package lua

const (
	// Lua plugin names
	LuaEngineName       = "lua.engine"
	LuaHTTPName         = "lua.http"
	LuaSQLName          = "lua.sql"
	LuaExecName         = "lua.exec"
	LuaWebSocketName    = "lua.websocket"
	LuaFSName           = "lua.fs"
	LuaStoreName        = "lua.store"
	LuaProcessName      = "lua.process"
	LuaFuncName         = "lua.func"
	LuaRegistryName     = "lua.registry"
	LuaSecurityName     = "lua.security"
	LuaTemplateName     = "lua.template"
	LuaCryptoName       = "lua.crypto"
	LuaTextName         = "lua.text"
	LuaBteaName         = "lua.btea"
	LuaExcelName        = "lua.excel"
	LuaTreeSitterName   = "lua.treesitter"
	LuaCloudStorageName = "lua.cloudstorage"
	LuaContractName     = "lua.contract"
	LuaOTelName         = "lua.otel"
	LuaExprName         = "lua.expr"
	LuaHTMLName         = "lua.html"
	LuaUUIDName         = "lua.uuid"
	LuaYAMLName         = "lua.yaml"
	LuaTimeName         = "lua.time"
	LuaSystemName       = "lua.system"
	LuaJSONName         = "lua.json"
	LuaBase64Name       = "lua.base64"
)
