package crypto

import (
	"context"
	"regexp"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"github.com/wippyai/runtime/runtime/lua/engine"
	lua "github.com/yuin/gopher-lua"
	"go.uber.org/zap"
)

func TestRandomModuleWithVM(t *testing.T) {
	logger := zap.NewNop()

	// Test loading the module and registering the random submodule
	t.Run("module loading", func(t *testing.T) {
		mod := NewCryptoModule()
		vm, err := engine.NewVM(logger, engine.WithLoader(mod.Name(), mod.Loader))
		require.NoError(t, err)
		defer vm.Close()

		err = vm.DoString(context.Background(), `
			local crypto = require("crypto")
			assert(type(crypto) == "table")
			assert(type(crypto.random) == "table")
			assert(type(crypto.random.bytes) == "function")
			assert(type(crypto.random.string) == "function")
			assert(type(crypto.random.uuid) == "function")
		`, "test")
		assert.NoError(t, err)
	})

	// Test input validation for randomBytes
	t.Run("randomBytes input validation", func(t *testing.T) {
		mod := NewCryptoModule()
		vm, err := engine.NewVM(logger, engine.WithLoader(mod.Name(), mod.Loader))
		require.NoError(t, err)
		defer vm.Close()

		// Test negative length
		t.Run("negative length", func(t *testing.T) {
			script := `
				local crypto = require("crypto")
				local bytes, err = crypto.random.bytes(-1)
				return err
			`
			err = vm.DoString(context.Background(), script, "test")
			require.NoError(t, err)
			// The error is returned on the Lua stack and not accessible here,
			// but the test passes if DoString succeeds
		})

		// Test zero length
		t.Run("zero length", func(t *testing.T) {
			script := `
				local crypto = require("crypto")
				local bytes, err = crypto.random.bytes(0)
				return err
			`
			err = vm.DoString(context.Background(), script, "test")
			require.NoError(t, err)
		})

		// Test non-integer length
		t.Run("non-integer length", func(t *testing.T) {
			script := `
				local crypto = require("crypto")
				local success, err = pcall(function()
					return crypto.random.bytes("not a number")
				end)
				return success
			`
			err = vm.DoString(context.Background(), script, "test")
			require.NoError(t, err)
		})
	})

	// Test randomBytes functionality
	t.Run("randomBytes functionality", func(t *testing.T) {
		mod := NewCryptoModule()
		vm, err := engine.NewVM(logger, engine.WithLoader(mod.Name(), mod.Loader))
		require.NoError(t, err)
		defer vm.Close()

		testCases := []struct {
			name   string
			length int
		}{
			{
				name:   "small length",
				length: 10,
			},
			{
				name:   "medium length",
				length: 100,
			},
			{
				name:   "large length",
				length: 1000,
			},
		}

		for _, tc := range testCases {
			t.Run(tc.name, func(t *testing.T) {
				script := `
					local crypto = require("crypto")
					function test(length)
						local result = {}
						local bytes, err = crypto.random.bytes(length)
						if err then
							result.success = false
							result.error = err
							return result
						end
						result.success = true
						result.length = #bytes
						result.bytes = bytes
						return result
					end
					return test
				`
				err = vm.Import(script, "test", "test")
				require.NoError(t, err)

				result, err := vm.Execute(context.Background(), "test", lua.LNumber(tc.length))
				require.NoError(t, err)

				resultTable, ok := result.(*lua.LTable)
				require.True(t, ok, "Expected result to be a table")

				success := resultTable.RawGetString("success")
				assert.Equal(t, lua.LTrue, success, "Expected operation to succeed")

				// Assert that the length matches the expected length
				length := int(resultTable.RawGetString("length").(lua.LNumber))
				assert.Equal(t, tc.length, length, "Generated bytes length mismatch")

				// We can't test the randomness here, but we can verify that we got bytes
				randomBytes := resultTable.RawGetString("bytes").(lua.LString)
				assert.NotEmpty(t, randomBytes.String(), "Generated bytes should not be empty")
			})
		}
	})

	// Test input validation for randomString
	t.Run("randomString input validation", func(t *testing.T) {
		mod := NewCryptoModule()
		vm, err := engine.NewVM(logger, engine.WithLoader(mod.Name(), mod.Loader))
		require.NoError(t, err)
		defer vm.Close()

		// Test negative length
		t.Run("negative length", func(t *testing.T) {
			script := `
				local crypto = require("crypto")
				local str, err = crypto.random.string(-1)
				return err
			`
			err = vm.DoString(context.Background(), script, "test")
			require.NoError(t, err)
		})

		// Test zero length
		t.Run("zero length", func(t *testing.T) {
			script := `
				local crypto = require("crypto")
				local str, err = crypto.random.string(0)
				return err
			`
			err = vm.DoString(context.Background(), script, "test")
			require.NoError(t, err)
		})

		// Test non-integer length
		t.Run("non-integer length", func(t *testing.T) {
			script := `
				local crypto = require("crypto")
				local success, err = pcall(function()
					return crypto.random.string("not a number")
				end)
				return success
			`
			err = vm.DoString(context.Background(), script, "test")
			require.NoError(t, err)
		})

		// Test empty charset
		t.Run("empty charset", func(t *testing.T) {
			script := `
				local crypto = require("crypto")
				local str, err = crypto.random.string(10, "")
				return err
			`
			err = vm.DoString(context.Background(), script, "test")
			require.NoError(t, err)
		})
	})

	// Test randomString functionality
	t.Run("randomString functionality", func(t *testing.T) {
		mod := NewCryptoModule()
		vm, err := engine.NewVM(logger, engine.WithLoader(mod.Name(), mod.Loader))
		require.NoError(t, err)
		defer vm.Close()

		testCases := []struct {
			name    string
			length  int
			charset string
		}{
			{
				name:    "default charset",
				length:  20,
				charset: "",
			},
			{
				name:    "numeric charset",
				length:  10,
				charset: "0123456789",
			},
			{
				name:    "custom charset",
				length:  15,
				charset: "abcdef",
			},
		}

		for _, tc := range testCases {
			t.Run(tc.name, func(t *testing.T) {
				var script string
				if tc.charset == "" {
					script = `
						local crypto = require("crypto")
						function test(length)
							local result = {}
							local str, err = crypto.random.string(length)
							if err then
								result.success = false
								result.error = err
								return result
							end
							result.success = true
							result.length = #str
							result.str = str
							return result
						end
						return test
					`
				} else {
					script = `
						local crypto = require("crypto")
						function test(length, charset)
							local result = {}
							local str, err = crypto.random.string(length, charset)
							if err then
								result.success = false
								result.error = err
								return result
							end
							result.success = true
							result.length = #str
							result.str = str
							return result
						end
						return test
					`
				}

				err = vm.Import(script, "test", "test")
				require.NoError(t, err)

				var result lua.LValue
				if tc.charset == "" {
					result, err = vm.Execute(context.Background(), "test", lua.LNumber(tc.length))
				} else {
					result, err = vm.Execute(context.Background(), "test", lua.LNumber(tc.length), lua.LString(tc.charset))
				}
				require.NoError(t, err)

				resultTable, ok := result.(*lua.LTable)
				require.True(t, ok, "Expected result to be a table")

				success := resultTable.RawGetString("success")
				assert.Equal(t, lua.LTrue, success, "Expected operation to succeed")

				// Assert that the length matches the expected length
				length := int(resultTable.RawGetString("length").(lua.LNumber))
				assert.Equal(t, tc.length, length, "Generated string length mismatch")

				// Verify that the generated string contains only characters from the charset
				randomStr := resultTable.RawGetString("str").(lua.LString).String()
				assert.NotEmpty(t, randomStr, "Generated string should not be empty")

				if tc.charset != "" {
					for _, c := range randomStr {
						assert.Contains(t, tc.charset, string(c), "Character not in charset")
					}
				}
			})
		}
	})

	// Test randomUUID functionality
	t.Run("randomUUID functionality", func(t *testing.T) {
		mod := NewCryptoModule()
		vm, err := engine.NewVM(logger, engine.WithLoader(mod.Name(), mod.Loader))
		require.NoError(t, err)
		defer vm.Close()

		script := `
			local crypto = require("crypto")
			function test()
				local result = {}
				local uuid, err = crypto.random.uuid()
				if err then
					result.success = false
					result.error = err
					return result
				end
				result.success = true
				result.uuid = uuid
				return result
			end
			return test
		`
		err = vm.Import(script, "test", "test")
		require.NoError(t, err)

		// Get multiple UUIDs to ensure they're unique
		var uuids []string
		for i := 0; i < 5; i++ {
			result, err := vm.Execute(context.Background(), "test")
			require.NoError(t, err)

			resultTable, ok := result.(*lua.LTable)
			require.True(t, ok, "Expected result to be a table")

			success := resultTable.RawGetString("success")
			assert.Equal(t, lua.LTrue, success, "Expected operation to succeed")

			uuid := resultTable.RawGetString("uuid").(lua.LString).String()
			uuids = append(uuids, uuid)

			// Verify UUID format (8-4-4-4-12)
			uuidRegex := regexp.MustCompile(`^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$`)
			assert.True(t, uuidRegex.MatchString(uuid), "Generated UUID does not match expected format: %s", uuid)
		}

		// Verify uniqueness
		uniqueUUIDs := make(map[string]bool)
		for _, uuid := range uuids {
			uniqueUUIDs[uuid] = true
		}
		assert.Equal(t, len(uuids), len(uniqueUUIDs), "Generated UUIDs should be unique")
	})

	// Test error handling in Lua
	t.Run("error handling in Lua", func(t *testing.T) {
		mod := NewCryptoModule()
		vm, err := engine.NewVM(logger, engine.WithLoader(mod.Name(), mod.Loader))
		require.NoError(t, err)
		defer vm.Close()

		script := `
			local crypto = require("crypto")
			function test()
				-- Test error handling for random functions
				local results = {}
				
				-- Test bytes with invalid input
				local success, result = pcall(function()
					return crypto.random.bytes("not a number")
				end)
				assert(not success, "Expected error for bytes with non-number input")
				
				-- Test string with invalid input
				success, result = pcall(function()
					return crypto.random.string("not a number")
				end)
				assert(not success, "Expected error for string with non-number input")
				
				-- Test with valid inputs (should not error)
				local bytes, err = crypto.random.bytes(10)
				assert(err == nil, "Unexpected error for bytes with valid input")
				assert(#bytes == 10, "Expected 10 bytes, got " .. #bytes)
				
				local str, err = crypto.random.string(10)
				assert(err == nil, "Unexpected error for string with valid input")
				assert(#str == 10, "Expected string of length 10, got " .. #str)
				
				local uuid, err = crypto.random.uuid()
				assert(err == nil, "Unexpected error for uuid with valid input")
				assert(#uuid == 36, "Expected UUID of length 36, got " .. #uuid)
				
				results = {
					bytes_length = #bytes,
					string_length = #str,
					uuid_length = #uuid
				}
				
				return results
			end
			return test
		`
		err = vm.Import(script, "test", "test")
		require.NoError(t, err)

		result, err := vm.Execute(context.Background(), "test")
		require.NoError(t, err)
		assert.NotNil(t, result)
		assert.Equal(t, lua.LTTable, result.Type())
	})
}
