// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: wippy/api/hub/module/v1/message.proto

package modulev1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Visibility int32

const (
	Visibility_VISIBILITY_UNSPECIFIED Visibility = 0
	Visibility_VISIBILITY_PUBLIC      Visibility = 1
	Visibility_VISIBILITY_PRIVATE     Visibility = 2
	Visibility_VISIBILITY_INTERNAL    Visibility = 3
)

// Enum value maps for Visibility.
var (
	Visibility_name = map[int32]string{
		0: "VISIBILITY_UNSPECIFIED",
		1: "VISIBILITY_PUBLIC",
		2: "VISIBILITY_PRIVATE",
		3: "VISIBILITY_INTERNAL",
	}
	Visibility_value = map[string]int32{
		"VISIBILITY_UNSPECIFIED": 0,
		"VISIBILITY_PUBLIC":      1,
		"VISIBILITY_PRIVATE":     2,
		"VISIBILITY_INTERNAL":    3,
	}
)

func (x Visibility) Enum() *Visibility {
	p := new(Visibility)
	*p = x
	return p
}

func (x Visibility) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Visibility) Descriptor() protoreflect.EnumDescriptor {
	return file_wippy_api_hub_module_v1_message_proto_enumTypes[0].Descriptor()
}

func (Visibility) Type() protoreflect.EnumType {
	return &file_wippy_api_hub_module_v1_message_proto_enumTypes[0]
}

func (x Visibility) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Visibility.Descriptor instead.
func (Visibility) EnumDescriptor() ([]byte, []int) {
	return file_wippy_api_hub_module_v1_message_proto_rawDescGZIP(), []int{0}
}

type ModuleType int32

const (
	ModuleType_MODULE_TYPE_UNSPECIFIED ModuleType = 0
	ModuleType_MODULE_TYPE_LIBRARY     ModuleType = 1
	ModuleType_MODULE_TYPE_APPLICATION ModuleType = 2
	ModuleType_MODULE_TYPE_AGENT       ModuleType = 3
	ModuleType_MODULE_TYPE_PLUGIN      ModuleType = 4
)

// Enum value maps for ModuleType.
var (
	ModuleType_name = map[int32]string{
		0: "MODULE_TYPE_UNSPECIFIED",
		1: "MODULE_TYPE_LIBRARY",
		2: "MODULE_TYPE_APPLICATION",
		3: "MODULE_TYPE_AGENT",
		4: "MODULE_TYPE_PLUGIN",
	}
	ModuleType_value = map[string]int32{
		"MODULE_TYPE_UNSPECIFIED": 0,
		"MODULE_TYPE_LIBRARY":     1,
		"MODULE_TYPE_APPLICATION": 2,
		"MODULE_TYPE_AGENT":       3,
		"MODULE_TYPE_PLUGIN":      4,
	}
)

func (x ModuleType) Enum() *ModuleType {
	p := new(ModuleType)
	*p = x
	return p
}

func (x ModuleType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ModuleType) Descriptor() protoreflect.EnumDescriptor {
	return file_wippy_api_hub_module_v1_message_proto_enumTypes[1].Descriptor()
}

func (ModuleType) Type() protoreflect.EnumType {
	return &file_wippy_api_hub_module_v1_message_proto_enumTypes[1]
}

func (x ModuleType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ModuleType.Descriptor instead.
func (ModuleType) EnumDescriptor() ([]byte, []int) {
	return file_wippy_api_hub_module_v1_message_proto_rawDescGZIP(), []int{1}
}

// Reference to a module.
type ModuleRef struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Value:
	//
	//	*ModuleRef_Id
	//	*ModuleRef_Name
	Value         isModuleRef_Value `protobuf_oneof:"value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ModuleRef) Reset() {
	*x = ModuleRef{}
	mi := &file_wippy_api_hub_module_v1_message_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModuleRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModuleRef) ProtoMessage() {}

func (x *ModuleRef) ProtoReflect() protoreflect.Message {
	mi := &file_wippy_api_hub_module_v1_message_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModuleRef.ProtoReflect.Descriptor instead.
func (*ModuleRef) Descriptor() ([]byte, []int) {
	return file_wippy_api_hub_module_v1_message_proto_rawDescGZIP(), []int{0}
}

func (x *ModuleRef) GetValue() isModuleRef_Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *ModuleRef) GetId() string {
	if x != nil {
		if x, ok := x.Value.(*ModuleRef_Id); ok {
			return x.Id
		}
	}
	return ""
}

func (x *ModuleRef) GetName() *ModuleName {
	if x != nil {
		if x, ok := x.Value.(*ModuleRef_Name); ok {
			return x.Name
		}
	}
	return nil
}

type isModuleRef_Value interface {
	isModuleRef_Value()
}

type ModuleRef_Id struct {
	Id string `protobuf:"bytes,1,opt,name=id,proto3,oneof"`
}

type ModuleRef_Name struct {
	Name *ModuleName `protobuf:"bytes,2,opt,name=name,proto3,oneof"`
}

func (*ModuleRef_Id) isModuleRef_Value() {}

func (*ModuleRef_Name) isModuleRef_Value() {}

// Module name in org/name format.
type ModuleName struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Org           string                 `protobuf:"bytes,1,opt,name=org,proto3" json:"org,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ModuleName) Reset() {
	*x = ModuleName{}
	mi := &file_wippy_api_hub_module_v1_message_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModuleName) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModuleName) ProtoMessage() {}

func (x *ModuleName) ProtoReflect() protoreflect.Message {
	mi := &file_wippy_api_hub_module_v1_message_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModuleName.ProtoReflect.Descriptor instead.
func (*ModuleName) Descriptor() ([]byte, []int) {
	return file_wippy_api_hub_module_v1_message_proto_rawDescGZIP(), []int{1}
}

func (x *ModuleName) GetOrg() string {
	if x != nil {
		return x.Org
	}
	return ""
}

func (x *ModuleName) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// A module in the hub.
type Module struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Id                 string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name               string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	DisplayName        string                 `protobuf:"bytes,3,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	OrganizationId     string                 `protobuf:"bytes,4,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	OrganizationName   string                 `protobuf:"bytes,5,opt,name=organization_name,json=organizationName,proto3" json:"organization_name,omitempty"`
	Description        string                 `protobuf:"bytes,6,opt,name=description,proto3" json:"description,omitempty"`
	LatestVersion      string                 `protobuf:"bytes,7,opt,name=latest_version,json=latestVersion,proto3" json:"latest_version,omitempty"`
	TotalDownloads     uint64                 `protobuf:"varint,8,opt,name=total_downloads,json=totalDownloads,proto3" json:"total_downloads,omitempty"`
	FavoritesCount     uint64                 `protobuf:"varint,9,opt,name=favorites_count,json=favoritesCount,proto3" json:"favorites_count,omitempty"`
	CreateTime         *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	UpdateTime         *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty"`
	Visibility         Visibility             `protobuf:"varint,12,opt,name=visibility,proto3,enum=wippy.api.hub.module.v1.Visibility" json:"visibility,omitempty"`
	Deprecated         bool                   `protobuf:"varint,13,opt,name=deprecated,proto3" json:"deprecated,omitempty"`
	DeprecationMessage string                 `protobuf:"bytes,14,opt,name=deprecation_message,json=deprecationMessage,proto3" json:"deprecation_message,omitempty"`
	Type               ModuleType             `protobuf:"varint,15,opt,name=type,proto3,enum=wippy.api.hub.module.v1.ModuleType" json:"type,omitempty"`
	Keywords           []string               `protobuf:"bytes,16,rep,name=keywords,proto3" json:"keywords,omitempty"`
	License            string                 `protobuf:"bytes,17,opt,name=license,proto3" json:"license,omitempty"`
	Repository         string                 `protobuf:"bytes,18,opt,name=repository,proto3" json:"repository,omitempty"`
	Homepage           string                 `protobuf:"bytes,19,opt,name=homepage,proto3" json:"homepage,omitempty"`
	Protected          bool                   `protobuf:"varint,20,opt,name=protected,proto3" json:"protected,omitempty"`
	Contracts          []*Contract            `protobuf:"bytes,21,rep,name=contracts,proto3" json:"contracts,omitempty"`
	DownloadStats      []*DownloadStat        `protobuf:"bytes,22,rep,name=download_stats,json=downloadStats,proto3" json:"download_stats,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *Module) Reset() {
	*x = Module{}
	mi := &file_wippy_api_hub_module_v1_message_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Module) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Module) ProtoMessage() {}

func (x *Module) ProtoReflect() protoreflect.Message {
	mi := &file_wippy_api_hub_module_v1_message_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Module.ProtoReflect.Descriptor instead.
func (*Module) Descriptor() ([]byte, []int) {
	return file_wippy_api_hub_module_v1_message_proto_rawDescGZIP(), []int{2}
}

func (x *Module) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Module) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Module) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *Module) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *Module) GetOrganizationName() string {
	if x != nil {
		return x.OrganizationName
	}
	return ""
}

func (x *Module) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Module) GetLatestVersion() string {
	if x != nil {
		return x.LatestVersion
	}
	return ""
}

func (x *Module) GetTotalDownloads() uint64 {
	if x != nil {
		return x.TotalDownloads
	}
	return 0
}

func (x *Module) GetFavoritesCount() uint64 {
	if x != nil {
		return x.FavoritesCount
	}
	return 0
}

func (x *Module) GetCreateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CreateTime
	}
	return nil
}

func (x *Module) GetUpdateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdateTime
	}
	return nil
}

func (x *Module) GetVisibility() Visibility {
	if x != nil {
		return x.Visibility
	}
	return Visibility_VISIBILITY_UNSPECIFIED
}

func (x *Module) GetDeprecated() bool {
	if x != nil {
		return x.Deprecated
	}
	return false
}

func (x *Module) GetDeprecationMessage() string {
	if x != nil {
		return x.DeprecationMessage
	}
	return ""
}

func (x *Module) GetType() ModuleType {
	if x != nil {
		return x.Type
	}
	return ModuleType_MODULE_TYPE_UNSPECIFIED
}

func (x *Module) GetKeywords() []string {
	if x != nil {
		return x.Keywords
	}
	return nil
}

func (x *Module) GetLicense() string {
	if x != nil {
		return x.License
	}
	return ""
}

func (x *Module) GetRepository() string {
	if x != nil {
		return x.Repository
	}
	return ""
}

func (x *Module) GetHomepage() string {
	if x != nil {
		return x.Homepage
	}
	return ""
}

func (x *Module) GetProtected() bool {
	if x != nil {
		return x.Protected
	}
	return false
}

func (x *Module) GetContracts() []*Contract {
	if x != nil {
		return x.Contracts
	}
	return nil
}

func (x *Module) GetDownloadStats() []*DownloadStat {
	if x != nil {
		return x.DownloadStats
	}
	return nil
}

// Organization in the hub.
type Organization struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Id                  string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	DisplayName         string                 `protobuf:"bytes,3,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	Description         string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	AvatarUrl           string                 `protobuf:"bytes,5,opt,name=avatar_url,json=avatarUrl,proto3" json:"avatar_url,omitempty"`
	Website             string                 `protobuf:"bytes,6,opt,name=website,proto3" json:"website,omitempty"`
	CreateTime          *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	HasPaidSubscription bool                   `protobuf:"varint,8,opt,name=has_paid_subscription,json=hasPaidSubscription,proto3" json:"has_paid_subscription,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *Organization) Reset() {
	*x = Organization{}
	mi := &file_wippy_api_hub_module_v1_message_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Organization) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Organization) ProtoMessage() {}

func (x *Organization) ProtoReflect() protoreflect.Message {
	mi := &file_wippy_api_hub_module_v1_message_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Organization.ProtoReflect.Descriptor instead.
func (*Organization) Descriptor() ([]byte, []int) {
	return file_wippy_api_hub_module_v1_message_proto_rawDescGZIP(), []int{3}
}

func (x *Organization) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Organization) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Organization) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *Organization) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Organization) GetAvatarUrl() string {
	if x != nil {
		return x.AvatarUrl
	}
	return ""
}

func (x *Organization) GetWebsite() string {
	if x != nil {
		return x.Website
	}
	return ""
}

func (x *Organization) GetCreateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CreateTime
	}
	return nil
}

func (x *Organization) GetHasPaidSubscription() bool {
	if x != nil {
		return x.HasPaidSubscription
	}
	return false
}

// Contract provided by a module.
type Contract struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Methods       []*ContractMethod      `protobuf:"bytes,4,rep,name=methods,proto3" json:"methods,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Contract) Reset() {
	*x = Contract{}
	mi := &file_wippy_api_hub_module_v1_message_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Contract) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Contract) ProtoMessage() {}

func (x *Contract) ProtoReflect() protoreflect.Message {
	mi := &file_wippy_api_hub_module_v1_message_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Contract.ProtoReflect.Descriptor instead.
func (*Contract) Descriptor() ([]byte, []int) {
	return file_wippy_api_hub_module_v1_message_proto_rawDescGZIP(), []int{4}
}

func (x *Contract) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Contract) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Contract) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Contract) GetMethods() []*ContractMethod {
	if x != nil {
		return x.Methods
	}
	return nil
}

// Method in a contract.
type ContractMethod struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContractMethod) Reset() {
	*x = ContractMethod{}
	mi := &file_wippy_api_hub_module_v1_message_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContractMethod) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContractMethod) ProtoMessage() {}

func (x *ContractMethod) ProtoReflect() protoreflect.Message {
	mi := &file_wippy_api_hub_module_v1_message_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContractMethod.ProtoReflect.Descriptor instead.
func (*ContractMethod) Descriptor() ([]byte, []int) {
	return file_wippy_api_hub_module_v1_message_proto_rawDescGZIP(), []int{5}
}

func (x *ContractMethod) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ContractMethod) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

// Daily download statistics.
type DownloadStat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Date          string                 `protobuf:"bytes,1,opt,name=date,proto3" json:"date,omitempty"`
	Count         uint64                 `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownloadStat) Reset() {
	*x = DownloadStat{}
	mi := &file_wippy_api_hub_module_v1_message_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadStat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadStat) ProtoMessage() {}

func (x *DownloadStat) ProtoReflect() protoreflect.Message {
	mi := &file_wippy_api_hub_module_v1_message_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadStat.ProtoReflect.Descriptor instead.
func (*DownloadStat) Descriptor() ([]byte, []int) {
	return file_wippy_api_hub_module_v1_message_proto_rawDescGZIP(), []int{6}
}

func (x *DownloadStat) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *DownloadStat) GetCount() uint64 {
	if x != nil {
		return x.Count
	}
	return 0
}

var File_wippy_api_hub_module_v1_message_proto protoreflect.FileDescriptor

const file_wippy_api_hub_module_v1_message_proto_rawDesc = "" +
	"\n" +
	"%wippy/api/hub/module/v1/message.proto\x12\x17wippy.api.hub.module.v1\x1a\x1bbuf/validate/validate.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"k\n" +
	"\tModuleRef\x12\x1a\n" +
	"\x02id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01H\x00R\x02id\x129\n" +
	"\x04name\x18\x02 \x01(\v2#.wippy.api.hub.module.v1.ModuleNameH\x00R\x04nameB\a\n" +
	"\x05value\"H\n" +
	"\n" +
	"ModuleName\x12\x1b\n" +
	"\x03org\x18\x01 \x01(\tB\t\xbaH\x06r\x04\x10\x01\x18@R\x03org\x12\x1d\n" +
	"\x04name\x18\x02 \x01(\tB\t\xbaH\x06r\x04\x10\x01\x18@R\x04name\"\xda\a\n" +
	"\x06Module\x12\x18\n" +
	"\x02id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\x02id\x120\n" +
	"\x04name\x18\x02 \x01(\tB\x1c\xbaH\x19r\x17\x10\x01\x18@2\x11^[a-z][a-z0-9-]*$R\x04name\x12!\n" +
	"\fdisplay_name\x18\x03 \x01(\tR\vdisplayName\x121\n" +
	"\x0forganization_id\x18\x04 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\x0eorganizationId\x12+\n" +
	"\x11organization_name\x18\x05 \x01(\tR\x10organizationName\x12 \n" +
	"\vdescription\x18\x06 \x01(\tR\vdescription\x12%\n" +
	"\x0elatest_version\x18\a \x01(\tR\rlatestVersion\x12'\n" +
	"\x0ftotal_downloads\x18\b \x01(\x04R\x0etotalDownloads\x12'\n" +
	"\x0ffavorites_count\x18\t \x01(\x04R\x0efavoritesCount\x12;\n" +
	"\vcreate_time\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"createTime\x12;\n" +
	"\vupdate_time\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"updateTime\x12C\n" +
	"\n" +
	"visibility\x18\f \x01(\x0e2#.wippy.api.hub.module.v1.VisibilityR\n" +
	"visibility\x12\x1e\n" +
	"\n" +
	"deprecated\x18\r \x01(\bR\n" +
	"deprecated\x12/\n" +
	"\x13deprecation_message\x18\x0e \x01(\tR\x12deprecationMessage\x127\n" +
	"\x04type\x18\x0f \x01(\x0e2#.wippy.api.hub.module.v1.ModuleTypeR\x04type\x12\x1a\n" +
	"\bkeywords\x18\x10 \x03(\tR\bkeywords\x12\x18\n" +
	"\alicense\x18\x11 \x01(\tR\alicense\x12\x1e\n" +
	"\n" +
	"repository\x18\x12 \x01(\tR\n" +
	"repository\x12\x1a\n" +
	"\bhomepage\x18\x13 \x01(\tR\bhomepage\x12\x1c\n" +
	"\tprotected\x18\x14 \x01(\bR\tprotected\x12?\n" +
	"\tcontracts\x18\x15 \x03(\v2!.wippy.api.hub.module.v1.ContractR\tcontracts\x12L\n" +
	"\x0edownload_stats\x18\x16 \x03(\v2%.wippy.api.hub.module.v1.DownloadStatR\rdownloadStats\"\xc9\x02\n" +
	"\fOrganization\x12\x18\n" +
	"\x02id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\x02id\x120\n" +
	"\x04name\x18\x02 \x01(\tB\x1c\xbaH\x19r\x17\x10\x01\x18@2\x11^[a-z][a-z0-9-]*$R\x04name\x12!\n" +
	"\fdisplay_name\x18\x03 \x01(\tR\vdisplayName\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x1d\n" +
	"\n" +
	"avatar_url\x18\x05 \x01(\tR\tavatarUrl\x12\x18\n" +
	"\awebsite\x18\x06 \x01(\tR\awebsite\x12;\n" +
	"\vcreate_time\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"createTime\x122\n" +
	"\x15has_paid_subscription\x18\b \x01(\bR\x13hasPaidSubscription\"\x93\x01\n" +
	"\bContract\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12A\n" +
	"\amethods\x18\x04 \x03(\v2'.wippy.api.hub.module.v1.ContractMethodR\amethods\"F\n" +
	"\x0eContractMethod\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\"8\n" +
	"\fDownloadStat\x12\x12\n" +
	"\x04date\x18\x01 \x01(\tR\x04date\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x04R\x05count*p\n" +
	"\n" +
	"Visibility\x12\x1a\n" +
	"\x16VISIBILITY_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11VISIBILITY_PUBLIC\x10\x01\x12\x16\n" +
	"\x12VISIBILITY_PRIVATE\x10\x02\x12\x17\n" +
	"\x13VISIBILITY_INTERNAL\x10\x03*\x8e\x01\n" +
	"\n" +
	"ModuleType\x12\x1b\n" +
	"\x17MODULE_TYPE_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13MODULE_TYPE_LIBRARY\x10\x01\x12\x1b\n" +
	"\x17MODULE_TYPE_APPLICATION\x10\x02\x12\x15\n" +
	"\x11MODULE_TYPE_AGENT\x10\x03\x12\x16\n" +
	"\x12MODULE_TYPE_PLUGIN\x10\x04B\xf1\x01\n" +
	"\x1bcom.wippy.api.hub.module.v1B\fMessageProtoP\x01ZCgithub.com/wippyai/runtime/api/hub/wippy/api/hub/module/v1;modulev1\xa2\x02\x04WAHM\xaa\x02\x17Wippy.Api.Hub.Module.V1\xca\x02\x17Wippy\\Api\\Hub\\Module\\V1\xe2\x02#Wippy\\Api\\Hub\\Module\\V1\\GPBMetadata\xea\x02\x1bWippy::Api::Hub::Module::V1b\x06proto3"

var (
	file_wippy_api_hub_module_v1_message_proto_rawDescOnce sync.Once
	file_wippy_api_hub_module_v1_message_proto_rawDescData []byte
)

func file_wippy_api_hub_module_v1_message_proto_rawDescGZIP() []byte {
	file_wippy_api_hub_module_v1_message_proto_rawDescOnce.Do(func() {
		file_wippy_api_hub_module_v1_message_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_wippy_api_hub_module_v1_message_proto_rawDesc), len(file_wippy_api_hub_module_v1_message_proto_rawDesc)))
	})
	return file_wippy_api_hub_module_v1_message_proto_rawDescData
}

var file_wippy_api_hub_module_v1_message_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_wippy_api_hub_module_v1_message_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_wippy_api_hub_module_v1_message_proto_goTypes = []any{
	(Visibility)(0),               // 0: wippy.api.hub.module.v1.Visibility
	(ModuleType)(0),               // 1: wippy.api.hub.module.v1.ModuleType
	(*ModuleRef)(nil),             // 2: wippy.api.hub.module.v1.ModuleRef
	(*ModuleName)(nil),            // 3: wippy.api.hub.module.v1.ModuleName
	(*Module)(nil),                // 4: wippy.api.hub.module.v1.Module
	(*Organization)(nil),          // 5: wippy.api.hub.module.v1.Organization
	(*Contract)(nil),              // 6: wippy.api.hub.module.v1.Contract
	(*ContractMethod)(nil),        // 7: wippy.api.hub.module.v1.ContractMethod
	(*DownloadStat)(nil),          // 8: wippy.api.hub.module.v1.DownloadStat
	(*timestamppb.Timestamp)(nil), // 9: google.protobuf.Timestamp
}
var file_wippy_api_hub_module_v1_message_proto_depIdxs = []int32{
	3, // 0: wippy.api.hub.module.v1.ModuleRef.name:type_name -> wippy.api.hub.module.v1.ModuleName
	9, // 1: wippy.api.hub.module.v1.Module.create_time:type_name -> google.protobuf.Timestamp
	9, // 2: wippy.api.hub.module.v1.Module.update_time:type_name -> google.protobuf.Timestamp
	0, // 3: wippy.api.hub.module.v1.Module.visibility:type_name -> wippy.api.hub.module.v1.Visibility
	1, // 4: wippy.api.hub.module.v1.Module.type:type_name -> wippy.api.hub.module.v1.ModuleType
	6, // 5: wippy.api.hub.module.v1.Module.contracts:type_name -> wippy.api.hub.module.v1.Contract
	8, // 6: wippy.api.hub.module.v1.Module.download_stats:type_name -> wippy.api.hub.module.v1.DownloadStat
	9, // 7: wippy.api.hub.module.v1.Organization.create_time:type_name -> google.protobuf.Timestamp
	7, // 8: wippy.api.hub.module.v1.Contract.methods:type_name -> wippy.api.hub.module.v1.ContractMethod
	9, // [9:9] is the sub-list for method output_type
	9, // [9:9] is the sub-list for method input_type
	9, // [9:9] is the sub-list for extension type_name
	9, // [9:9] is the sub-list for extension extendee
	0, // [0:9] is the sub-list for field type_name
}

func init() { file_wippy_api_hub_module_v1_message_proto_init() }
func file_wippy_api_hub_module_v1_message_proto_init() {
	if File_wippy_api_hub_module_v1_message_proto != nil {
		return
	}
	file_wippy_api_hub_module_v1_message_proto_msgTypes[0].OneofWrappers = []any{
		(*ModuleRef_Id)(nil),
		(*ModuleRef_Name)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_wippy_api_hub_module_v1_message_proto_rawDesc), len(file_wippy_api_hub_module_v1_message_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_wippy_api_hub_module_v1_message_proto_goTypes,
		DependencyIndexes: file_wippy_api_hub_module_v1_message_proto_depIdxs,
		EnumInfos:         file_wippy_api_hub_module_v1_message_proto_enumTypes,
		MessageInfos:      file_wippy_api_hub_module_v1_message_proto_msgTypes,
	}.Build()
	File_wippy_api_hub_module_v1_message_proto = out.File
	file_wippy_api_hub_module_v1_message_proto_goTypes = nil
	file_wippy_api_hub_module_v1_message_proto_depIdxs = nil
}
