// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: wippy/api/hub/favorite/v1/service.proto

package favoritev1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	v1 "github.com/wippyai/runtime/api/hub/wippy/api/hub/module/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AddFavoriteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Module        *v1.ModuleRef          `protobuf:"bytes,1,opt,name=module,proto3" json:"module,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddFavoriteRequest) Reset() {
	*x = AddFavoriteRequest{}
	mi := &file_wippy_api_hub_favorite_v1_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddFavoriteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddFavoriteRequest) ProtoMessage() {}

func (x *AddFavoriteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wippy_api_hub_favorite_v1_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddFavoriteRequest.ProtoReflect.Descriptor instead.
func (*AddFavoriteRequest) Descriptor() ([]byte, []int) {
	return file_wippy_api_hub_favorite_v1_service_proto_rawDescGZIP(), []int{0}
}

func (x *AddFavoriteRequest) GetModule() *v1.ModuleRef {
	if x != nil {
		return x.Module
	}
	return nil
}

type AddFavoriteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddFavoriteResponse) Reset() {
	*x = AddFavoriteResponse{}
	mi := &file_wippy_api_hub_favorite_v1_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddFavoriteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddFavoriteResponse) ProtoMessage() {}

func (x *AddFavoriteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_wippy_api_hub_favorite_v1_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddFavoriteResponse.ProtoReflect.Descriptor instead.
func (*AddFavoriteResponse) Descriptor() ([]byte, []int) {
	return file_wippy_api_hub_favorite_v1_service_proto_rawDescGZIP(), []int{1}
}

type RemoveFavoriteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Module        *v1.ModuleRef          `protobuf:"bytes,1,opt,name=module,proto3" json:"module,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveFavoriteRequest) Reset() {
	*x = RemoveFavoriteRequest{}
	mi := &file_wippy_api_hub_favorite_v1_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveFavoriteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveFavoriteRequest) ProtoMessage() {}

func (x *RemoveFavoriteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wippy_api_hub_favorite_v1_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveFavoriteRequest.ProtoReflect.Descriptor instead.
func (*RemoveFavoriteRequest) Descriptor() ([]byte, []int) {
	return file_wippy_api_hub_favorite_v1_service_proto_rawDescGZIP(), []int{2}
}

func (x *RemoveFavoriteRequest) GetModule() *v1.ModuleRef {
	if x != nil {
		return x.Module
	}
	return nil
}

type RemoveFavoriteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveFavoriteResponse) Reset() {
	*x = RemoveFavoriteResponse{}
	mi := &file_wippy_api_hub_favorite_v1_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveFavoriteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveFavoriteResponse) ProtoMessage() {}

func (x *RemoveFavoriteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_wippy_api_hub_favorite_v1_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveFavoriteResponse.ProtoReflect.Descriptor instead.
func (*RemoveFavoriteResponse) Descriptor() ([]byte, []int) {
	return file_wippy_api_hub_favorite_v1_service_proto_rawDescGZIP(), []int{3}
}

type IsFavoritedRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Module        *v1.ModuleRef          `protobuf:"bytes,1,opt,name=module,proto3" json:"module,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IsFavoritedRequest) Reset() {
	*x = IsFavoritedRequest{}
	mi := &file_wippy_api_hub_favorite_v1_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsFavoritedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsFavoritedRequest) ProtoMessage() {}

func (x *IsFavoritedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wippy_api_hub_favorite_v1_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsFavoritedRequest.ProtoReflect.Descriptor instead.
func (*IsFavoritedRequest) Descriptor() ([]byte, []int) {
	return file_wippy_api_hub_favorite_v1_service_proto_rawDescGZIP(), []int{4}
}

func (x *IsFavoritedRequest) GetModule() *v1.ModuleRef {
	if x != nil {
		return x.Module
	}
	return nil
}

type IsFavoritedResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Favorited     bool                   `protobuf:"varint,1,opt,name=favorited,proto3" json:"favorited,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IsFavoritedResponse) Reset() {
	*x = IsFavoritedResponse{}
	mi := &file_wippy_api_hub_favorite_v1_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsFavoritedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsFavoritedResponse) ProtoMessage() {}

func (x *IsFavoritedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_wippy_api_hub_favorite_v1_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsFavoritedResponse.ProtoReflect.Descriptor instead.
func (*IsFavoritedResponse) Descriptor() ([]byte, []int) {
	return file_wippy_api_hub_favorite_v1_service_proto_rawDescGZIP(), []int{5}
}

func (x *IsFavoritedResponse) GetFavorited() bool {
	if x != nil {
		return x.Favorited
	}
	return false
}

type ListFavoritesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFavoritesRequest) Reset() {
	*x = ListFavoritesRequest{}
	mi := &file_wippy_api_hub_favorite_v1_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFavoritesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFavoritesRequest) ProtoMessage() {}

func (x *ListFavoritesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wippy_api_hub_favorite_v1_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFavoritesRequest.ProtoReflect.Descriptor instead.
func (*ListFavoritesRequest) Descriptor() ([]byte, []int) {
	return file_wippy_api_hub_favorite_v1_service_proto_rawDescGZIP(), []int{6}
}

func (x *ListFavoritesRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListFavoritesRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ListFavoritesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Modules       []*v1.Module           `protobuf:"bytes,1,rep,name=modules,proto3" json:"modules,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFavoritesResponse) Reset() {
	*x = ListFavoritesResponse{}
	mi := &file_wippy_api_hub_favorite_v1_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFavoritesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFavoritesResponse) ProtoMessage() {}

func (x *ListFavoritesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_wippy_api_hub_favorite_v1_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFavoritesResponse.ProtoReflect.Descriptor instead.
func (*ListFavoritesResponse) Descriptor() ([]byte, []int) {
	return file_wippy_api_hub_favorite_v1_service_proto_rawDescGZIP(), []int{7}
}

func (x *ListFavoritesResponse) GetModules() []*v1.Module {
	if x != nil {
		return x.Modules
	}
	return nil
}

func (x *ListFavoritesResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListFavoritesResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListFavoritesResponse) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

var File_wippy_api_hub_favorite_v1_service_proto protoreflect.FileDescriptor

const file_wippy_api_hub_favorite_v1_service_proto_rawDesc = "" +
	"\n" +
	"'wippy/api/hub/favorite/v1/service.proto\x12\x19wippy.api.hub.favorite.v1\x1a\x1bbuf/validate/validate.proto\x1a%wippy/api/hub/module/v1/message.proto\"X\n" +
	"\x12AddFavoriteRequest\x12B\n" +
	"\x06module\x18\x01 \x01(\v2\".wippy.api.hub.module.v1.ModuleRefB\x06\xbaH\x03\xc8\x01\x01R\x06module\"\x15\n" +
	"\x13AddFavoriteResponse\"[\n" +
	"\x15RemoveFavoriteRequest\x12B\n" +
	"\x06module\x18\x01 \x01(\v2\".wippy.api.hub.module.v1.ModuleRefB\x06\xbaH\x03\xc8\x01\x01R\x06module\"\x18\n" +
	"\x16RemoveFavoriteResponse\"X\n" +
	"\x12IsFavoritedRequest\x12B\n" +
	"\x06module\x18\x01 \x01(\v2\".wippy.api.hub.module.v1.ModuleRefB\x06\xbaH\x03\xc8\x01\x01R\x06module\"3\n" +
	"\x13IsFavoritedResponse\x12\x1c\n" +
	"\tfavorited\x18\x01 \x01(\bR\tfavorited\"^\n" +
	"\x14ListFavoritesRequest\x12\x1e\n" +
	"\x04page\x18\x01 \x01(\x05B\n" +
	"\xbaH\a\x1a\x05\x18\x90N(\x00R\x04page\x12&\n" +
	"\tpage_size\x18\x02 \x01(\x05B\t\xbaH\x06\x1a\x04\x18d(\x01R\bpageSize\"\x99\x01\n" +
	"\x15ListFavoritesResponse\x129\n" +
	"\amodules\x18\x01 \x03(\v2\x1f.wippy.api.hub.module.v1.ModuleR\amodules\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize2\xec\x03\n" +
	"\x0fFavoriteService\x12q\n" +
	"\vAddFavorite\x12-.wippy.api.hub.favorite.v1.AddFavoriteRequest\x1a..wippy.api.hub.favorite.v1.AddFavoriteResponse\"\x03\x90\x02\x02\x12z\n" +
	"\x0eRemoveFavorite\x120.wippy.api.hub.favorite.v1.RemoveFavoriteRequest\x1a1.wippy.api.hub.favorite.v1.RemoveFavoriteResponse\"\x03\x90\x02\x02\x12q\n" +
	"\vIsFavorited\x12-.wippy.api.hub.favorite.v1.IsFavoritedRequest\x1a..wippy.api.hub.favorite.v1.IsFavoritedResponse\"\x03\x90\x02\x01\x12w\n" +
	"\rListFavorites\x12/.wippy.api.hub.favorite.v1.ListFavoritesRequest\x1a0.wippy.api.hub.favorite.v1.ListFavoritesResponse\"\x03\x90\x02\x01B\xff\x01\n" +
	"\x1dcom.wippy.api.hub.favorite.v1B\fServiceProtoP\x01ZGgithub.com/wippyai/runtime/api/hub/wippy/api/hub/favorite/v1;favoritev1\xa2\x02\x04WAHF\xaa\x02\x19Wippy.Api.Hub.Favorite.V1\xca\x02\x19Wippy\\Api\\Hub\\Favorite\\V1\xe2\x02%Wippy\\Api\\Hub\\Favorite\\V1\\GPBMetadata\xea\x02\x1dWippy::Api::Hub::Favorite::V1b\x06proto3"

var (
	file_wippy_api_hub_favorite_v1_service_proto_rawDescOnce sync.Once
	file_wippy_api_hub_favorite_v1_service_proto_rawDescData []byte
)

func file_wippy_api_hub_favorite_v1_service_proto_rawDescGZIP() []byte {
	file_wippy_api_hub_favorite_v1_service_proto_rawDescOnce.Do(func() {
		file_wippy_api_hub_favorite_v1_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_wippy_api_hub_favorite_v1_service_proto_rawDesc), len(file_wippy_api_hub_favorite_v1_service_proto_rawDesc)))
	})
	return file_wippy_api_hub_favorite_v1_service_proto_rawDescData
}

var file_wippy_api_hub_favorite_v1_service_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_wippy_api_hub_favorite_v1_service_proto_goTypes = []any{
	(*AddFavoriteRequest)(nil),     // 0: wippy.api.hub.favorite.v1.AddFavoriteRequest
	(*AddFavoriteResponse)(nil),    // 1: wippy.api.hub.favorite.v1.AddFavoriteResponse
	(*RemoveFavoriteRequest)(nil),  // 2: wippy.api.hub.favorite.v1.RemoveFavoriteRequest
	(*RemoveFavoriteResponse)(nil), // 3: wippy.api.hub.favorite.v1.RemoveFavoriteResponse
	(*IsFavoritedRequest)(nil),     // 4: wippy.api.hub.favorite.v1.IsFavoritedRequest
	(*IsFavoritedResponse)(nil),    // 5: wippy.api.hub.favorite.v1.IsFavoritedResponse
	(*ListFavoritesRequest)(nil),   // 6: wippy.api.hub.favorite.v1.ListFavoritesRequest
	(*ListFavoritesResponse)(nil),  // 7: wippy.api.hub.favorite.v1.ListFavoritesResponse
	(*v1.ModuleRef)(nil),           // 8: wippy.api.hub.module.v1.ModuleRef
	(*v1.Module)(nil),              // 9: wippy.api.hub.module.v1.Module
}
var file_wippy_api_hub_favorite_v1_service_proto_depIdxs = []int32{
	8, // 0: wippy.api.hub.favorite.v1.AddFavoriteRequest.module:type_name -> wippy.api.hub.module.v1.ModuleRef
	8, // 1: wippy.api.hub.favorite.v1.RemoveFavoriteRequest.module:type_name -> wippy.api.hub.module.v1.ModuleRef
	8, // 2: wippy.api.hub.favorite.v1.IsFavoritedRequest.module:type_name -> wippy.api.hub.module.v1.ModuleRef
	9, // 3: wippy.api.hub.favorite.v1.ListFavoritesResponse.modules:type_name -> wippy.api.hub.module.v1.Module
	0, // 4: wippy.api.hub.favorite.v1.FavoriteService.AddFavorite:input_type -> wippy.api.hub.favorite.v1.AddFavoriteRequest
	2, // 5: wippy.api.hub.favorite.v1.FavoriteService.RemoveFavorite:input_type -> wippy.api.hub.favorite.v1.RemoveFavoriteRequest
	4, // 6: wippy.api.hub.favorite.v1.FavoriteService.IsFavorited:input_type -> wippy.api.hub.favorite.v1.IsFavoritedRequest
	6, // 7: wippy.api.hub.favorite.v1.FavoriteService.ListFavorites:input_type -> wippy.api.hub.favorite.v1.ListFavoritesRequest
	1, // 8: wippy.api.hub.favorite.v1.FavoriteService.AddFavorite:output_type -> wippy.api.hub.favorite.v1.AddFavoriteResponse
	3, // 9: wippy.api.hub.favorite.v1.FavoriteService.RemoveFavorite:output_type -> wippy.api.hub.favorite.v1.RemoveFavoriteResponse
	5, // 10: wippy.api.hub.favorite.v1.FavoriteService.IsFavorited:output_type -> wippy.api.hub.favorite.v1.IsFavoritedResponse
	7, // 11: wippy.api.hub.favorite.v1.FavoriteService.ListFavorites:output_type -> wippy.api.hub.favorite.v1.ListFavoritesResponse
	8, // [8:12] is the sub-list for method output_type
	4, // [4:8] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_wippy_api_hub_favorite_v1_service_proto_init() }
func file_wippy_api_hub_favorite_v1_service_proto_init() {
	if File_wippy_api_hub_favorite_v1_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_wippy_api_hub_favorite_v1_service_proto_rawDesc), len(file_wippy_api_hub_favorite_v1_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_wippy_api_hub_favorite_v1_service_proto_goTypes,
		DependencyIndexes: file_wippy_api_hub_favorite_v1_service_proto_depIdxs,
		MessageInfos:      file_wippy_api_hub_favorite_v1_service_proto_msgTypes,
	}.Build()
	File_wippy_api_hub_favorite_v1_service_proto = out.File
	file_wippy_api_hub_favorite_v1_service_proto_goTypes = nil
	file_wippy_api_hub_favorite_v1_service_proto_depIdxs = nil
}
