// SPDX-License-Identifier: MPL-2.0

// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: wippy/api/hub/publish/v1/service.proto

package publishv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/wippyai/runtime/api/hub/wippy/api/hub/publish/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// PublishServiceName is the fully-qualified name of the PublishService service.
	PublishServiceName = "wippy.api.hub.publish.v1.PublishService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// PublishServiceInitiatePublishProcedure is the fully-qualified name of the PublishService's
	// InitiatePublish RPC.
	PublishServiceInitiatePublishProcedure = "/wippy.api.hub.publish.v1.PublishService/InitiatePublish"
	// PublishServiceConfirmPublishProcedure is the fully-qualified name of the PublishService's
	// ConfirmPublish RPC.
	PublishServiceConfirmPublishProcedure = "/wippy.api.hub.publish.v1.PublishService/ConfirmPublish"
	// PublishServiceGetPublishStatusProcedure is the fully-qualified name of the PublishService's
	// GetPublishStatus RPC.
	PublishServiceGetPublishStatusProcedure = "/wippy.api.hub.publish.v1.PublishService/GetPublishStatus"
	// PublishServiceCancelPublishProcedure is the fully-qualified name of the PublishService's
	// CancelPublish RPC.
	PublishServiceCancelPublishProcedure = "/wippy.api.hub.publish.v1.PublishService/CancelPublish"
	// PublishServiceYankVersionProcedure is the fully-qualified name of the PublishService's
	// YankVersion RPC.
	PublishServiceYankVersionProcedure = "/wippy.api.hub.publish.v1.PublishService/YankVersion"
)

// PublishServiceClient is a client for the wippy.api.hub.publish.v1.PublishService service.
type PublishServiceClient interface {
	InitiatePublish(context.Context, *connect.Request[v1.InitiatePublishRequest]) (*connect.Response[v1.InitiatePublishResponse], error)
	ConfirmPublish(context.Context, *connect.Request[v1.ConfirmPublishRequest]) (*connect.Response[v1.ConfirmPublishResponse], error)
	GetPublishStatus(context.Context, *connect.Request[v1.GetPublishStatusRequest]) (*connect.Response[v1.GetPublishStatusResponse], error)
	CancelPublish(context.Context, *connect.Request[v1.CancelPublishRequest]) (*connect.Response[v1.CancelPublishResponse], error)
	YankVersion(context.Context, *connect.Request[v1.YankVersionRequest]) (*connect.Response[v1.YankVersionResponse], error)
}

// NewPublishServiceClient constructs a client for the wippy.api.hub.publish.v1.PublishService
// service. By default, it uses the Connect protocol with the binary Protobuf Codec, asks for
// gzipped responses, and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply
// the connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewPublishServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) PublishServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	publishServiceMethods := v1.File_wippy_api_hub_publish_v1_service_proto.Services().ByName("PublishService").Methods()
	return &publishServiceClient{
		initiatePublish: connect.NewClient[v1.InitiatePublishRequest, v1.InitiatePublishResponse](
			httpClient,
			baseURL+PublishServiceInitiatePublishProcedure,
			connect.WithSchema(publishServiceMethods.ByName("InitiatePublish")),
			connect.WithClientOptions(opts...),
		),
		confirmPublish: connect.NewClient[v1.ConfirmPublishRequest, v1.ConfirmPublishResponse](
			httpClient,
			baseURL+PublishServiceConfirmPublishProcedure,
			connect.WithSchema(publishServiceMethods.ByName("ConfirmPublish")),
			connect.WithClientOptions(opts...),
		),
		getPublishStatus: connect.NewClient[v1.GetPublishStatusRequest, v1.GetPublishStatusResponse](
			httpClient,
			baseURL+PublishServiceGetPublishStatusProcedure,
			connect.WithSchema(publishServiceMethods.ByName("GetPublishStatus")),
			connect.WithIdempotency(connect.IdempotencyNoSideEffects),
			connect.WithClientOptions(opts...),
		),
		cancelPublish: connect.NewClient[v1.CancelPublishRequest, v1.CancelPublishResponse](
			httpClient,
			baseURL+PublishServiceCancelPublishProcedure,
			connect.WithSchema(publishServiceMethods.ByName("CancelPublish")),
			connect.WithClientOptions(opts...),
		),
		yankVersion: connect.NewClient[v1.YankVersionRequest, v1.YankVersionResponse](
			httpClient,
			baseURL+PublishServiceYankVersionProcedure,
			connect.WithSchema(publishServiceMethods.ByName("YankVersion")),
			connect.WithClientOptions(opts...),
		),
	}
}

// publishServiceClient implements PublishServiceClient.
type publishServiceClient struct {
	initiatePublish  *connect.Client[v1.InitiatePublishRequest, v1.InitiatePublishResponse]
	confirmPublish   *connect.Client[v1.ConfirmPublishRequest, v1.ConfirmPublishResponse]
	getPublishStatus *connect.Client[v1.GetPublishStatusRequest, v1.GetPublishStatusResponse]
	cancelPublish    *connect.Client[v1.CancelPublishRequest, v1.CancelPublishResponse]
	yankVersion      *connect.Client[v1.YankVersionRequest, v1.YankVersionResponse]
}

// InitiatePublish calls wippy.api.hub.publish.v1.PublishService.InitiatePublish.
func (c *publishServiceClient) InitiatePublish(ctx context.Context, req *connect.Request[v1.InitiatePublishRequest]) (*connect.Response[v1.InitiatePublishResponse], error) {
	return c.initiatePublish.CallUnary(ctx, req)
}

// ConfirmPublish calls wippy.api.hub.publish.v1.PublishService.ConfirmPublish.
func (c *publishServiceClient) ConfirmPublish(ctx context.Context, req *connect.Request[v1.ConfirmPublishRequest]) (*connect.Response[v1.ConfirmPublishResponse], error) {
	return c.confirmPublish.CallUnary(ctx, req)
}

// GetPublishStatus calls wippy.api.hub.publish.v1.PublishService.GetPublishStatus.
func (c *publishServiceClient) GetPublishStatus(ctx context.Context, req *connect.Request[v1.GetPublishStatusRequest]) (*connect.Response[v1.GetPublishStatusResponse], error) {
	return c.getPublishStatus.CallUnary(ctx, req)
}

// CancelPublish calls wippy.api.hub.publish.v1.PublishService.CancelPublish.
func (c *publishServiceClient) CancelPublish(ctx context.Context, req *connect.Request[v1.CancelPublishRequest]) (*connect.Response[v1.CancelPublishResponse], error) {
	return c.cancelPublish.CallUnary(ctx, req)
}

// YankVersion calls wippy.api.hub.publish.v1.PublishService.YankVersion.
func (c *publishServiceClient) YankVersion(ctx context.Context, req *connect.Request[v1.YankVersionRequest]) (*connect.Response[v1.YankVersionResponse], error) {
	return c.yankVersion.CallUnary(ctx, req)
}

// PublishServiceHandler is an implementation of the wippy.api.hub.publish.v1.PublishService
// service.
type PublishServiceHandler interface {
	InitiatePublish(context.Context, *connect.Request[v1.InitiatePublishRequest]) (*connect.Response[v1.InitiatePublishResponse], error)
	ConfirmPublish(context.Context, *connect.Request[v1.ConfirmPublishRequest]) (*connect.Response[v1.ConfirmPublishResponse], error)
	GetPublishStatus(context.Context, *connect.Request[v1.GetPublishStatusRequest]) (*connect.Response[v1.GetPublishStatusResponse], error)
	CancelPublish(context.Context, *connect.Request[v1.CancelPublishRequest]) (*connect.Response[v1.CancelPublishResponse], error)
	YankVersion(context.Context, *connect.Request[v1.YankVersionRequest]) (*connect.Response[v1.YankVersionResponse], error)
}

// NewPublishServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewPublishServiceHandler(svc PublishServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	publishServiceMethods := v1.File_wippy_api_hub_publish_v1_service_proto.Services().ByName("PublishService").Methods()
	publishServiceInitiatePublishHandler := connect.NewUnaryHandler(
		PublishServiceInitiatePublishProcedure,
		svc.InitiatePublish,
		connect.WithSchema(publishServiceMethods.ByName("InitiatePublish")),
		connect.WithHandlerOptions(opts...),
	)
	publishServiceConfirmPublishHandler := connect.NewUnaryHandler(
		PublishServiceConfirmPublishProcedure,
		svc.ConfirmPublish,
		connect.WithSchema(publishServiceMethods.ByName("ConfirmPublish")),
		connect.WithHandlerOptions(opts...),
	)
	publishServiceGetPublishStatusHandler := connect.NewUnaryHandler(
		PublishServiceGetPublishStatusProcedure,
		svc.GetPublishStatus,
		connect.WithSchema(publishServiceMethods.ByName("GetPublishStatus")),
		connect.WithIdempotency(connect.IdempotencyNoSideEffects),
		connect.WithHandlerOptions(opts...),
	)
	publishServiceCancelPublishHandler := connect.NewUnaryHandler(
		PublishServiceCancelPublishProcedure,
		svc.CancelPublish,
		connect.WithSchema(publishServiceMethods.ByName("CancelPublish")),
		connect.WithHandlerOptions(opts...),
	)
	publishServiceYankVersionHandler := connect.NewUnaryHandler(
		PublishServiceYankVersionProcedure,
		svc.YankVersion,
		connect.WithSchema(publishServiceMethods.ByName("YankVersion")),
		connect.WithHandlerOptions(opts...),
	)
	return "/wippy.api.hub.publish.v1.PublishService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case PublishServiceInitiatePublishProcedure:
			publishServiceInitiatePublishHandler.ServeHTTP(w, r)
		case PublishServiceConfirmPublishProcedure:
			publishServiceConfirmPublishHandler.ServeHTTP(w, r)
		case PublishServiceGetPublishStatusProcedure:
			publishServiceGetPublishStatusHandler.ServeHTTP(w, r)
		case PublishServiceCancelPublishProcedure:
			publishServiceCancelPublishHandler.ServeHTTP(w, r)
		case PublishServiceYankVersionProcedure:
			publishServiceYankVersionHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedPublishServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedPublishServiceHandler struct{}

func (UnimplementedPublishServiceHandler) InitiatePublish(context.Context, *connect.Request[v1.InitiatePublishRequest]) (*connect.Response[v1.InitiatePublishResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("wippy.api.hub.publish.v1.PublishService.InitiatePublish is not implemented"))
}

func (UnimplementedPublishServiceHandler) ConfirmPublish(context.Context, *connect.Request[v1.ConfirmPublishRequest]) (*connect.Response[v1.ConfirmPublishResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("wippy.api.hub.publish.v1.PublishService.ConfirmPublish is not implemented"))
}

func (UnimplementedPublishServiceHandler) GetPublishStatus(context.Context, *connect.Request[v1.GetPublishStatusRequest]) (*connect.Response[v1.GetPublishStatusResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("wippy.api.hub.publish.v1.PublishService.GetPublishStatus is not implemented"))
}

func (UnimplementedPublishServiceHandler) CancelPublish(context.Context, *connect.Request[v1.CancelPublishRequest]) (*connect.Response[v1.CancelPublishResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("wippy.api.hub.publish.v1.PublishService.CancelPublish is not implemented"))
}

func (UnimplementedPublishServiceHandler) YankVersion(context.Context, *connect.Request[v1.YankVersionRequest]) (*connect.Response[v1.YankVersionResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("wippy.api.hub.publish.v1.PublishService.YankVersion is not implemented"))
}
