apiVersion: wippy.http/v1
kind: Endpoint
metadata:
  name: time-endpoint
  labels:
    component: http
    type: http
config:
  id: http.endpoint.default.http_time
  path: /time
  method: GET
  handler: runtime.function.http_time