// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/ponyruntime/pony/moduleloader (interfaces: ManifestLoader)
//
// Generated by this command:
//
//	mockgen -destination tests/mock/moduleloader/moduleloader.go github.com/ponyruntime/pony/moduleloader ManifestLoader
//

// Package mock_moduleloader is a generated GoMock package.
package mock_moduleloader

import (
	context "context"
	reflect "reflect"

	moduleloader "github.com/ponyruntime/pony/moduleloader"
	gomock "go.uber.org/mock/gomock"
)

// MockManifestLoader is a mock of ManifestLoader interface.
type MockManifestLoader struct {
	ctrl     *gomock.Controller
	recorder *MockManifestLoaderMockRecorder
	isgomock struct{}
}

// MockManifestLoaderMockRecorder is the mock recorder for MockManifestLoader.
type MockManifestLoaderMockRecorder struct {
	mock *MockManifestLoader
}

// NewMockManifestLoader creates a new mock instance.
func NewMockManifestLoader(ctrl *gomock.Controller) *MockManifestLoader {
	mock := &MockManifestLoader{ctrl: ctrl}
	mock.recorder = &MockManifestLoaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockManifestLoader) EXPECT() *MockManifestLoaderMockRecorder {
	return m.recorder
}

// LoadManifest mocks base method.
func (m *MockManifestLoader) LoadManifest(ctx context.Context) (*moduleloader.Manifest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LoadManifest", ctx)
	ret0, _ := ret[0].(*moduleloader.Manifest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LoadManifest indicates an expected call of LoadManifest.
func (mr *MockManifestLoaderMockRecorder) LoadManifest(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoadManifest", reflect.TypeOf((*MockManifestLoader)(nil).LoadManifest), ctx)
}
