// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/wippyai/module-registry-proto-go/registry/module/v1/modulev1connect (interfaces: ModuleServiceClient,CommitServiceClient,LabelServiceClient,DownloadServiceClient)
//
// Generated by this command:
//
//	mockgen -destination tests/mock/modulev1connect/modulev1connect.go github.com/wippyai/module-registry-proto-go/registry/module/v1/modulev1connect ModuleServiceClient,CommitServiceClient,LabelServiceClient,DownloadServiceClient
//

// Package mock_modulev1connect is a generated GoMock package.
package mock_modulev1connect

import (
	context "context"
	reflect "reflect"

	connect "connectrpc.com/connect"
	modulev1 "github.com/wippyai/module-registry-proto-go/registry/module/v1"
	gomock "go.uber.org/mock/gomock"
)

// MockModuleServiceClient is a mock of ModuleServiceClient interface.
type MockModuleServiceClient struct {
	ctrl     *gomock.Controller
	recorder *MockModuleServiceClientMockRecorder
	isgomock struct{}
}

// MockModuleServiceClientMockRecorder is the mock recorder for MockModuleServiceClient.
type MockModuleServiceClientMockRecorder struct {
	mock *MockModuleServiceClient
}

// NewMockModuleServiceClient creates a new mock instance.
func NewMockModuleServiceClient(ctrl *gomock.Controller) *MockModuleServiceClient {
	mock := &MockModuleServiceClient{ctrl: ctrl}
	mock.recorder = &MockModuleServiceClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockModuleServiceClient) EXPECT() *MockModuleServiceClientMockRecorder {
	return m.recorder
}

// CreateModule mocks base method.
func (m *MockModuleServiceClient) CreateModule(arg0 context.Context, arg1 *connect.Request[modulev1.CreateModuleRequest]) (*connect.Response[modulev1.CreateModuleResponse], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateModule", arg0, arg1)
	ret0, _ := ret[0].(*connect.Response[modulev1.CreateModuleResponse])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateModule indicates an expected call of CreateModule.
func (mr *MockModuleServiceClientMockRecorder) CreateModule(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateModule", reflect.TypeOf((*MockModuleServiceClient)(nil).CreateModule), arg0, arg1)
}

// ListModules mocks base method.
func (m *MockModuleServiceClient) ListModules(arg0 context.Context, arg1 *connect.Request[modulev1.ListModulesRequest]) (*connect.Response[modulev1.ListModulesResponse], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListModules", arg0, arg1)
	ret0, _ := ret[0].(*connect.Response[modulev1.ListModulesResponse])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListModules indicates an expected call of ListModules.
func (mr *MockModuleServiceClientMockRecorder) ListModules(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListModules", reflect.TypeOf((*MockModuleServiceClient)(nil).ListModules), arg0, arg1)
}

// ListOrganizationModules mocks base method.
func (m *MockModuleServiceClient) ListOrganizationModules(arg0 context.Context, arg1 *connect.Request[modulev1.ListOrganizationModulesRequest]) (*connect.Response[modulev1.ListOrganizationModulesResponse], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListOrganizationModules", arg0, arg1)
	ret0, _ := ret[0].(*connect.Response[modulev1.ListOrganizationModulesResponse])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListOrganizationModules indicates an expected call of ListOrganizationModules.
func (mr *MockModuleServiceClientMockRecorder) ListOrganizationModules(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListOrganizationModules", reflect.TypeOf((*MockModuleServiceClient)(nil).ListOrganizationModules), arg0, arg1)
}

// MockCommitServiceClient is a mock of CommitServiceClient interface.
type MockCommitServiceClient struct {
	ctrl     *gomock.Controller
	recorder *MockCommitServiceClientMockRecorder
	isgomock struct{}
}

// MockCommitServiceClientMockRecorder is the mock recorder for MockCommitServiceClient.
type MockCommitServiceClientMockRecorder struct {
	mock *MockCommitServiceClient
}

// NewMockCommitServiceClient creates a new mock instance.
func NewMockCommitServiceClient(ctrl *gomock.Controller) *MockCommitServiceClient {
	mock := &MockCommitServiceClient{ctrl: ctrl}
	mock.recorder = &MockCommitServiceClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCommitServiceClient) EXPECT() *MockCommitServiceClientMockRecorder {
	return m.recorder
}

// ListCommits mocks base method.
func (m *MockCommitServiceClient) ListCommits(arg0 context.Context, arg1 *connect.Request[modulev1.ListCommitsRequest]) (*connect.Response[modulev1.ListCommitsResponse], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListCommits", arg0, arg1)
	ret0, _ := ret[0].(*connect.Response[modulev1.ListCommitsResponse])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListCommits indicates an expected call of ListCommits.
func (mr *MockCommitServiceClientMockRecorder) ListCommits(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListCommits", reflect.TypeOf((*MockCommitServiceClient)(nil).ListCommits), arg0, arg1)
}

// ListModuleCommits mocks base method.
func (m *MockCommitServiceClient) ListModuleCommits(arg0 context.Context, arg1 *connect.Request[modulev1.ListModuleCommitsRequest]) (*connect.Response[modulev1.ListModuleCommitsResponse], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListModuleCommits", arg0, arg1)
	ret0, _ := ret[0].(*connect.Response[modulev1.ListModuleCommitsResponse])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListModuleCommits indicates an expected call of ListModuleCommits.
func (mr *MockCommitServiceClientMockRecorder) ListModuleCommits(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListModuleCommits", reflect.TypeOf((*MockCommitServiceClient)(nil).ListModuleCommits), arg0, arg1)
}

// MockLabelServiceClient is a mock of LabelServiceClient interface.
type MockLabelServiceClient struct {
	ctrl     *gomock.Controller
	recorder *MockLabelServiceClientMockRecorder
	isgomock struct{}
}

// MockLabelServiceClientMockRecorder is the mock recorder for MockLabelServiceClient.
type MockLabelServiceClientMockRecorder struct {
	mock *MockLabelServiceClient
}

// NewMockLabelServiceClient creates a new mock instance.
func NewMockLabelServiceClient(ctrl *gomock.Controller) *MockLabelServiceClient {
	mock := &MockLabelServiceClient{ctrl: ctrl}
	mock.recorder = &MockLabelServiceClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLabelServiceClient) EXPECT() *MockLabelServiceClientMockRecorder {
	return m.recorder
}

// CreateLabel mocks base method.
func (m *MockLabelServiceClient) CreateLabel(arg0 context.Context, arg1 *connect.Request[modulev1.CreateLabelRequest]) (*connect.Response[modulev1.CreateLabelResponse], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateLabel", arg0, arg1)
	ret0, _ := ret[0].(*connect.Response[modulev1.CreateLabelResponse])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateLabel indicates an expected call of CreateLabel.
func (mr *MockLabelServiceClientMockRecorder) CreateLabel(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateLabel", reflect.TypeOf((*MockLabelServiceClient)(nil).CreateLabel), arg0, arg1)
}

// ListModuleLabels mocks base method.
func (m *MockLabelServiceClient) ListModuleLabels(arg0 context.Context, arg1 *connect.Request[modulev1.ListModuleLabelsRequest]) (*connect.Response[modulev1.ListModuleLabelsResponse], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListModuleLabels", arg0, arg1)
	ret0, _ := ret[0].(*connect.Response[modulev1.ListModuleLabelsResponse])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListModuleLabels indicates an expected call of ListModuleLabels.
func (mr *MockLabelServiceClientMockRecorder) ListModuleLabels(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListModuleLabels", reflect.TypeOf((*MockLabelServiceClient)(nil).ListModuleLabels), arg0, arg1)
}

// MockDownloadServiceClient is a mock of DownloadServiceClient interface.
type MockDownloadServiceClient struct {
	ctrl     *gomock.Controller
	recorder *MockDownloadServiceClientMockRecorder
	isgomock struct{}
}

// MockDownloadServiceClientMockRecorder is the mock recorder for MockDownloadServiceClient.
type MockDownloadServiceClientMockRecorder struct {
	mock *MockDownloadServiceClient
}

// NewMockDownloadServiceClient creates a new mock instance.
func NewMockDownloadServiceClient(ctrl *gomock.Controller) *MockDownloadServiceClient {
	mock := &MockDownloadServiceClient{ctrl: ctrl}
	mock.recorder = &MockDownloadServiceClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDownloadServiceClient) EXPECT() *MockDownloadServiceClientMockRecorder {
	return m.recorder
}

// Download mocks base method.
func (m *MockDownloadServiceClient) Download(arg0 context.Context, arg1 *connect.Request[modulev1.DownloadRequest]) (*connect.Response[modulev1.DownloadResponse], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Download", arg0, arg1)
	ret0, _ := ret[0].(*connect.Response[modulev1.DownloadResponse])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Download indicates an expected call of Download.
func (mr *MockDownloadServiceClientMockRecorder) Download(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Download", reflect.TypeOf((*MockDownloadServiceClient)(nil).Download), arg0, arg1)
}
