package stream

import (
	"bufio"
	"fmt"
)

// SplitType represents the type of splitting to use for scanning
type SplitType string

const (
	SplitLines SplitType = "lines"
	SplitWords SplitType = "words"
	SplitBytes SplitType = "bytes"
	SplitRunes SplitType = "runes"
)

// Scanner provides line-by-line or token-based reading from a Stream using bufio.Scanner.
// It mirrors Go's bufio.Scanner interface for consistency.
type Scanner struct {
	scanner   *bufio.Scanner
	stream    *Stream
	splitType SplitType
}

// NewScanner creates a new Scanner that reads from the provided Stream.
// The Scanner uses the Stream as an io.Reader, so it will respect the
// Stream's context and error handling.
// Default split type is lines if not specified.
func NewScanner(stream *Stream, splitType ...SplitType) (*Scanner, error) {
	if stream == nil {
		return nil, fmt.Errorf("stream cannot be nil")
	}

	split := SplitLines
	if len(splitType) > 0 {
		split = splitType[0]
	}

	scanner := &Scanner{
		scanner:   bufio.NewScanner(stream),
		stream:    stream,
		splitType: split,
	}

	// Configure the split function based on type
	switch split {
	case SplitLines:
		scanner.scanner.Split(bufio.ScanLines)
	case SplitWords:
		scanner.scanner.Split(bufio.ScanWords)
	case SplitBytes:
		scanner.scanner.Split(bufio.ScanBytes)
	case SplitRunes:
		scanner.scanner.Split(bufio.ScanRunes)
	default:
		return nil, fmt.Errorf("unsupported split type: %s", split)
	}

	return scanner, nil
}

// Scan advances the Scanner to the next token, which will then be
// available through the Text method. It returns false when the scan
// stops, either by reaching the end of the input or an error.
// After Scan returns false, the Err method will return any error
// that occurred during scanning, except that if it was io.EOF, Err
// will return nil.
func (s *Scanner) Scan() bool {
	return s.scanner.Scan()
}

// Text returns the most recent token generated by a call to Scan.
// The underlying array may point to data that will be overwritten
// by a subsequent call to Scan. It does no allocation.
func (s *Scanner) Text() string {
	return s.scanner.Text()
}

// Err returns the first non-EOF error that was encountered by the Scanner.
func (s *Scanner) Err() error {
	return s.scanner.Err()
}

// SplitType returns the split type used by this scanner
func (s *Scanner) SplitType() SplitType {
	return s.splitType
}
