apiVersion: wippy.runtime/v1
kind: Function
metadata:
  name: http-time-handler
  labels:
    component: runtime
    type: lua
config:
  id: runtime.function.http_time
  runtime: lua
  method: main
  source: file://src/http_time.lua
  extensions:
    - http
    - json