// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: wippy/api/hub/version/v1/message.proto

package versionv1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ProtectionType int32

const (
	ProtectionType_PROTECTION_TYPE_UNSPECIFIED ProtectionType = 0
	ProtectionType_PROTECTION_TYPE_NONE        ProtectionType = 1
	ProtectionType_PROTECTION_TYPE_BYTECODE    ProtectionType = 2
	ProtectionType_PROTECTION_TYPE_ENCRYPTED   ProtectionType = 3
)

// Enum value maps for ProtectionType.
var (
	ProtectionType_name = map[int32]string{
		0: "PROTECTION_TYPE_UNSPECIFIED",
		1: "PROTECTION_TYPE_NONE",
		2: "PROTECTION_TYPE_BYTECODE",
		3: "PROTECTION_TYPE_ENCRYPTED",
	}
	ProtectionType_value = map[string]int32{
		"PROTECTION_TYPE_UNSPECIFIED": 0,
		"PROTECTION_TYPE_NONE":        1,
		"PROTECTION_TYPE_BYTECODE":    2,
		"PROTECTION_TYPE_ENCRYPTED":   3,
	}
)

func (x ProtectionType) Enum() *ProtectionType {
	p := new(ProtectionType)
	*p = x
	return p
}

func (x ProtectionType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ProtectionType) Descriptor() protoreflect.EnumDescriptor {
	return file_wippy_api_hub_version_v1_message_proto_enumTypes[0].Descriptor()
}

func (ProtectionType) Type() protoreflect.EnumType {
	return &file_wippy_api_hub_version_v1_message_proto_enumTypes[0]
}

func (x ProtectionType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ProtectionType.Descriptor instead.
func (ProtectionType) EnumDescriptor() ([]byte, []int) {
	return file_wippy_api_hub_version_v1_message_proto_rawDescGZIP(), []int{0}
}

// Version reference.
type VersionRef struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Value:
	//
	//	*VersionRef_Id
	//	*VersionRef_Version
	//	*VersionRef_Label
	Value         isVersionRef_Value `protobuf_oneof:"value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VersionRef) Reset() {
	*x = VersionRef{}
	mi := &file_wippy_api_hub_version_v1_message_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VersionRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VersionRef) ProtoMessage() {}

func (x *VersionRef) ProtoReflect() protoreflect.Message {
	mi := &file_wippy_api_hub_version_v1_message_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VersionRef.ProtoReflect.Descriptor instead.
func (*VersionRef) Descriptor() ([]byte, []int) {
	return file_wippy_api_hub_version_v1_message_proto_rawDescGZIP(), []int{0}
}

func (x *VersionRef) GetValue() isVersionRef_Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *VersionRef) GetId() string {
	if x != nil {
		if x, ok := x.Value.(*VersionRef_Id); ok {
			return x.Id
		}
	}
	return ""
}

func (x *VersionRef) GetVersion() string {
	if x != nil {
		if x, ok := x.Value.(*VersionRef_Version); ok {
			return x.Version
		}
	}
	return ""
}

func (x *VersionRef) GetLabel() string {
	if x != nil {
		if x, ok := x.Value.(*VersionRef_Label); ok {
			return x.Label
		}
	}
	return ""
}

type isVersionRef_Value interface {
	isVersionRef_Value()
}

type VersionRef_Id struct {
	Id string `protobuf:"bytes,1,opt,name=id,proto3,oneof"`
}

type VersionRef_Version struct {
	Version string `protobuf:"bytes,2,opt,name=version,proto3,oneof"`
}

type VersionRef_Label struct {
	Label string `protobuf:"bytes,3,opt,name=label,proto3,oneof"`
}

func (*VersionRef_Id) isVersionRef_Value() {}

func (*VersionRef_Version) isVersionRef_Value() {}

func (*VersionRef_Label) isVersionRef_Value() {}

// A version of a module.
type Version struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ModuleId       string                 `protobuf:"bytes,2,opt,name=module_id,json=moduleId,proto3" json:"module_id,omitempty"`
	Version        string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	Digest         string                 `protobuf:"bytes,4,opt,name=digest,proto3" json:"digest,omitempty"`
	SizeBytes      uint64                 `protobuf:"varint,5,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	Yanked         bool                   `protobuf:"varint,6,opt,name=yanked,proto3" json:"yanked,omitempty"`
	PublishedBy    string                 `protobuf:"bytes,7,opt,name=published_by,json=publishedBy,proto3" json:"published_by,omitempty"`
	CreateTime     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	Metadata       *VersionMetadata       `protobuf:"bytes,9,opt,name=metadata,proto3" json:"metadata,omitempty"`
	DownloadCount  uint64                 `protobuf:"varint,10,opt,name=download_count,json=downloadCount,proto3" json:"download_count,omitempty"`
	Protected      bool                   `protobuf:"varint,11,opt,name=protected,proto3" json:"protected,omitempty"`
	ProtectionType ProtectionType         `protobuf:"varint,12,opt,name=protection_type,json=protectionType,proto3,enum=wippy.api.hub.version.v1.ProtectionType" json:"protection_type,omitempty"`
	LuaModules     []string               `protobuf:"bytes,13,rep,name=lua_modules,json=luaModules,proto3" json:"lua_modules,omitempty"`
	EntryKinds     []string               `protobuf:"bytes,14,rep,name=entry_kinds,json=entryKinds,proto3" json:"entry_kinds,omitempty"`
	EntryCount     uint32                 `protobuf:"varint,15,opt,name=entry_count,json=entryCount,proto3" json:"entry_count,omitempty"`
	Dependencies   []*Dependency          `protobuf:"bytes,16,rep,name=dependencies,proto3" json:"dependencies,omitempty"`
	Requirements   []*Requirement         `protobuf:"bytes,17,rep,name=requirements,proto3" json:"requirements,omitempty"`
	Files          []*VersionFile         `protobuf:"bytes,18,rep,name=files,proto3" json:"files,omitempty"`
	Readme         string                 `protobuf:"bytes,19,opt,name=readme,proto3" json:"readme,omitempty"`
	ReleaseNotes   string                 `protobuf:"bytes,20,opt,name=release_notes,json=releaseNotes,proto3" json:"release_notes,omitempty"`
	Source         string                 `protobuf:"bytes,21,opt,name=source,proto3" json:"source,omitempty"`
	SourceLabel    string                 `protobuf:"bytes,22,opt,name=source_label,json=sourceLabel,proto3" json:"source_label,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Version) Reset() {
	*x = Version{}
	mi := &file_wippy_api_hub_version_v1_message_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Version) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Version) ProtoMessage() {}

func (x *Version) ProtoReflect() protoreflect.Message {
	mi := &file_wippy_api_hub_version_v1_message_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Version.ProtoReflect.Descriptor instead.
func (*Version) Descriptor() ([]byte, []int) {
	return file_wippy_api_hub_version_v1_message_proto_rawDescGZIP(), []int{1}
}

func (x *Version) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Version) GetModuleId() string {
	if x != nil {
		return x.ModuleId
	}
	return ""
}

func (x *Version) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *Version) GetDigest() string {
	if x != nil {
		return x.Digest
	}
	return ""
}

func (x *Version) GetSizeBytes() uint64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

func (x *Version) GetYanked() bool {
	if x != nil {
		return x.Yanked
	}
	return false
}

func (x *Version) GetPublishedBy() string {
	if x != nil {
		return x.PublishedBy
	}
	return ""
}

func (x *Version) GetCreateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CreateTime
	}
	return nil
}

func (x *Version) GetMetadata() *VersionMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *Version) GetDownloadCount() uint64 {
	if x != nil {
		return x.DownloadCount
	}
	return 0
}

func (x *Version) GetProtected() bool {
	if x != nil {
		return x.Protected
	}
	return false
}

func (x *Version) GetProtectionType() ProtectionType {
	if x != nil {
		return x.ProtectionType
	}
	return ProtectionType_PROTECTION_TYPE_UNSPECIFIED
}

func (x *Version) GetLuaModules() []string {
	if x != nil {
		return x.LuaModules
	}
	return nil
}

func (x *Version) GetEntryKinds() []string {
	if x != nil {
		return x.EntryKinds
	}
	return nil
}

func (x *Version) GetEntryCount() uint32 {
	if x != nil {
		return x.EntryCount
	}
	return 0
}

func (x *Version) GetDependencies() []*Dependency {
	if x != nil {
		return x.Dependencies
	}
	return nil
}

func (x *Version) GetRequirements() []*Requirement {
	if x != nil {
		return x.Requirements
	}
	return nil
}

func (x *Version) GetFiles() []*VersionFile {
	if x != nil {
		return x.Files
	}
	return nil
}

func (x *Version) GetReadme() string {
	if x != nil {
		return x.Readme
	}
	return ""
}

func (x *Version) GetReleaseNotes() string {
	if x != nil {
		return x.ReleaseNotes
	}
	return ""
}

func (x *Version) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *Version) GetSourceLabel() string {
	if x != nil {
		return x.SourceLabel
	}
	return ""
}

// Metadata from module manifest.
type VersionMetadata struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Description     string                 `protobuf:"bytes,1,opt,name=description,proto3" json:"description,omitempty"`
	Repository      string                 `protobuf:"bytes,2,opt,name=repository,proto3" json:"repository,omitempty"`
	License         string                 `protobuf:"bytes,3,opt,name=license,proto3" json:"license,omitempty"`
	Keywords        []string               `protobuf:"bytes,4,rep,name=keywords,proto3" json:"keywords,omitempty"`
	Authors         []string               `protobuf:"bytes,5,rep,name=authors,proto3" json:"authors,omitempty"`
	Documentation   string                 `protobuf:"bytes,6,opt,name=documentation,proto3" json:"documentation,omitempty"`
	Homepage        string                 `protobuf:"bytes,7,opt,name=homepage,proto3" json:"homepage,omitempty"`
	MinWippyVersion string                 `protobuf:"bytes,8,opt,name=min_wippy_version,json=minWippyVersion,proto3" json:"min_wippy_version,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *VersionMetadata) Reset() {
	*x = VersionMetadata{}
	mi := &file_wippy_api_hub_version_v1_message_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VersionMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VersionMetadata) ProtoMessage() {}

func (x *VersionMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_wippy_api_hub_version_v1_message_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VersionMetadata.ProtoReflect.Descriptor instead.
func (*VersionMetadata) Descriptor() ([]byte, []int) {
	return file_wippy_api_hub_version_v1_message_proto_rawDescGZIP(), []int{2}
}

func (x *VersionMetadata) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *VersionMetadata) GetRepository() string {
	if x != nil {
		return x.Repository
	}
	return ""
}

func (x *VersionMetadata) GetLicense() string {
	if x != nil {
		return x.License
	}
	return ""
}

func (x *VersionMetadata) GetKeywords() []string {
	if x != nil {
		return x.Keywords
	}
	return nil
}

func (x *VersionMetadata) GetAuthors() []string {
	if x != nil {
		return x.Authors
	}
	return nil
}

func (x *VersionMetadata) GetDocumentation() string {
	if x != nil {
		return x.Documentation
	}
	return ""
}

func (x *VersionMetadata) GetHomepage() string {
	if x != nil {
		return x.Homepage
	}
	return ""
}

func (x *VersionMetadata) GetMinWippyVersion() string {
	if x != nil {
		return x.MinWippyVersion
	}
	return ""
}

// Dependency declaration.
type Dependency struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Org               string                 `protobuf:"bytes,1,opt,name=org,proto3" json:"org,omitempty"`
	Name              string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	VersionConstraint string                 `protobuf:"bytes,3,opt,name=version_constraint,json=versionConstraint,proto3" json:"version_constraint,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Dependency) Reset() {
	*x = Dependency{}
	mi := &file_wippy_api_hub_version_v1_message_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Dependency) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Dependency) ProtoMessage() {}

func (x *Dependency) ProtoReflect() protoreflect.Message {
	mi := &file_wippy_api_hub_version_v1_message_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Dependency.ProtoReflect.Descriptor instead.
func (*Dependency) Descriptor() ([]byte, []int) {
	return file_wippy_api_hub_version_v1_message_proto_rawDescGZIP(), []int{3}
}

func (x *Dependency) GetOrg() string {
	if x != nil {
		return x.Org
	}
	return ""
}

func (x *Dependency) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Dependency) GetVersionConstraint() string {
	if x != nil {
		return x.VersionConstraint
	}
	return ""
}

// File in a version.
type VersionFile struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	SizeBytes     uint64                 `protobuf:"varint,2,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VersionFile) Reset() {
	*x = VersionFile{}
	mi := &file_wippy_api_hub_version_v1_message_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VersionFile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VersionFile) ProtoMessage() {}

func (x *VersionFile) ProtoReflect() protoreflect.Message {
	mi := &file_wippy_api_hub_version_v1_message_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VersionFile.ProtoReflect.Descriptor instead.
func (*VersionFile) Descriptor() ([]byte, []int) {
	return file_wippy_api_hub_version_v1_message_proto_rawDescGZIP(), []int{4}
}

func (x *VersionFile) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *VersionFile) GetSizeBytes() uint64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

// Label pointing to a version.
type Label struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	VersionId     string                 `protobuf:"bytes,2,opt,name=version_id,json=versionId,proto3" json:"version_id,omitempty"`
	UpdateTime    *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty"`
	ReleaseNotes  string                 `protobuf:"bytes,4,opt,name=release_notes,json=releaseNotes,proto3" json:"release_notes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Label) Reset() {
	*x = Label{}
	mi := &file_wippy_api_hub_version_v1_message_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Label) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Label) ProtoMessage() {}

func (x *Label) ProtoReflect() protoreflect.Message {
	mi := &file_wippy_api_hub_version_v1_message_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Label.ProtoReflect.Descriptor instead.
func (*Label) Descriptor() ([]byte, []int) {
	return file_wippy_api_hub_version_v1_message_proto_rawDescGZIP(), []int{5}
}

func (x *Label) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Label) GetVersionId() string {
	if x != nil {
		return x.VersionId
	}
	return ""
}

func (x *Label) GetUpdateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdateTime
	}
	return nil
}

func (x *Label) GetReleaseNotes() string {
	if x != nil {
		return x.ReleaseNotes
	}
	return ""
}

// Configuration requirement.
type Requirement struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Targets       []*RequirementTarget   `protobuf:"bytes,3,rep,name=targets,proto3" json:"targets,omitempty"`
	Default       string                 `protobuf:"bytes,4,opt,name=default,proto3" json:"default,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Requirement) Reset() {
	*x = Requirement{}
	mi := &file_wippy_api_hub_version_v1_message_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Requirement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Requirement) ProtoMessage() {}

func (x *Requirement) ProtoReflect() protoreflect.Message {
	mi := &file_wippy_api_hub_version_v1_message_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Requirement.ProtoReflect.Descriptor instead.
func (*Requirement) Descriptor() ([]byte, []int) {
	return file_wippy_api_hub_version_v1_message_proto_rawDescGZIP(), []int{6}
}

func (x *Requirement) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Requirement) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Requirement) GetTargets() []*RequirementTarget {
	if x != nil {
		return x.Targets
	}
	return nil
}

func (x *Requirement) GetDefault() string {
	if x != nil {
		return x.Default
	}
	return ""
}

// Requirement target.
type RequirementTarget struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entry         string                 `protobuf:"bytes,1,opt,name=entry,proto3" json:"entry,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequirementTarget) Reset() {
	*x = RequirementTarget{}
	mi := &file_wippy_api_hub_version_v1_message_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequirementTarget) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequirementTarget) ProtoMessage() {}

func (x *RequirementTarget) ProtoReflect() protoreflect.Message {
	mi := &file_wippy_api_hub_version_v1_message_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequirementTarget.ProtoReflect.Descriptor instead.
func (*RequirementTarget) Descriptor() ([]byte, []int) {
	return file_wippy_api_hub_version_v1_message_proto_rawDescGZIP(), []int{7}
}

func (x *RequirementTarget) GetEntry() string {
	if x != nil {
		return x.Entry
	}
	return ""
}

func (x *RequirementTarget) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

var File_wippy_api_hub_version_v1_message_proto protoreflect.FileDescriptor

const file_wippy_api_hub_version_v1_message_proto_rawDesc = "" +
	"\n" +
	"&wippy/api/hub/version/v1/message.proto\x12\x18wippy.api.hub.version.v1\x1a\x1bbuf/validate/validate.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"w\n" +
	"\n" +
	"VersionRef\x12\x1a\n" +
	"\x02id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01H\x00R\x02id\x12#\n" +
	"\aversion\x18\x02 \x01(\tB\a\xbaH\x04r\x02\x18@H\x00R\aversion\x12\x1f\n" +
	"\x05label\x18\x03 \x01(\tB\a\xbaH\x04r\x02\x18 H\x00R\x05labelB\a\n" +
	"\x05value\"\xaa\a\n" +
	"\aVersion\x12\x18\n" +
	"\x02id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\x02id\x12%\n" +
	"\tmodule_id\x18\x02 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\bmoduleId\x12#\n" +
	"\aversion\x18\x03 \x01(\tB\t\xbaH\x06r\x04\x10\x01\x18@R\aversion\x12\x16\n" +
	"\x06digest\x18\x04 \x01(\tR\x06digest\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\x05 \x01(\x04R\tsizeBytes\x12\x16\n" +
	"\x06yanked\x18\x06 \x01(\bR\x06yanked\x12!\n" +
	"\fpublished_by\x18\a \x01(\tR\vpublishedBy\x12;\n" +
	"\vcreate_time\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"createTime\x12E\n" +
	"\bmetadata\x18\t \x01(\v2).wippy.api.hub.version.v1.VersionMetadataR\bmetadata\x12%\n" +
	"\x0edownload_count\x18\n" +
	" \x01(\x04R\rdownloadCount\x12\x1c\n" +
	"\tprotected\x18\v \x01(\bR\tprotected\x12Q\n" +
	"\x0fprotection_type\x18\f \x01(\x0e2(.wippy.api.hub.version.v1.ProtectionTypeR\x0eprotectionType\x12\x1f\n" +
	"\vlua_modules\x18\r \x03(\tR\n" +
	"luaModules\x12\x1f\n" +
	"\ventry_kinds\x18\x0e \x03(\tR\n" +
	"entryKinds\x12\x1f\n" +
	"\ventry_count\x18\x0f \x01(\rR\n" +
	"entryCount\x12H\n" +
	"\fdependencies\x18\x10 \x03(\v2$.wippy.api.hub.version.v1.DependencyR\fdependencies\x12I\n" +
	"\frequirements\x18\x11 \x03(\v2%.wippy.api.hub.version.v1.RequirementR\frequirements\x12;\n" +
	"\x05files\x18\x12 \x03(\v2%.wippy.api.hub.version.v1.VersionFileR\x05files\x12\x16\n" +
	"\x06readme\x18\x13 \x01(\tR\x06readme\x12#\n" +
	"\rrelease_notes\x18\x14 \x01(\tR\freleaseNotes\x12\x16\n" +
	"\x06source\x18\x15 \x01(\tR\x06source\x12!\n" +
	"\fsource_label\x18\x16 \x01(\tR\vsourceLabel\"\x91\x02\n" +
	"\x0fVersionMetadata\x12 \n" +
	"\vdescription\x18\x01 \x01(\tR\vdescription\x12\x1e\n" +
	"\n" +
	"repository\x18\x02 \x01(\tR\n" +
	"repository\x12\x18\n" +
	"\alicense\x18\x03 \x01(\tR\alicense\x12\x1a\n" +
	"\bkeywords\x18\x04 \x03(\tR\bkeywords\x12\x18\n" +
	"\aauthors\x18\x05 \x03(\tR\aauthors\x12$\n" +
	"\rdocumentation\x18\x06 \x01(\tR\rdocumentation\x12\x1a\n" +
	"\bhomepage\x18\a \x01(\tR\bhomepage\x12*\n" +
	"\x11min_wippy_version\x18\b \x01(\tR\x0fminWippyVersion\"w\n" +
	"\n" +
	"Dependency\x12\x1b\n" +
	"\x03org\x18\x01 \x01(\tB\t\xbaH\x06r\x04\x10\x01\x18@R\x03org\x12\x1d\n" +
	"\x04name\x18\x02 \x01(\tB\t\xbaH\x06r\x04\x10\x01\x18@R\x04name\x12-\n" +
	"\x12version_constraint\x18\x03 \x01(\tR\x11versionConstraint\"@\n" +
	"\vVersionFile\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\x02 \x01(\x04R\tsizeBytes\"\xc4\x01\n" +
	"\x05Label\x120\n" +
	"\x04name\x18\x01 \x01(\tB\x1c\xbaH\x19r\x17\x10\x01\x18 2\x11^[a-z][a-z0-9-]*$R\x04name\x12'\n" +
	"\n" +
	"version_id\x18\x02 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\tversionId\x12;\n" +
	"\vupdate_time\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"updateTime\x12#\n" +
	"\rrelease_notes\x18\x04 \x01(\tR\freleaseNotes\"\xa4\x01\n" +
	"\vRequirement\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12E\n" +
	"\atargets\x18\x03 \x03(\v2+.wippy.api.hub.version.v1.RequirementTargetR\atargets\x12\x18\n" +
	"\adefault\x18\x04 \x01(\tR\adefault\"=\n" +
	"\x11RequirementTarget\x12\x14\n" +
	"\x05entry\x18\x01 \x01(\tR\x05entry\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path*\x88\x01\n" +
	"\x0eProtectionType\x12\x1f\n" +
	"\x1bPROTECTION_TYPE_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14PROTECTION_TYPE_NONE\x10\x01\x12\x1c\n" +
	"\x18PROTECTION_TYPE_BYTECODE\x10\x02\x12\x1d\n" +
	"\x19PROTECTION_TYPE_ENCRYPTED\x10\x03B\xf8\x01\n" +
	"\x1ccom.wippy.api.hub.version.v1B\fMessageProtoP\x01ZEgithub.com/wippyai/runtime/api/hub/wippy/api/hub/version/v1;versionv1\xa2\x02\x04WAHV\xaa\x02\x18Wippy.Api.Hub.Version.V1\xca\x02\x18Wippy\\Api\\Hub\\Version\\V1\xe2\x02$Wippy\\Api\\Hub\\Version\\V1\\GPBMetadata\xea\x02\x1cWippy::Api::Hub::Version::V1b\x06proto3"

var (
	file_wippy_api_hub_version_v1_message_proto_rawDescOnce sync.Once
	file_wippy_api_hub_version_v1_message_proto_rawDescData []byte
)

func file_wippy_api_hub_version_v1_message_proto_rawDescGZIP() []byte {
	file_wippy_api_hub_version_v1_message_proto_rawDescOnce.Do(func() {
		file_wippy_api_hub_version_v1_message_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_wippy_api_hub_version_v1_message_proto_rawDesc), len(file_wippy_api_hub_version_v1_message_proto_rawDesc)))
	})
	return file_wippy_api_hub_version_v1_message_proto_rawDescData
}

var file_wippy_api_hub_version_v1_message_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_wippy_api_hub_version_v1_message_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_wippy_api_hub_version_v1_message_proto_goTypes = []any{
	(ProtectionType)(0),           // 0: wippy.api.hub.version.v1.ProtectionType
	(*VersionRef)(nil),            // 1: wippy.api.hub.version.v1.VersionRef
	(*Version)(nil),               // 2: wippy.api.hub.version.v1.Version
	(*VersionMetadata)(nil),       // 3: wippy.api.hub.version.v1.VersionMetadata
	(*Dependency)(nil),            // 4: wippy.api.hub.version.v1.Dependency
	(*VersionFile)(nil),           // 5: wippy.api.hub.version.v1.VersionFile
	(*Label)(nil),                 // 6: wippy.api.hub.version.v1.Label
	(*Requirement)(nil),           // 7: wippy.api.hub.version.v1.Requirement
	(*RequirementTarget)(nil),     // 8: wippy.api.hub.version.v1.RequirementTarget
	(*timestamppb.Timestamp)(nil), // 9: google.protobuf.Timestamp
}
var file_wippy_api_hub_version_v1_message_proto_depIdxs = []int32{
	9, // 0: wippy.api.hub.version.v1.Version.create_time:type_name -> google.protobuf.Timestamp
	3, // 1: wippy.api.hub.version.v1.Version.metadata:type_name -> wippy.api.hub.version.v1.VersionMetadata
	0, // 2: wippy.api.hub.version.v1.Version.protection_type:type_name -> wippy.api.hub.version.v1.ProtectionType
	4, // 3: wippy.api.hub.version.v1.Version.dependencies:type_name -> wippy.api.hub.version.v1.Dependency
	7, // 4: wippy.api.hub.version.v1.Version.requirements:type_name -> wippy.api.hub.version.v1.Requirement
	5, // 5: wippy.api.hub.version.v1.Version.files:type_name -> wippy.api.hub.version.v1.VersionFile
	9, // 6: wippy.api.hub.version.v1.Label.update_time:type_name -> google.protobuf.Timestamp
	8, // 7: wippy.api.hub.version.v1.Requirement.targets:type_name -> wippy.api.hub.version.v1.RequirementTarget
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_wippy_api_hub_version_v1_message_proto_init() }
func file_wippy_api_hub_version_v1_message_proto_init() {
	if File_wippy_api_hub_version_v1_message_proto != nil {
		return
	}
	file_wippy_api_hub_version_v1_message_proto_msgTypes[0].OneofWrappers = []any{
		(*VersionRef_Id)(nil),
		(*VersionRef_Version)(nil),
		(*VersionRef_Label)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_wippy_api_hub_version_v1_message_proto_rawDesc), len(file_wippy_api_hub_version_v1_message_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_wippy_api_hub_version_v1_message_proto_goTypes,
		DependencyIndexes: file_wippy_api_hub_version_v1_message_proto_depIdxs,
		EnumInfos:         file_wippy_api_hub_version_v1_message_proto_enumTypes,
		MessageInfos:      file_wippy_api_hub_version_v1_message_proto_msgTypes,
	}.Build()
	File_wippy_api_hub_version_v1_message_proto = out.File
	file_wippy_api_hub_version_v1_message_proto_goTypes = nil
	file_wippy_api_hub_version_v1_message_proto_depIdxs = nil
}
