// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/wippyai/module-registry-proto-go/registry/identity/v1/identityv1connect (interfaces: OrganizationServiceClient)
//
// Generated by this command:
//
//	mockgen -destination tests/mock/identityv1connect/identityv1connect.go github.com/wippyai/module-registry-proto-go/registry/identity/v1/identityv1connect OrganizationServiceClient
//

// Package mock_identityv1connect is a generated GoMock package.
package mock_identityv1connect

import (
	context "context"
	reflect "reflect"

	connect "connectrpc.com/connect"
	identityv1 "github.com/wippyai/module-registry-proto-go/registry/identity/v1"
	gomock "go.uber.org/mock/gomock"
)

// MockOrganizationServiceClient is a mock of OrganizationServiceClient interface.
type MockOrganizationServiceClient struct {
	ctrl     *gomock.Controller
	recorder *MockOrganizationServiceClientMockRecorder
	isgomock struct{}
}

// MockOrganizationServiceClientMockRecorder is the mock recorder for MockOrganizationServiceClient.
type MockOrganizationServiceClientMockRecorder struct {
	mock *MockOrganizationServiceClient
}

// NewMockOrganizationServiceClient creates a new mock instance.
func NewMockOrganizationServiceClient(ctrl *gomock.Controller) *MockOrganizationServiceClient {
	mock := &MockOrganizationServiceClient{ctrl: ctrl}
	mock.recorder = &MockOrganizationServiceClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOrganizationServiceClient) EXPECT() *MockOrganizationServiceClientMockRecorder {
	return m.recorder
}

// CreateOrganization mocks base method.
func (m *MockOrganizationServiceClient) CreateOrganization(arg0 context.Context, arg1 *connect.Request[identityv1.CreateOrganizationRequest]) (*connect.Response[identityv1.CreateOrganizationResponse], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateOrganization", arg0, arg1)
	ret0, _ := ret[0].(*connect.Response[identityv1.CreateOrganizationResponse])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateOrganization indicates an expected call of CreateOrganization.
func (mr *MockOrganizationServiceClientMockRecorder) CreateOrganization(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateOrganization", reflect.TypeOf((*MockOrganizationServiceClient)(nil).CreateOrganization), arg0, arg1)
}

// ListOrganizations mocks base method.
func (m *MockOrganizationServiceClient) ListOrganizations(arg0 context.Context, arg1 *connect.Request[identityv1.ListOrganizationsRequest]) (*connect.Response[identityv1.ListOrganizationsResponse], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListOrganizations", arg0, arg1)
	ret0, _ := ret[0].(*connect.Response[identityv1.ListOrganizationsResponse])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListOrganizations indicates an expected call of ListOrganizations.
func (mr *MockOrganizationServiceClientMockRecorder) ListOrganizations(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListOrganizations", reflect.TypeOf((*MockOrganizationServiceClient)(nil).ListOrganizations), arg0, arg1)
}

// ListUserOrganizations mocks base method.
func (m *MockOrganizationServiceClient) ListUserOrganizations(arg0 context.Context, arg1 *connect.Request[identityv1.ListOrganizationsRequest]) (*connect.Response[identityv1.ListOrganizationsResponse], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListUserOrganizations", arg0, arg1)
	ret0, _ := ret[0].(*connect.Response[identityv1.ListOrganizationsResponse])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListUserOrganizations indicates an expected call of ListUserOrganizations.
func (mr *MockOrganizationServiceClientMockRecorder) ListUserOrganizations(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListUserOrganizations", reflect.TypeOf((*MockOrganizationServiceClient)(nil).ListUserOrganizations), arg0, arg1)
}
