package lua

const (
	// Lua component names
	LuaEngineName = "lua.engine"
	LuaEnvName    = "lua.env"
	LuaIOName     = "lua.io"
	LuaLoggerName = "lua.logger"
	LuaBase64Name = "lua.base64"
	// LuaBteaName reserved for future use
	LuaChannelName          = "lua.channel"
	LuaCloudStorageName     = "lua.cloudstorage"
	LuaCompressName         = "lua.compress"
	LuaContractName         = "lua.contract"
	LuaContextName          = "lua.context"
	LuaEvalName             = "lua.eval"
	LuaCryptoName           = "lua.crypto"
	LuaEventsName           = "lua.events"
	LuaExcelName            = "lua.excel"
	LuaExecName             = "lua.exec"
	LuaExprName             = "lua.expr"
	LuaFSName               = "lua.fs"
	LuaFuncName             = "lua.func"
	LuaHTMLName             = "lua.html"
	LuaHTTPName             = "lua.http"
	LuaMetricsName          = "lua.metrics"
	LuaJSONName             = "lua.json"
	LuaPayloadName          = "lua.payload"
	LuaProcessName          = "lua.process"
	LuaRegistryName         = "lua.registry"
	LuaSecurityName         = "lua.security"
	LuaSQLName              = "lua.sql"
	LuaStoreName            = "lua.store"
	LuaStreamName           = "lua.stream"
	LuaSubscribeName        = "lua.subscribe"
	LuaSystemName           = "lua.system"
	LuaTemplateName         = "lua.template"
	LuaTextName             = "lua.text"
	LuaTimeName             = "lua.time"
	LuaTreeSitterName       = "lua.treesitter"
	LuaQueueName            = "lua.queue"
	LuaTemporalActivityName = "lua.temporal_activity"
	// LuaUpstreamName reserved for future use
	LuaUUIDName      = "lua.uuid"
	LuaWebSocketName = "lua.websocket"
	LuaYAMLName      = "lua.yaml"
)
