// SPDX-License-Identifier: MPL-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: wippy/api/hub/download/v1/service.proto

package downloadv1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	v12 "github.com/wippyai/runtime/api/hub/wippy/api/hub/common/v1"
	v1 "github.com/wippyai/runtime/api/hub/wippy/api/hub/module/v1"
	v11 "github.com/wippyai/runtime/api/hub/wippy/api/hub/version/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetDownloadURLRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Module        *v1.ModuleRef          `protobuf:"bytes,1,opt,name=module,proto3" json:"module,omitempty"`
	Version       *v11.VersionRef        `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDownloadURLRequest) Reset() {
	*x = GetDownloadURLRequest{}
	mi := &file_wippy_api_hub_download_v1_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDownloadURLRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDownloadURLRequest) ProtoMessage() {}

func (x *GetDownloadURLRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wippy_api_hub_download_v1_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDownloadURLRequest.ProtoReflect.Descriptor instead.
func (*GetDownloadURLRequest) Descriptor() ([]byte, []int) {
	return file_wippy_api_hub_download_v1_service_proto_rawDescGZIP(), []int{0}
}

func (x *GetDownloadURLRequest) GetModule() *v1.ModuleRef {
	if x != nil {
		return x.Module
	}
	return nil
}

func (x *GetDownloadURLRequest) GetVersion() *v11.VersionRef {
	if x != nil {
		return x.Version
	}
	return nil
}

type GetDownloadURLResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Download      *v12.DownloadInfo      `protobuf:"bytes,1,opt,name=download,proto3" json:"download,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Protected     bool                   `protobuf:"varint,3,opt,name=protected,proto3" json:"protected,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDownloadURLResponse) Reset() {
	*x = GetDownloadURLResponse{}
	mi := &file_wippy_api_hub_download_v1_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDownloadURLResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDownloadURLResponse) ProtoMessage() {}

func (x *GetDownloadURLResponse) ProtoReflect() protoreflect.Message {
	mi := &file_wippy_api_hub_download_v1_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDownloadURLResponse.ProtoReflect.Descriptor instead.
func (*GetDownloadURLResponse) Descriptor() ([]byte, []int) {
	return file_wippy_api_hub_download_v1_service_proto_rawDescGZIP(), []int{1}
}

func (x *GetDownloadURLResponse) GetDownload() *v12.DownloadInfo {
	if x != nil {
		return x.Download
	}
	return nil
}

func (x *GetDownloadURLResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *GetDownloadURLResponse) GetProtected() bool {
	if x != nil {
		return x.Protected
	}
	return false
}

type GetBatchDownloadURLsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*BatchDownloadItem   `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBatchDownloadURLsRequest) Reset() {
	*x = GetBatchDownloadURLsRequest{}
	mi := &file_wippy_api_hub_download_v1_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBatchDownloadURLsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBatchDownloadURLsRequest) ProtoMessage() {}

func (x *GetBatchDownloadURLsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wippy_api_hub_download_v1_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBatchDownloadURLsRequest.ProtoReflect.Descriptor instead.
func (*GetBatchDownloadURLsRequest) Descriptor() ([]byte, []int) {
	return file_wippy_api_hub_download_v1_service_proto_rawDescGZIP(), []int{2}
}

func (x *GetBatchDownloadURLsRequest) GetItems() []*BatchDownloadItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type BatchDownloadItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Org           string                 `protobuf:"bytes,1,opt,name=org,proto3" json:"org,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Version       string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchDownloadItem) Reset() {
	*x = BatchDownloadItem{}
	mi := &file_wippy_api_hub_download_v1_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchDownloadItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchDownloadItem) ProtoMessage() {}

func (x *BatchDownloadItem) ProtoReflect() protoreflect.Message {
	mi := &file_wippy_api_hub_download_v1_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchDownloadItem.ProtoReflect.Descriptor instead.
func (*BatchDownloadItem) Descriptor() ([]byte, []int) {
	return file_wippy_api_hub_download_v1_service_proto_rawDescGZIP(), []int{3}
}

func (x *BatchDownloadItem) GetOrg() string {
	if x != nil {
		return x.Org
	}
	return ""
}

func (x *BatchDownloadItem) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *BatchDownloadItem) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type GetBatchDownloadURLsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*BatchDownloadResult `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBatchDownloadURLsResponse) Reset() {
	*x = GetBatchDownloadURLsResponse{}
	mi := &file_wippy_api_hub_download_v1_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBatchDownloadURLsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBatchDownloadURLsResponse) ProtoMessage() {}

func (x *GetBatchDownloadURLsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_wippy_api_hub_download_v1_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBatchDownloadURLsResponse.ProtoReflect.Descriptor instead.
func (*GetBatchDownloadURLsResponse) Descriptor() ([]byte, []int) {
	return file_wippy_api_hub_download_v1_service_proto_rawDescGZIP(), []int{4}
}

func (x *GetBatchDownloadURLsResponse) GetResults() []*BatchDownloadResult {
	if x != nil {
		return x.Results
	}
	return nil
}

type BatchDownloadResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Org           string                 `protobuf:"bytes,1,opt,name=org,proto3" json:"org,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Version       string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	Download      *v12.DownloadInfo      `protobuf:"bytes,4,opt,name=download,proto3" json:"download,omitempty"`
	Protected     bool                   `protobuf:"varint,5,opt,name=protected,proto3" json:"protected,omitempty"`
	Error         *v12.OperationError    `protobuf:"bytes,6,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchDownloadResult) Reset() {
	*x = BatchDownloadResult{}
	mi := &file_wippy_api_hub_download_v1_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchDownloadResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchDownloadResult) ProtoMessage() {}

func (x *BatchDownloadResult) ProtoReflect() protoreflect.Message {
	mi := &file_wippy_api_hub_download_v1_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchDownloadResult.ProtoReflect.Descriptor instead.
func (*BatchDownloadResult) Descriptor() ([]byte, []int) {
	return file_wippy_api_hub_download_v1_service_proto_rawDescGZIP(), []int{5}
}

func (x *BatchDownloadResult) GetOrg() string {
	if x != nil {
		return x.Org
	}
	return ""
}

func (x *BatchDownloadResult) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *BatchDownloadResult) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *BatchDownloadResult) GetDownload() *v12.DownloadInfo {
	if x != nil {
		return x.Download
	}
	return nil
}

func (x *BatchDownloadResult) GetProtected() bool {
	if x != nil {
		return x.Protected
	}
	return false
}

func (x *BatchDownloadResult) GetError() *v12.OperationError {
	if x != nil {
		return x.Error
	}
	return nil
}

var File_wippy_api_hub_download_v1_service_proto protoreflect.FileDescriptor

const file_wippy_api_hub_download_v1_service_proto_rawDesc = "" +
	"\n" +
	"'wippy/api/hub/download/v1/service.proto\x12\x19wippy.api.hub.download.v1\x1a\x1bbuf/validate/validate.proto\x1a%wippy/api/hub/common/v1/message.proto\x1a%wippy/api/hub/module/v1/message.proto\x1a&wippy/api/hub/version/v1/message.proto\"\x9b\x01\n" +
	"\x15GetDownloadURLRequest\x12B\n" +
	"\x06module\x18\x01 \x01(\v2\".wippy.api.hub.module.v1.ModuleRefB\x06\xbaH\x03\xc8\x01\x01R\x06module\x12>\n" +
	"\aversion\x18\x02 \x01(\v2$.wippy.api.hub.version.v1.VersionRefR\aversion\"\x93\x01\n" +
	"\x16GetDownloadURLResponse\x12A\n" +
	"\bdownload\x18\x01 \x01(\v2%.wippy.api.hub.common.v1.DownloadInfoR\bdownload\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\x1c\n" +
	"\tprotected\x18\x03 \x01(\bR\tprotected\"m\n" +
	"\x1bGetBatchDownloadURLsRequest\x12N\n" +
	"\x05items\x18\x01 \x03(\v2,.wippy.api.hub.download.v1.BatchDownloadItemB\n" +
	"\xbaH\a\x92\x01\x04\b\x01\x102R\x05items\"e\n" +
	"\x11BatchDownloadItem\x12\x19\n" +
	"\x03org\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x03org\x12\x1b\n" +
	"\x04name\x18\x02 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x04name\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\"h\n" +
	"\x1cGetBatchDownloadURLsResponse\x12H\n" +
	"\aresults\x18\x01 \x03(\v2..wippy.api.hub.download.v1.BatchDownloadResultR\aresults\"\xf5\x01\n" +
	"\x13BatchDownloadResult\x12\x10\n" +
	"\x03org\x18\x01 \x01(\tR\x03org\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\x12A\n" +
	"\bdownload\x18\x04 \x01(\v2%.wippy.api.hub.common.v1.DownloadInfoR\bdownload\x12\x1c\n" +
	"\tprotected\x18\x05 \x01(\bR\tprotected\x12=\n" +
	"\x05error\x18\x06 \x01(\v2'.wippy.api.hub.common.v1.OperationErrorR\x05error2\x9c\x02\n" +
	"\x0fDownloadService\x12z\n" +
	"\x0eGetDownloadURL\x120.wippy.api.hub.download.v1.GetDownloadURLRequest\x1a1.wippy.api.hub.download.v1.GetDownloadURLResponse\"\x03\x90\x02\x01\x12\x8c\x01\n" +
	"\x14GetBatchDownloadURLs\x126.wippy.api.hub.download.v1.GetBatchDownloadURLsRequest\x1a7.wippy.api.hub.download.v1.GetBatchDownloadURLsResponse\"\x03\x90\x02\x01B\xff\x01\n" +
	"\x1dcom.wippy.api.hub.download.v1B\fServiceProtoP\x01ZGgithub.com/wippyai/runtime/api/hub/wippy/api/hub/download/v1;downloadv1\xa2\x02\x04WAHD\xaa\x02\x19Wippy.Api.Hub.Download.V1\xca\x02\x19Wippy\\Api\\Hub\\Download\\V1\xe2\x02%Wippy\\Api\\Hub\\Download\\V1\\GPBMetadata\xea\x02\x1dWippy::Api::Hub::Download::V1b\x06proto3"

var (
	file_wippy_api_hub_download_v1_service_proto_rawDescOnce sync.Once
	file_wippy_api_hub_download_v1_service_proto_rawDescData []byte
)

func file_wippy_api_hub_download_v1_service_proto_rawDescGZIP() []byte {
	file_wippy_api_hub_download_v1_service_proto_rawDescOnce.Do(func() {
		file_wippy_api_hub_download_v1_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_wippy_api_hub_download_v1_service_proto_rawDesc), len(file_wippy_api_hub_download_v1_service_proto_rawDesc)))
	})
	return file_wippy_api_hub_download_v1_service_proto_rawDescData
}

var file_wippy_api_hub_download_v1_service_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_wippy_api_hub_download_v1_service_proto_goTypes = []any{
	(*GetDownloadURLRequest)(nil),        // 0: wippy.api.hub.download.v1.GetDownloadURLRequest
	(*GetDownloadURLResponse)(nil),       // 1: wippy.api.hub.download.v1.GetDownloadURLResponse
	(*GetBatchDownloadURLsRequest)(nil),  // 2: wippy.api.hub.download.v1.GetBatchDownloadURLsRequest
	(*BatchDownloadItem)(nil),            // 3: wippy.api.hub.download.v1.BatchDownloadItem
	(*GetBatchDownloadURLsResponse)(nil), // 4: wippy.api.hub.download.v1.GetBatchDownloadURLsResponse
	(*BatchDownloadResult)(nil),          // 5: wippy.api.hub.download.v1.BatchDownloadResult
	(*v1.ModuleRef)(nil),                 // 6: wippy.api.hub.module.v1.ModuleRef
	(*v11.VersionRef)(nil),               // 7: wippy.api.hub.version.v1.VersionRef
	(*v12.DownloadInfo)(nil),             // 8: wippy.api.hub.common.v1.DownloadInfo
	(*v12.OperationError)(nil),           // 9: wippy.api.hub.common.v1.OperationError
}
var file_wippy_api_hub_download_v1_service_proto_depIdxs = []int32{
	6, // 0: wippy.api.hub.download.v1.GetDownloadURLRequest.module:type_name -> wippy.api.hub.module.v1.ModuleRef
	7, // 1: wippy.api.hub.download.v1.GetDownloadURLRequest.version:type_name -> wippy.api.hub.version.v1.VersionRef
	8, // 2: wippy.api.hub.download.v1.GetDownloadURLResponse.download:type_name -> wippy.api.hub.common.v1.DownloadInfo
	3, // 3: wippy.api.hub.download.v1.GetBatchDownloadURLsRequest.items:type_name -> wippy.api.hub.download.v1.BatchDownloadItem
	5, // 4: wippy.api.hub.download.v1.GetBatchDownloadURLsResponse.results:type_name -> wippy.api.hub.download.v1.BatchDownloadResult
	8, // 5: wippy.api.hub.download.v1.BatchDownloadResult.download:type_name -> wippy.api.hub.common.v1.DownloadInfo
	9, // 6: wippy.api.hub.download.v1.BatchDownloadResult.error:type_name -> wippy.api.hub.common.v1.OperationError
	0, // 7: wippy.api.hub.download.v1.DownloadService.GetDownloadURL:input_type -> wippy.api.hub.download.v1.GetDownloadURLRequest
	2, // 8: wippy.api.hub.download.v1.DownloadService.GetBatchDownloadURLs:input_type -> wippy.api.hub.download.v1.GetBatchDownloadURLsRequest
	1, // 9: wippy.api.hub.download.v1.DownloadService.GetDownloadURL:output_type -> wippy.api.hub.download.v1.GetDownloadURLResponse
	4, // 10: wippy.api.hub.download.v1.DownloadService.GetBatchDownloadURLs:output_type -> wippy.api.hub.download.v1.GetBatchDownloadURLsResponse
	9, // [9:11] is the sub-list for method output_type
	7, // [7:9] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_wippy_api_hub_download_v1_service_proto_init() }
func file_wippy_api_hub_download_v1_service_proto_init() {
	if File_wippy_api_hub_download_v1_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_wippy_api_hub_download_v1_service_proto_rawDesc), len(file_wippy_api_hub_download_v1_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_wippy_api_hub_download_v1_service_proto_goTypes,
		DependencyIndexes: file_wippy_api_hub_download_v1_service_proto_depIdxs,
		MessageInfos:      file_wippy_api_hub_download_v1_service_proto_msgTypes,
	}.Build()
	File_wippy_api_hub_download_v1_service_proto = out.File
	file_wippy_api_hub_download_v1_service_proto_goTypes = nil
	file_wippy_api_hub_download_v1_service_proto_depIdxs = nil
}
