// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: wippy/api/hub/publish/v1/message.proto

package publishv1

import (
	v1 "github.com/wippyai/runtime/api/hub/wippy/api/hub/version/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Publish operation status.
type PublishStatus int32

const (
	PublishStatus_PUBLISH_STATUS_UNSPECIFIED    PublishStatus = 0
	PublishStatus_PUBLISH_STATUS_PENDING_UPLOAD PublishStatus = 1
	PublishStatus_PUBLISH_STATUS_PROCESSING     PublishStatus = 2
	PublishStatus_PUBLISH_STATUS_VALIDATING     PublishStatus = 3
	PublishStatus_PUBLISH_STATUS_COMPLETED      PublishStatus = 4
	PublishStatus_PUBLISH_STATUS_FAILED         PublishStatus = 5
	PublishStatus_PUBLISH_STATUS_CANCELLED      PublishStatus = 6
)

// Enum value maps for PublishStatus.
var (
	PublishStatus_name = map[int32]string{
		0: "PUBLISH_STATUS_UNSPECIFIED",
		1: "PUBLISH_STATUS_PENDING_UPLOAD",
		2: "PUBLISH_STATUS_PROCESSING",
		3: "PUBLISH_STATUS_VALIDATING",
		4: "PUBLISH_STATUS_COMPLETED",
		5: "PUBLISH_STATUS_FAILED",
		6: "PUBLISH_STATUS_CANCELLED",
	}
	PublishStatus_value = map[string]int32{
		"PUBLISH_STATUS_UNSPECIFIED":    0,
		"PUBLISH_STATUS_PENDING_UPLOAD": 1,
		"PUBLISH_STATUS_PROCESSING":     2,
		"PUBLISH_STATUS_VALIDATING":     3,
		"PUBLISH_STATUS_COMPLETED":      4,
		"PUBLISH_STATUS_FAILED":         5,
		"PUBLISH_STATUS_CANCELLED":      6,
	}
)

func (x PublishStatus) Enum() *PublishStatus {
	p := new(PublishStatus)
	*p = x
	return p
}

func (x PublishStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PublishStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_wippy_api_hub_publish_v1_message_proto_enumTypes[0].Descriptor()
}

func (PublishStatus) Type() protoreflect.EnumType {
	return &file_wippy_api_hub_publish_v1_message_proto_enumTypes[0]
}

func (x PublishStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PublishStatus.Descriptor instead.
func (PublishStatus) EnumDescriptor() ([]byte, []int) {
	return file_wippy_api_hub_publish_v1_message_proto_rawDescGZIP(), []int{0}
}

// Detailed status information.
type PublishStatusDetails struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ErrorMessage  string                 `protobuf:"bytes,1,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	ErrorCode     string                 `protobuf:"bytes,2,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	Version       *v1.Version            `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	Stage         string                 `protobuf:"bytes,4,opt,name=stage,proto3" json:"stage,omitempty"`
	Progress      int32                  `protobuf:"varint,5,opt,name=progress,proto3" json:"progress,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishStatusDetails) Reset() {
	*x = PublishStatusDetails{}
	mi := &file_wippy_api_hub_publish_v1_message_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishStatusDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishStatusDetails) ProtoMessage() {}

func (x *PublishStatusDetails) ProtoReflect() protoreflect.Message {
	mi := &file_wippy_api_hub_publish_v1_message_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishStatusDetails.ProtoReflect.Descriptor instead.
func (*PublishStatusDetails) Descriptor() ([]byte, []int) {
	return file_wippy_api_hub_publish_v1_message_proto_rawDescGZIP(), []int{0}
}

func (x *PublishStatusDetails) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *PublishStatusDetails) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

func (x *PublishStatusDetails) GetVersion() *v1.Version {
	if x != nil {
		return x.Version
	}
	return nil
}

func (x *PublishStatusDetails) GetStage() string {
	if x != nil {
		return x.Stage
	}
	return ""
}

func (x *PublishStatusDetails) GetProgress() int32 {
	if x != nil {
		return x.Progress
	}
	return 0
}

var File_wippy_api_hub_publish_v1_message_proto protoreflect.FileDescriptor

const file_wippy_api_hub_publish_v1_message_proto_rawDesc = "" +
	"\n" +
	"&wippy/api/hub/publish/v1/message.proto\x12\x18wippy.api.hub.publish.v1\x1a&wippy/api/hub/version/v1/message.proto\"\xc9\x01\n" +
	"\x14PublishStatusDetails\x12#\n" +
	"\rerror_message\x18\x01 \x01(\tR\ferrorMessage\x12\x1d\n" +
	"\n" +
	"error_code\x18\x02 \x01(\tR\terrorCode\x12;\n" +
	"\aversion\x18\x03 \x01(\v2!.wippy.api.hub.version.v1.VersionR\aversion\x12\x14\n" +
	"\x05stage\x18\x04 \x01(\tR\x05stage\x12\x1a\n" +
	"\bprogress\x18\x05 \x01(\x05R\bprogress*\xe7\x01\n" +
	"\rPublishStatus\x12\x1e\n" +
	"\x1aPUBLISH_STATUS_UNSPECIFIED\x10\x00\x12!\n" +
	"\x1dPUBLISH_STATUS_PENDING_UPLOAD\x10\x01\x12\x1d\n" +
	"\x19PUBLISH_STATUS_PROCESSING\x10\x02\x12\x1d\n" +
	"\x19PUBLISH_STATUS_VALIDATING\x10\x03\x12\x1c\n" +
	"\x18PUBLISH_STATUS_COMPLETED\x10\x04\x12\x19\n" +
	"\x15PUBLISH_STATUS_FAILED\x10\x05\x12\x1c\n" +
	"\x18PUBLISH_STATUS_CANCELLED\x10\x06B\xf8\x01\n" +
	"\x1ccom.wippy.api.hub.publish.v1B\fMessageProtoP\x01ZEgithub.com/wippyai/runtime/api/hub/wippy/api/hub/publish/v1;publishv1\xa2\x02\x04WAHP\xaa\x02\x18Wippy.Api.Hub.Publish.V1\xca\x02\x18Wippy\\Api\\Hub\\Publish\\V1\xe2\x02$Wippy\\Api\\Hub\\Publish\\V1\\GPBMetadata\xea\x02\x1cWippy::Api::Hub::Publish::V1b\x06proto3"

var (
	file_wippy_api_hub_publish_v1_message_proto_rawDescOnce sync.Once
	file_wippy_api_hub_publish_v1_message_proto_rawDescData []byte
)

func file_wippy_api_hub_publish_v1_message_proto_rawDescGZIP() []byte {
	file_wippy_api_hub_publish_v1_message_proto_rawDescOnce.Do(func() {
		file_wippy_api_hub_publish_v1_message_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_wippy_api_hub_publish_v1_message_proto_rawDesc), len(file_wippy_api_hub_publish_v1_message_proto_rawDesc)))
	})
	return file_wippy_api_hub_publish_v1_message_proto_rawDescData
}

var file_wippy_api_hub_publish_v1_message_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_wippy_api_hub_publish_v1_message_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_wippy_api_hub_publish_v1_message_proto_goTypes = []any{
	(PublishStatus)(0),           // 0: wippy.api.hub.publish.v1.PublishStatus
	(*PublishStatusDetails)(nil), // 1: wippy.api.hub.publish.v1.PublishStatusDetails
	(*v1.Version)(nil),           // 2: wippy.api.hub.version.v1.Version
}
var file_wippy_api_hub_publish_v1_message_proto_depIdxs = []int32{
	2, // 0: wippy.api.hub.publish.v1.PublishStatusDetails.version:type_name -> wippy.api.hub.version.v1.Version
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_wippy_api_hub_publish_v1_message_proto_init() }
func file_wippy_api_hub_publish_v1_message_proto_init() {
	if File_wippy_api_hub_publish_v1_message_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_wippy_api_hub_publish_v1_message_proto_rawDesc), len(file_wippy_api_hub_publish_v1_message_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_wippy_api_hub_publish_v1_message_proto_goTypes,
		DependencyIndexes: file_wippy_api_hub_publish_v1_message_proto_depIdxs,
		EnumInfos:         file_wippy_api_hub_publish_v1_message_proto_enumTypes,
		MessageInfos:      file_wippy_api_hub_publish_v1_message_proto_msgTypes,
	}.Build()
	File_wippy_api_hub_publish_v1_message_proto = out.File
	file_wippy_api_hub_publish_v1_message_proto_goTypes = nil
	file_wippy_api_hub_publish_v1_message_proto_depIdxs = nil
}
