// SPDX-License-Identifier: MPL-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: wippy/api/hub/publish/v1/service.proto

package publishv1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	v1 "github.com/wippyai/runtime/api/hub/wippy/api/hub/module/v1"
	v11 "github.com/wippyai/runtime/api/hub/wippy/api/hub/version/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InitiatePublishRequest struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Module *v1.ModuleRef          `protobuf:"bytes,1,opt,name=module,proto3" json:"module,omitempty"`
	// Types that are valid to be assigned to Target:
	//
	//	*InitiatePublishRequest_Version
	//	*InitiatePublishRequest_Label
	Target            isInitiatePublishRequest_Target `protobuf_oneof:"target"`
	ExpectedSizeBytes uint64                          `protobuf:"varint,4,opt,name=expected_size_bytes,json=expectedSizeBytes,proto3" json:"expected_size_bytes,omitempty"`
	Digest            string                          `protobuf:"bytes,5,opt,name=digest,proto3" json:"digest,omitempty"`
	Protected         bool                            `protobuf:"varint,6,opt,name=protected,proto3" json:"protected,omitempty"`
	ReleaseNotes      string                          `protobuf:"bytes,7,opt,name=release_notes,json=releaseNotes,proto3" json:"release_notes,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *InitiatePublishRequest) Reset() {
	*x = InitiatePublishRequest{}
	mi := &file_wippy_api_hub_publish_v1_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitiatePublishRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitiatePublishRequest) ProtoMessage() {}

func (x *InitiatePublishRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wippy_api_hub_publish_v1_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitiatePublishRequest.ProtoReflect.Descriptor instead.
func (*InitiatePublishRequest) Descriptor() ([]byte, []int) {
	return file_wippy_api_hub_publish_v1_service_proto_rawDescGZIP(), []int{0}
}

func (x *InitiatePublishRequest) GetModule() *v1.ModuleRef {
	if x != nil {
		return x.Module
	}
	return nil
}

func (x *InitiatePublishRequest) GetTarget() isInitiatePublishRequest_Target {
	if x != nil {
		return x.Target
	}
	return nil
}

func (x *InitiatePublishRequest) GetVersion() string {
	if x != nil {
		if x, ok := x.Target.(*InitiatePublishRequest_Version); ok {
			return x.Version
		}
	}
	return ""
}

func (x *InitiatePublishRequest) GetLabel() string {
	if x != nil {
		if x, ok := x.Target.(*InitiatePublishRequest_Label); ok {
			return x.Label
		}
	}
	return ""
}

func (x *InitiatePublishRequest) GetExpectedSizeBytes() uint64 {
	if x != nil {
		return x.ExpectedSizeBytes
	}
	return 0
}

func (x *InitiatePublishRequest) GetDigest() string {
	if x != nil {
		return x.Digest
	}
	return ""
}

func (x *InitiatePublishRequest) GetProtected() bool {
	if x != nil {
		return x.Protected
	}
	return false
}

func (x *InitiatePublishRequest) GetReleaseNotes() string {
	if x != nil {
		return x.ReleaseNotes
	}
	return ""
}

type isInitiatePublishRequest_Target interface {
	isInitiatePublishRequest_Target()
}

type InitiatePublishRequest_Version struct {
	Version string `protobuf:"bytes,2,opt,name=version,proto3,oneof"`
}

type InitiatePublishRequest_Label struct {
	Label string `protobuf:"bytes,3,opt,name=label,proto3,oneof"`
}

func (*InitiatePublishRequest_Version) isInitiatePublishRequest_Target() {}

func (*InitiatePublishRequest_Label) isInitiatePublishRequest_Target() {}

type InitiatePublishResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	PublishId       string                 `protobuf:"bytes,1,opt,name=publish_id,json=publishId,proto3" json:"publish_id,omitempty"`
	UploadUrl       string                 `protobuf:"bytes,2,opt,name=upload_url,json=uploadUrl,proto3" json:"upload_url,omitempty"`
	UploadExpiresAt *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=upload_expires_at,json=uploadExpiresAt,proto3" json:"upload_expires_at,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *InitiatePublishResponse) Reset() {
	*x = InitiatePublishResponse{}
	mi := &file_wippy_api_hub_publish_v1_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitiatePublishResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitiatePublishResponse) ProtoMessage() {}

func (x *InitiatePublishResponse) ProtoReflect() protoreflect.Message {
	mi := &file_wippy_api_hub_publish_v1_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitiatePublishResponse.ProtoReflect.Descriptor instead.
func (*InitiatePublishResponse) Descriptor() ([]byte, []int) {
	return file_wippy_api_hub_publish_v1_service_proto_rawDescGZIP(), []int{1}
}

func (x *InitiatePublishResponse) GetPublishId() string {
	if x != nil {
		return x.PublishId
	}
	return ""
}

func (x *InitiatePublishResponse) GetUploadUrl() string {
	if x != nil {
		return x.UploadUrl
	}
	return ""
}

func (x *InitiatePublishResponse) GetUploadExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UploadExpiresAt
	}
	return nil
}

type ConfirmPublishRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PublishId     string                 `protobuf:"bytes,1,opt,name=publish_id,json=publishId,proto3" json:"publish_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfirmPublishRequest) Reset() {
	*x = ConfirmPublishRequest{}
	mi := &file_wippy_api_hub_publish_v1_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfirmPublishRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmPublishRequest) ProtoMessage() {}

func (x *ConfirmPublishRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wippy_api_hub_publish_v1_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmPublishRequest.ProtoReflect.Descriptor instead.
func (*ConfirmPublishRequest) Descriptor() ([]byte, []int) {
	return file_wippy_api_hub_publish_v1_service_proto_rawDescGZIP(), []int{2}
}

func (x *ConfirmPublishRequest) GetPublishId() string {
	if x != nil {
		return x.PublishId
	}
	return ""
}

type ConfirmPublishResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        PublishStatus          `protobuf:"varint,1,opt,name=status,proto3,enum=wippy.api.hub.publish.v1.PublishStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfirmPublishResponse) Reset() {
	*x = ConfirmPublishResponse{}
	mi := &file_wippy_api_hub_publish_v1_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfirmPublishResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmPublishResponse) ProtoMessage() {}

func (x *ConfirmPublishResponse) ProtoReflect() protoreflect.Message {
	mi := &file_wippy_api_hub_publish_v1_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmPublishResponse.ProtoReflect.Descriptor instead.
func (*ConfirmPublishResponse) Descriptor() ([]byte, []int) {
	return file_wippy_api_hub_publish_v1_service_proto_rawDescGZIP(), []int{3}
}

func (x *ConfirmPublishResponse) GetStatus() PublishStatus {
	if x != nil {
		return x.Status
	}
	return PublishStatus_PUBLISH_STATUS_UNSPECIFIED
}

type GetPublishStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PublishId     string                 `protobuf:"bytes,1,opt,name=publish_id,json=publishId,proto3" json:"publish_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPublishStatusRequest) Reset() {
	*x = GetPublishStatusRequest{}
	mi := &file_wippy_api_hub_publish_v1_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPublishStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPublishStatusRequest) ProtoMessage() {}

func (x *GetPublishStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wippy_api_hub_publish_v1_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPublishStatusRequest.ProtoReflect.Descriptor instead.
func (*GetPublishStatusRequest) Descriptor() ([]byte, []int) {
	return file_wippy_api_hub_publish_v1_service_proto_rawDescGZIP(), []int{4}
}

func (x *GetPublishStatusRequest) GetPublishId() string {
	if x != nil {
		return x.PublishId
	}
	return ""
}

type GetPublishStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        PublishStatus          `protobuf:"varint,1,opt,name=status,proto3,enum=wippy.api.hub.publish.v1.PublishStatus" json:"status,omitempty"`
	Details       *PublishStatusDetails  `protobuf:"bytes,2,opt,name=details,proto3" json:"details,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPublishStatusResponse) Reset() {
	*x = GetPublishStatusResponse{}
	mi := &file_wippy_api_hub_publish_v1_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPublishStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPublishStatusResponse) ProtoMessage() {}

func (x *GetPublishStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_wippy_api_hub_publish_v1_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPublishStatusResponse.ProtoReflect.Descriptor instead.
func (*GetPublishStatusResponse) Descriptor() ([]byte, []int) {
	return file_wippy_api_hub_publish_v1_service_proto_rawDescGZIP(), []int{5}
}

func (x *GetPublishStatusResponse) GetStatus() PublishStatus {
	if x != nil {
		return x.Status
	}
	return PublishStatus_PUBLISH_STATUS_UNSPECIFIED
}

func (x *GetPublishStatusResponse) GetDetails() *PublishStatusDetails {
	if x != nil {
		return x.Details
	}
	return nil
}

type CancelPublishRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PublishId     string                 `protobuf:"bytes,1,opt,name=publish_id,json=publishId,proto3" json:"publish_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelPublishRequest) Reset() {
	*x = CancelPublishRequest{}
	mi := &file_wippy_api_hub_publish_v1_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelPublishRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelPublishRequest) ProtoMessage() {}

func (x *CancelPublishRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wippy_api_hub_publish_v1_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelPublishRequest.ProtoReflect.Descriptor instead.
func (*CancelPublishRequest) Descriptor() ([]byte, []int) {
	return file_wippy_api_hub_publish_v1_service_proto_rawDescGZIP(), []int{6}
}

func (x *CancelPublishRequest) GetPublishId() string {
	if x != nil {
		return x.PublishId
	}
	return ""
}

type CancelPublishResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cancelled     bool                   `protobuf:"varint,1,opt,name=cancelled,proto3" json:"cancelled,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelPublishResponse) Reset() {
	*x = CancelPublishResponse{}
	mi := &file_wippy_api_hub_publish_v1_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelPublishResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelPublishResponse) ProtoMessage() {}

func (x *CancelPublishResponse) ProtoReflect() protoreflect.Message {
	mi := &file_wippy_api_hub_publish_v1_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelPublishResponse.ProtoReflect.Descriptor instead.
func (*CancelPublishResponse) Descriptor() ([]byte, []int) {
	return file_wippy_api_hub_publish_v1_service_proto_rawDescGZIP(), []int{7}
}

func (x *CancelPublishResponse) GetCancelled() bool {
	if x != nil {
		return x.Cancelled
	}
	return false
}

type YankVersionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Module        *v1.ModuleRef          `protobuf:"bytes,1,opt,name=module,proto3" json:"module,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Reason        string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *YankVersionRequest) Reset() {
	*x = YankVersionRequest{}
	mi := &file_wippy_api_hub_publish_v1_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *YankVersionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*YankVersionRequest) ProtoMessage() {}

func (x *YankVersionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wippy_api_hub_publish_v1_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use YankVersionRequest.ProtoReflect.Descriptor instead.
func (*YankVersionRequest) Descriptor() ([]byte, []int) {
	return file_wippy_api_hub_publish_v1_service_proto_rawDescGZIP(), []int{8}
}

func (x *YankVersionRequest) GetModule() *v1.ModuleRef {
	if x != nil {
		return x.Module
	}
	return nil
}

func (x *YankVersionRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *YankVersionRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type YankVersionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       *v11.Version           `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *YankVersionResponse) Reset() {
	*x = YankVersionResponse{}
	mi := &file_wippy_api_hub_publish_v1_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *YankVersionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*YankVersionResponse) ProtoMessage() {}

func (x *YankVersionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_wippy_api_hub_publish_v1_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use YankVersionResponse.ProtoReflect.Descriptor instead.
func (*YankVersionResponse) Descriptor() ([]byte, []int) {
	return file_wippy_api_hub_publish_v1_service_proto_rawDescGZIP(), []int{9}
}

func (x *YankVersionResponse) GetVersion() *v11.Version {
	if x != nil {
		return x.Version
	}
	return nil
}

var File_wippy_api_hub_publish_v1_service_proto protoreflect.FileDescriptor

const file_wippy_api_hub_publish_v1_service_proto_rawDesc = "" +
	"\n" +
	"&wippy/api/hub/publish/v1/service.proto\x12\x18wippy.api.hub.publish.v1\x1a\x1bbuf/validate/validate.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a%wippy/api/hub/module/v1/message.proto\x1a&wippy/api/hub/publish/v1/message.proto\x1a&wippy/api/hub/version/v1/message.proto\"\xd4\x02\n" +
	"\x16InitiatePublishRequest\x12B\n" +
	"\x06module\x18\x01 \x01(\v2\".wippy.api.hub.module.v1.ModuleRefB\x06\xbaH\x03\xc8\x01\x01R\x06module\x12#\n" +
	"\aversion\x18\x02 \x01(\tB\a\xbaH\x04r\x02\x18@H\x00R\aversion\x122\n" +
	"\x05label\x18\x03 \x01(\tB\x1a\xbaH\x17r\x15\x18 2\x11^[a-z][a-z0-9-]*$H\x00R\x05label\x12.\n" +
	"\x13expected_size_bytes\x18\x04 \x01(\x04R\x11expectedSizeBytes\x12 \n" +
	"\x06digest\x18\x05 \x01(\tB\b\xbaH\x05r\x03\x98\x01@R\x06digest\x12\x1c\n" +
	"\tprotected\x18\x06 \x01(\bR\tprotected\x12#\n" +
	"\rrelease_notes\x18\a \x01(\tR\freleaseNotesB\b\n" +
	"\x06target\"\x9f\x01\n" +
	"\x17InitiatePublishResponse\x12\x1d\n" +
	"\n" +
	"publish_id\x18\x01 \x01(\tR\tpublishId\x12\x1d\n" +
	"\n" +
	"upload_url\x18\x02 \x01(\tR\tuploadUrl\x12F\n" +
	"\x11upload_expires_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\x0fuploadExpiresAt\"@\n" +
	"\x15ConfirmPublishRequest\x12'\n" +
	"\n" +
	"publish_id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\tpublishId\"Y\n" +
	"\x16ConfirmPublishResponse\x12?\n" +
	"\x06status\x18\x01 \x01(\x0e2'.wippy.api.hub.publish.v1.PublishStatusR\x06status\"B\n" +
	"\x17GetPublishStatusRequest\x12'\n" +
	"\n" +
	"publish_id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\tpublishId\"\xa5\x01\n" +
	"\x18GetPublishStatusResponse\x12?\n" +
	"\x06status\x18\x01 \x01(\x0e2'.wippy.api.hub.publish.v1.PublishStatusR\x06status\x12H\n" +
	"\adetails\x18\x02 \x01(\v2..wippy.api.hub.publish.v1.PublishStatusDetailsR\adetails\"?\n" +
	"\x14CancelPublishRequest\x12'\n" +
	"\n" +
	"publish_id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\tpublishId\"5\n" +
	"\x15CancelPublishResponse\x12\x1c\n" +
	"\tcancelled\x18\x01 \x01(\bR\tcancelled\"\x95\x01\n" +
	"\x12YankVersionRequest\x12B\n" +
	"\x06module\x18\x01 \x01(\v2\".wippy.api.hub.module.v1.ModuleRefB\x06\xbaH\x03\xc8\x01\x01R\x06module\x12#\n" +
	"\aversion\x18\x02 \x01(\tB\t\xbaH\x06r\x04\x10\x01\x18@R\aversion\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\"R\n" +
	"\x13YankVersionResponse\x12;\n" +
	"\aversion\x18\x01 \x01(\v2!.wippy.api.hub.version.v1.VersionR\aversion2\xe3\x04\n" +
	"\x0ePublishService\x12x\n" +
	"\x0fInitiatePublish\x120.wippy.api.hub.publish.v1.InitiatePublishRequest\x1a1.wippy.api.hub.publish.v1.InitiatePublishResponse\"\x00\x12u\n" +
	"\x0eConfirmPublish\x12/.wippy.api.hub.publish.v1.ConfirmPublishRequest\x1a0.wippy.api.hub.publish.v1.ConfirmPublishResponse\"\x00\x12~\n" +
	"\x10GetPublishStatus\x121.wippy.api.hub.publish.v1.GetPublishStatusRequest\x1a2.wippy.api.hub.publish.v1.GetPublishStatusResponse\"\x03\x90\x02\x01\x12r\n" +
	"\rCancelPublish\x12..wippy.api.hub.publish.v1.CancelPublishRequest\x1a/.wippy.api.hub.publish.v1.CancelPublishResponse\"\x00\x12l\n" +
	"\vYankVersion\x12,.wippy.api.hub.publish.v1.YankVersionRequest\x1a-.wippy.api.hub.publish.v1.YankVersionResponse\"\x00B\xf8\x01\n" +
	"\x1ccom.wippy.api.hub.publish.v1B\fServiceProtoP\x01ZEgithub.com/wippyai/runtime/api/hub/wippy/api/hub/publish/v1;publishv1\xa2\x02\x04WAHP\xaa\x02\x18Wippy.Api.Hub.Publish.V1\xca\x02\x18Wippy\\Api\\Hub\\Publish\\V1\xe2\x02$Wippy\\Api\\Hub\\Publish\\V1\\GPBMetadata\xea\x02\x1cWippy::Api::Hub::Publish::V1b\x06proto3"

var (
	file_wippy_api_hub_publish_v1_service_proto_rawDescOnce sync.Once
	file_wippy_api_hub_publish_v1_service_proto_rawDescData []byte
)

func file_wippy_api_hub_publish_v1_service_proto_rawDescGZIP() []byte {
	file_wippy_api_hub_publish_v1_service_proto_rawDescOnce.Do(func() {
		file_wippy_api_hub_publish_v1_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_wippy_api_hub_publish_v1_service_proto_rawDesc), len(file_wippy_api_hub_publish_v1_service_proto_rawDesc)))
	})
	return file_wippy_api_hub_publish_v1_service_proto_rawDescData
}

var file_wippy_api_hub_publish_v1_service_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_wippy_api_hub_publish_v1_service_proto_goTypes = []any{
	(*InitiatePublishRequest)(nil),   // 0: wippy.api.hub.publish.v1.InitiatePublishRequest
	(*InitiatePublishResponse)(nil),  // 1: wippy.api.hub.publish.v1.InitiatePublishResponse
	(*ConfirmPublishRequest)(nil),    // 2: wippy.api.hub.publish.v1.ConfirmPublishRequest
	(*ConfirmPublishResponse)(nil),   // 3: wippy.api.hub.publish.v1.ConfirmPublishResponse
	(*GetPublishStatusRequest)(nil),  // 4: wippy.api.hub.publish.v1.GetPublishStatusRequest
	(*GetPublishStatusResponse)(nil), // 5: wippy.api.hub.publish.v1.GetPublishStatusResponse
	(*CancelPublishRequest)(nil),     // 6: wippy.api.hub.publish.v1.CancelPublishRequest
	(*CancelPublishResponse)(nil),    // 7: wippy.api.hub.publish.v1.CancelPublishResponse
	(*YankVersionRequest)(nil),       // 8: wippy.api.hub.publish.v1.YankVersionRequest
	(*YankVersionResponse)(nil),      // 9: wippy.api.hub.publish.v1.YankVersionResponse
	(*v1.ModuleRef)(nil),             // 10: wippy.api.hub.module.v1.ModuleRef
	(*timestamppb.Timestamp)(nil),    // 11: google.protobuf.Timestamp
	(PublishStatus)(0),               // 12: wippy.api.hub.publish.v1.PublishStatus
	(*PublishStatusDetails)(nil),     // 13: wippy.api.hub.publish.v1.PublishStatusDetails
	(*v11.Version)(nil),              // 14: wippy.api.hub.version.v1.Version
}
var file_wippy_api_hub_publish_v1_service_proto_depIdxs = []int32{
	10, // 0: wippy.api.hub.publish.v1.InitiatePublishRequest.module:type_name -> wippy.api.hub.module.v1.ModuleRef
	11, // 1: wippy.api.hub.publish.v1.InitiatePublishResponse.upload_expires_at:type_name -> google.protobuf.Timestamp
	12, // 2: wippy.api.hub.publish.v1.ConfirmPublishResponse.status:type_name -> wippy.api.hub.publish.v1.PublishStatus
	12, // 3: wippy.api.hub.publish.v1.GetPublishStatusResponse.status:type_name -> wippy.api.hub.publish.v1.PublishStatus
	13, // 4: wippy.api.hub.publish.v1.GetPublishStatusResponse.details:type_name -> wippy.api.hub.publish.v1.PublishStatusDetails
	10, // 5: wippy.api.hub.publish.v1.YankVersionRequest.module:type_name -> wippy.api.hub.module.v1.ModuleRef
	14, // 6: wippy.api.hub.publish.v1.YankVersionResponse.version:type_name -> wippy.api.hub.version.v1.Version
	0,  // 7: wippy.api.hub.publish.v1.PublishService.InitiatePublish:input_type -> wippy.api.hub.publish.v1.InitiatePublishRequest
	2,  // 8: wippy.api.hub.publish.v1.PublishService.ConfirmPublish:input_type -> wippy.api.hub.publish.v1.ConfirmPublishRequest
	4,  // 9: wippy.api.hub.publish.v1.PublishService.GetPublishStatus:input_type -> wippy.api.hub.publish.v1.GetPublishStatusRequest
	6,  // 10: wippy.api.hub.publish.v1.PublishService.CancelPublish:input_type -> wippy.api.hub.publish.v1.CancelPublishRequest
	8,  // 11: wippy.api.hub.publish.v1.PublishService.YankVersion:input_type -> wippy.api.hub.publish.v1.YankVersionRequest
	1,  // 12: wippy.api.hub.publish.v1.PublishService.InitiatePublish:output_type -> wippy.api.hub.publish.v1.InitiatePublishResponse
	3,  // 13: wippy.api.hub.publish.v1.PublishService.ConfirmPublish:output_type -> wippy.api.hub.publish.v1.ConfirmPublishResponse
	5,  // 14: wippy.api.hub.publish.v1.PublishService.GetPublishStatus:output_type -> wippy.api.hub.publish.v1.GetPublishStatusResponse
	7,  // 15: wippy.api.hub.publish.v1.PublishService.CancelPublish:output_type -> wippy.api.hub.publish.v1.CancelPublishResponse
	9,  // 16: wippy.api.hub.publish.v1.PublishService.YankVersion:output_type -> wippy.api.hub.publish.v1.YankVersionResponse
	12, // [12:17] is the sub-list for method output_type
	7,  // [7:12] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_wippy_api_hub_publish_v1_service_proto_init() }
func file_wippy_api_hub_publish_v1_service_proto_init() {
	if File_wippy_api_hub_publish_v1_service_proto != nil {
		return
	}
	file_wippy_api_hub_publish_v1_message_proto_init()
	file_wippy_api_hub_publish_v1_service_proto_msgTypes[0].OneofWrappers = []any{
		(*InitiatePublishRequest_Version)(nil),
		(*InitiatePublishRequest_Label)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_wippy_api_hub_publish_v1_service_proto_rawDesc), len(file_wippy_api_hub_publish_v1_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_wippy_api_hub_publish_v1_service_proto_goTypes,
		DependencyIndexes: file_wippy_api_hub_publish_v1_service_proto_depIdxs,
		MessageInfos:      file_wippy_api_hub_publish_v1_service_proto_msgTypes,
	}.Build()
	File_wippy_api_hub_publish_v1_service_proto = out.File
	file_wippy_api_hub_publish_v1_service_proto_goTypes = nil
	file_wippy_api_hub_publish_v1_service_proto_depIdxs = nil
}
