// SPDX-License-Identifier: MPL-2.0

// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: wippy/api/hub/label/v1/service.proto

package labelv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/wippyai/runtime/api/hub/wippy/api/hub/label/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// LabelServiceName is the fully-qualified name of the LabelService service.
	LabelServiceName = "wippy.api.hub.label.v1.LabelService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// LabelServiceSetLabelProcedure is the fully-qualified name of the LabelService's SetLabel RPC.
	LabelServiceSetLabelProcedure = "/wippy.api.hub.label.v1.LabelService/SetLabel"
	// LabelServiceDeleteLabelProcedure is the fully-qualified name of the LabelService's DeleteLabel
	// RPC.
	LabelServiceDeleteLabelProcedure = "/wippy.api.hub.label.v1.LabelService/DeleteLabel"
	// LabelServiceGetLabelProcedure is the fully-qualified name of the LabelService's GetLabel RPC.
	LabelServiceGetLabelProcedure = "/wippy.api.hub.label.v1.LabelService/GetLabel"
	// LabelServiceListLabelsProcedure is the fully-qualified name of the LabelService's ListLabels RPC.
	LabelServiceListLabelsProcedure = "/wippy.api.hub.label.v1.LabelService/ListLabels"
)

// LabelServiceClient is a client for the wippy.api.hub.label.v1.LabelService service.
type LabelServiceClient interface {
	SetLabel(context.Context, *connect.Request[v1.SetLabelRequest]) (*connect.Response[v1.SetLabelResponse], error)
	DeleteLabel(context.Context, *connect.Request[v1.DeleteLabelRequest]) (*connect.Response[v1.DeleteLabelResponse], error)
	GetLabel(context.Context, *connect.Request[v1.GetLabelRequest]) (*connect.Response[v1.GetLabelResponse], error)
	ListLabels(context.Context, *connect.Request[v1.ListLabelsRequest]) (*connect.Response[v1.ListLabelsResponse], error)
}

// NewLabelServiceClient constructs a client for the wippy.api.hub.label.v1.LabelService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewLabelServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) LabelServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	labelServiceMethods := v1.File_wippy_api_hub_label_v1_service_proto.Services().ByName("LabelService").Methods()
	return &labelServiceClient{
		setLabel: connect.NewClient[v1.SetLabelRequest, v1.SetLabelResponse](
			httpClient,
			baseURL+LabelServiceSetLabelProcedure,
			connect.WithSchema(labelServiceMethods.ByName("SetLabel")),
			connect.WithIdempotency(connect.IdempotencyIdempotent),
			connect.WithClientOptions(opts...),
		),
		deleteLabel: connect.NewClient[v1.DeleteLabelRequest, v1.DeleteLabelResponse](
			httpClient,
			baseURL+LabelServiceDeleteLabelProcedure,
			connect.WithSchema(labelServiceMethods.ByName("DeleteLabel")),
			connect.WithClientOptions(opts...),
		),
		getLabel: connect.NewClient[v1.GetLabelRequest, v1.GetLabelResponse](
			httpClient,
			baseURL+LabelServiceGetLabelProcedure,
			connect.WithSchema(labelServiceMethods.ByName("GetLabel")),
			connect.WithIdempotency(connect.IdempotencyNoSideEffects),
			connect.WithClientOptions(opts...),
		),
		listLabels: connect.NewClient[v1.ListLabelsRequest, v1.ListLabelsResponse](
			httpClient,
			baseURL+LabelServiceListLabelsProcedure,
			connect.WithSchema(labelServiceMethods.ByName("ListLabels")),
			connect.WithIdempotency(connect.IdempotencyNoSideEffects),
			connect.WithClientOptions(opts...),
		),
	}
}

// labelServiceClient implements LabelServiceClient.
type labelServiceClient struct {
	setLabel    *connect.Client[v1.SetLabelRequest, v1.SetLabelResponse]
	deleteLabel *connect.Client[v1.DeleteLabelRequest, v1.DeleteLabelResponse]
	getLabel    *connect.Client[v1.GetLabelRequest, v1.GetLabelResponse]
	listLabels  *connect.Client[v1.ListLabelsRequest, v1.ListLabelsResponse]
}

// SetLabel calls wippy.api.hub.label.v1.LabelService.SetLabel.
func (c *labelServiceClient) SetLabel(ctx context.Context, req *connect.Request[v1.SetLabelRequest]) (*connect.Response[v1.SetLabelResponse], error) {
	return c.setLabel.CallUnary(ctx, req)
}

// DeleteLabel calls wippy.api.hub.label.v1.LabelService.DeleteLabel.
func (c *labelServiceClient) DeleteLabel(ctx context.Context, req *connect.Request[v1.DeleteLabelRequest]) (*connect.Response[v1.DeleteLabelResponse], error) {
	return c.deleteLabel.CallUnary(ctx, req)
}

// GetLabel calls wippy.api.hub.label.v1.LabelService.GetLabel.
func (c *labelServiceClient) GetLabel(ctx context.Context, req *connect.Request[v1.GetLabelRequest]) (*connect.Response[v1.GetLabelResponse], error) {
	return c.getLabel.CallUnary(ctx, req)
}

// ListLabels calls wippy.api.hub.label.v1.LabelService.ListLabels.
func (c *labelServiceClient) ListLabels(ctx context.Context, req *connect.Request[v1.ListLabelsRequest]) (*connect.Response[v1.ListLabelsResponse], error) {
	return c.listLabels.CallUnary(ctx, req)
}

// LabelServiceHandler is an implementation of the wippy.api.hub.label.v1.LabelService service.
type LabelServiceHandler interface {
	SetLabel(context.Context, *connect.Request[v1.SetLabelRequest]) (*connect.Response[v1.SetLabelResponse], error)
	DeleteLabel(context.Context, *connect.Request[v1.DeleteLabelRequest]) (*connect.Response[v1.DeleteLabelResponse], error)
	GetLabel(context.Context, *connect.Request[v1.GetLabelRequest]) (*connect.Response[v1.GetLabelResponse], error)
	ListLabels(context.Context, *connect.Request[v1.ListLabelsRequest]) (*connect.Response[v1.ListLabelsResponse], error)
}

// NewLabelServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewLabelServiceHandler(svc LabelServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	labelServiceMethods := v1.File_wippy_api_hub_label_v1_service_proto.Services().ByName("LabelService").Methods()
	labelServiceSetLabelHandler := connect.NewUnaryHandler(
		LabelServiceSetLabelProcedure,
		svc.SetLabel,
		connect.WithSchema(labelServiceMethods.ByName("SetLabel")),
		connect.WithIdempotency(connect.IdempotencyIdempotent),
		connect.WithHandlerOptions(opts...),
	)
	labelServiceDeleteLabelHandler := connect.NewUnaryHandler(
		LabelServiceDeleteLabelProcedure,
		svc.DeleteLabel,
		connect.WithSchema(labelServiceMethods.ByName("DeleteLabel")),
		connect.WithHandlerOptions(opts...),
	)
	labelServiceGetLabelHandler := connect.NewUnaryHandler(
		LabelServiceGetLabelProcedure,
		svc.GetLabel,
		connect.WithSchema(labelServiceMethods.ByName("GetLabel")),
		connect.WithIdempotency(connect.IdempotencyNoSideEffects),
		connect.WithHandlerOptions(opts...),
	)
	labelServiceListLabelsHandler := connect.NewUnaryHandler(
		LabelServiceListLabelsProcedure,
		svc.ListLabels,
		connect.WithSchema(labelServiceMethods.ByName("ListLabels")),
		connect.WithIdempotency(connect.IdempotencyNoSideEffects),
		connect.WithHandlerOptions(opts...),
	)
	return "/wippy.api.hub.label.v1.LabelService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case LabelServiceSetLabelProcedure:
			labelServiceSetLabelHandler.ServeHTTP(w, r)
		case LabelServiceDeleteLabelProcedure:
			labelServiceDeleteLabelHandler.ServeHTTP(w, r)
		case LabelServiceGetLabelProcedure:
			labelServiceGetLabelHandler.ServeHTTP(w, r)
		case LabelServiceListLabelsProcedure:
			labelServiceListLabelsHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedLabelServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedLabelServiceHandler struct{}

func (UnimplementedLabelServiceHandler) SetLabel(context.Context, *connect.Request[v1.SetLabelRequest]) (*connect.Response[v1.SetLabelResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("wippy.api.hub.label.v1.LabelService.SetLabel is not implemented"))
}

func (UnimplementedLabelServiceHandler) DeleteLabel(context.Context, *connect.Request[v1.DeleteLabelRequest]) (*connect.Response[v1.DeleteLabelResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("wippy.api.hub.label.v1.LabelService.DeleteLabel is not implemented"))
}

func (UnimplementedLabelServiceHandler) GetLabel(context.Context, *connect.Request[v1.GetLabelRequest]) (*connect.Response[v1.GetLabelResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("wippy.api.hub.label.v1.LabelService.GetLabel is not implemented"))
}

func (UnimplementedLabelServiceHandler) ListLabels(context.Context, *connect.Request[v1.ListLabelsRequest]) (*connect.Response[v1.ListLabelsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("wippy.api.hub.label.v1.LabelService.ListLabels is not implemented"))
}
