// SPDX-License-Identifier: MPL-2.0

// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: wippy/api/hub/manifest/v1/service.proto

package manifestv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/wippyai/runtime/api/hub/wippy/api/hub/manifest/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// ManifestServiceName is the fully-qualified name of the ManifestService service.
	ManifestServiceName = "wippy.api.hub.manifest.v1.ManifestService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// ManifestServiceGetManifestProcedure is the fully-qualified name of the ManifestService's
	// GetManifest RPC.
	ManifestServiceGetManifestProcedure = "/wippy.api.hub.manifest.v1.ManifestService/GetManifest"
	// ManifestServiceResolveDependenciesProcedure is the fully-qualified name of the ManifestService's
	// ResolveDependencies RPC.
	ManifestServiceResolveDependenciesProcedure = "/wippy.api.hub.manifest.v1.ManifestService/ResolveDependencies"
	// ManifestServiceCheckUpdatesProcedure is the fully-qualified name of the ManifestService's
	// CheckUpdates RPC.
	ManifestServiceCheckUpdatesProcedure = "/wippy.api.hub.manifest.v1.ManifestService/CheckUpdates"
)

// ManifestServiceClient is a client for the wippy.api.hub.manifest.v1.ManifestService service.
type ManifestServiceClient interface {
	GetManifest(context.Context, *connect.Request[v1.GetManifestRequest]) (*connect.Response[v1.GetManifestResponse], error)
	ResolveDependencies(context.Context, *connect.Request[v1.ResolveDependenciesRequest]) (*connect.Response[v1.ResolveDependenciesResponse], error)
	CheckUpdates(context.Context, *connect.Request[v1.CheckUpdatesRequest]) (*connect.Response[v1.CheckUpdatesResponse], error)
}

// NewManifestServiceClient constructs a client for the wippy.api.hub.manifest.v1.ManifestService
// service. By default, it uses the Connect protocol with the binary Protobuf Codec, asks for
// gzipped responses, and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply
// the connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewManifestServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) ManifestServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	manifestServiceMethods := v1.File_wippy_api_hub_manifest_v1_service_proto.Services().ByName("ManifestService").Methods()
	return &manifestServiceClient{
		getManifest: connect.NewClient[v1.GetManifestRequest, v1.GetManifestResponse](
			httpClient,
			baseURL+ManifestServiceGetManifestProcedure,
			connect.WithSchema(manifestServiceMethods.ByName("GetManifest")),
			connect.WithIdempotency(connect.IdempotencyNoSideEffects),
			connect.WithClientOptions(opts...),
		),
		resolveDependencies: connect.NewClient[v1.ResolveDependenciesRequest, v1.ResolveDependenciesResponse](
			httpClient,
			baseURL+ManifestServiceResolveDependenciesProcedure,
			connect.WithSchema(manifestServiceMethods.ByName("ResolveDependencies")),
			connect.WithIdempotency(connect.IdempotencyNoSideEffects),
			connect.WithClientOptions(opts...),
		),
		checkUpdates: connect.NewClient[v1.CheckUpdatesRequest, v1.CheckUpdatesResponse](
			httpClient,
			baseURL+ManifestServiceCheckUpdatesProcedure,
			connect.WithSchema(manifestServiceMethods.ByName("CheckUpdates")),
			connect.WithIdempotency(connect.IdempotencyNoSideEffects),
			connect.WithClientOptions(opts...),
		),
	}
}

// manifestServiceClient implements ManifestServiceClient.
type manifestServiceClient struct {
	getManifest         *connect.Client[v1.GetManifestRequest, v1.GetManifestResponse]
	resolveDependencies *connect.Client[v1.ResolveDependenciesRequest, v1.ResolveDependenciesResponse]
	checkUpdates        *connect.Client[v1.CheckUpdatesRequest, v1.CheckUpdatesResponse]
}

// GetManifest calls wippy.api.hub.manifest.v1.ManifestService.GetManifest.
func (c *manifestServiceClient) GetManifest(ctx context.Context, req *connect.Request[v1.GetManifestRequest]) (*connect.Response[v1.GetManifestResponse], error) {
	return c.getManifest.CallUnary(ctx, req)
}

// ResolveDependencies calls wippy.api.hub.manifest.v1.ManifestService.ResolveDependencies.
func (c *manifestServiceClient) ResolveDependencies(ctx context.Context, req *connect.Request[v1.ResolveDependenciesRequest]) (*connect.Response[v1.ResolveDependenciesResponse], error) {
	return c.resolveDependencies.CallUnary(ctx, req)
}

// CheckUpdates calls wippy.api.hub.manifest.v1.ManifestService.CheckUpdates.
func (c *manifestServiceClient) CheckUpdates(ctx context.Context, req *connect.Request[v1.CheckUpdatesRequest]) (*connect.Response[v1.CheckUpdatesResponse], error) {
	return c.checkUpdates.CallUnary(ctx, req)
}

// ManifestServiceHandler is an implementation of the wippy.api.hub.manifest.v1.ManifestService
// service.
type ManifestServiceHandler interface {
	GetManifest(context.Context, *connect.Request[v1.GetManifestRequest]) (*connect.Response[v1.GetManifestResponse], error)
	ResolveDependencies(context.Context, *connect.Request[v1.ResolveDependenciesRequest]) (*connect.Response[v1.ResolveDependenciesResponse], error)
	CheckUpdates(context.Context, *connect.Request[v1.CheckUpdatesRequest]) (*connect.Response[v1.CheckUpdatesResponse], error)
}

// NewManifestServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewManifestServiceHandler(svc ManifestServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	manifestServiceMethods := v1.File_wippy_api_hub_manifest_v1_service_proto.Services().ByName("ManifestService").Methods()
	manifestServiceGetManifestHandler := connect.NewUnaryHandler(
		ManifestServiceGetManifestProcedure,
		svc.GetManifest,
		connect.WithSchema(manifestServiceMethods.ByName("GetManifest")),
		connect.WithIdempotency(connect.IdempotencyNoSideEffects),
		connect.WithHandlerOptions(opts...),
	)
	manifestServiceResolveDependenciesHandler := connect.NewUnaryHandler(
		ManifestServiceResolveDependenciesProcedure,
		svc.ResolveDependencies,
		connect.WithSchema(manifestServiceMethods.ByName("ResolveDependencies")),
		connect.WithIdempotency(connect.IdempotencyNoSideEffects),
		connect.WithHandlerOptions(opts...),
	)
	manifestServiceCheckUpdatesHandler := connect.NewUnaryHandler(
		ManifestServiceCheckUpdatesProcedure,
		svc.CheckUpdates,
		connect.WithSchema(manifestServiceMethods.ByName("CheckUpdates")),
		connect.WithIdempotency(connect.IdempotencyNoSideEffects),
		connect.WithHandlerOptions(opts...),
	)
	return "/wippy.api.hub.manifest.v1.ManifestService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case ManifestServiceGetManifestProcedure:
			manifestServiceGetManifestHandler.ServeHTTP(w, r)
		case ManifestServiceResolveDependenciesProcedure:
			manifestServiceResolveDependenciesHandler.ServeHTTP(w, r)
		case ManifestServiceCheckUpdatesProcedure:
			manifestServiceCheckUpdatesHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedManifestServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedManifestServiceHandler struct{}

func (UnimplementedManifestServiceHandler) GetManifest(context.Context, *connect.Request[v1.GetManifestRequest]) (*connect.Response[v1.GetManifestResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("wippy.api.hub.manifest.v1.ManifestService.GetManifest is not implemented"))
}

func (UnimplementedManifestServiceHandler) ResolveDependencies(context.Context, *connect.Request[v1.ResolveDependenciesRequest]) (*connect.Response[v1.ResolveDependenciesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("wippy.api.hub.manifest.v1.ManifestService.ResolveDependencies is not implemented"))
}

func (UnimplementedManifestServiceHandler) CheckUpdates(context.Context, *connect.Request[v1.CheckUpdatesRequest]) (*connect.Response[v1.CheckUpdatesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("wippy.api.hub.manifest.v1.ManifestService.CheckUpdates is not implemented"))
}
