// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: api/registry/history/v1/history.proto

package historyv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	HistoryService_Head_FullMethodName                 = "/wippy.registry.history.v1.HistoryService/Head"
	HistoryService_GetVersion_FullMethodName           = "/wippy.registry.history.v1.HistoryService/GetVersion"
	HistoryService_GetMaxVersionID_FullMethodName      = "/wippy.registry.history.v1.HistoryService/GetMaxVersionID"
	HistoryService_ListVersions_FullMethodName         = "/wippy.registry.history.v1.HistoryService/ListVersions"
	HistoryService_GetChangeSet_FullMethodName         = "/wippy.registry.history.v1.HistoryService/GetChangeSet"
	HistoryService_ReplayChanges_FullMethodName        = "/wippy.registry.history.v1.HistoryService/ReplayChanges"
	HistoryService_Save_FullMethodName                 = "/wippy.registry.history.v1.HistoryService/Save"
	HistoryService_SetHead_FullMethodName              = "/wippy.registry.history.v1.HistoryService/SetHead"
	HistoryService_CompareAndSetHead_FullMethodName    = "/wippy.registry.history.v1.HistoryService/CompareAndSetHead"
	HistoryService_GetResolution_FullMethodName        = "/wippy.registry.history.v1.HistoryService/GetResolution"
	HistoryService_CheckpointResolution_FullMethodName = "/wippy.registry.history.v1.HistoryService/CheckpointResolution"
	HistoryService_GetBaseline_FullMethodName          = "/wippy.registry.history.v1.HistoryService/GetBaseline"
	HistoryService_SetBaseline_FullMethodName          = "/wippy.registry.history.v1.HistoryService/SetBaseline"
	HistoryService_BeginTransfer_FullMethodName        = "/wippy.registry.history.v1.HistoryService/BeginTransfer"
	HistoryService_TransferVersions_FullMethodName     = "/wippy.registry.history.v1.HistoryService/TransferVersions"
	HistoryService_CompleteTransfer_FullMethodName     = "/wippy.registry.history.v1.HistoryService/CompleteTransfer"
)

// HistoryServiceClient is the client API for HistoryService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type HistoryServiceClient interface {
	Head(ctx context.Context, in *RegistryRequest, opts ...grpc.CallOption) (*Lineage, error)
	GetVersion(ctx context.Context, in *VersionRequest, opts ...grpc.CallOption) (*Lineage, error)
	GetMaxVersionID(ctx context.Context, in *RegistryRequest, opts ...grpc.CallOption) (*MaxVersionID, error)
	ListVersions(ctx context.Context, in *ListVersionsRequest, opts ...grpc.CallOption) (*VersionList, error)
	GetChangeSet(ctx context.Context, in *VersionRequest, opts ...grpc.CallOption) (*ChangeSet, error)
	ReplayChanges(ctx context.Context, in *VersionRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ChangeSet], error)
	Save(ctx context.Context, in *SaveRequest, opts ...grpc.CallOption) (*Empty, error)
	SetHead(ctx context.Context, in *SetHeadRequest, opts ...grpc.CallOption) (*Empty, error)
	CompareAndSetHead(ctx context.Context, in *CompareAndSetHeadRequest, opts ...grpc.CallOption) (*Empty, error)
	GetResolution(ctx context.Context, in *VersionRequest, opts ...grpc.CallOption) (*Resolution, error)
	CheckpointResolution(ctx context.Context, in *CheckpointResolutionRequest, opts ...grpc.CallOption) (*Empty, error)
	GetBaseline(ctx context.Context, in *RegistryRequest, opts ...grpc.CallOption) (*Baseline, error)
	SetBaseline(ctx context.Context, in *SetBaselineRequest, opts ...grpc.CallOption) (*Empty, error)
	BeginTransfer(ctx context.Context, in *BeginTransferRequest, opts ...grpc.CallOption) (*TransferStatus, error)
	TransferVersions(ctx context.Context, in *TransferVersionsRequest, opts ...grpc.CallOption) (*Empty, error)
	CompleteTransfer(ctx context.Context, in *CompleteTransferRequest, opts ...grpc.CallOption) (*TransferStatus, error)
}

type historyServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewHistoryServiceClient(cc grpc.ClientConnInterface) HistoryServiceClient {
	return &historyServiceClient{cc}
}

func (c *historyServiceClient) Head(ctx context.Context, in *RegistryRequest, opts ...grpc.CallOption) (*Lineage, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Lineage)
	err := c.cc.Invoke(ctx, HistoryService_Head_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *historyServiceClient) GetVersion(ctx context.Context, in *VersionRequest, opts ...grpc.CallOption) (*Lineage, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Lineage)
	err := c.cc.Invoke(ctx, HistoryService_GetVersion_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *historyServiceClient) GetMaxVersionID(ctx context.Context, in *RegistryRequest, opts ...grpc.CallOption) (*MaxVersionID, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MaxVersionID)
	err := c.cc.Invoke(ctx, HistoryService_GetMaxVersionID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *historyServiceClient) ListVersions(ctx context.Context, in *ListVersionsRequest, opts ...grpc.CallOption) (*VersionList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VersionList)
	err := c.cc.Invoke(ctx, HistoryService_ListVersions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *historyServiceClient) GetChangeSet(ctx context.Context, in *VersionRequest, opts ...grpc.CallOption) (*ChangeSet, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ChangeSet)
	err := c.cc.Invoke(ctx, HistoryService_GetChangeSet_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *historyServiceClient) ReplayChanges(ctx context.Context, in *VersionRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ChangeSet], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &HistoryService_ServiceDesc.Streams[0], HistoryService_ReplayChanges_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[VersionRequest, ChangeSet]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type HistoryService_ReplayChangesClient = grpc.ServerStreamingClient[ChangeSet]

func (c *historyServiceClient) Save(ctx context.Context, in *SaveRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, HistoryService_Save_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *historyServiceClient) SetHead(ctx context.Context, in *SetHeadRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, HistoryService_SetHead_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *historyServiceClient) CompareAndSetHead(ctx context.Context, in *CompareAndSetHeadRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, HistoryService_CompareAndSetHead_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *historyServiceClient) GetResolution(ctx context.Context, in *VersionRequest, opts ...grpc.CallOption) (*Resolution, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Resolution)
	err := c.cc.Invoke(ctx, HistoryService_GetResolution_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *historyServiceClient) CheckpointResolution(ctx context.Context, in *CheckpointResolutionRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, HistoryService_CheckpointResolution_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *historyServiceClient) GetBaseline(ctx context.Context, in *RegistryRequest, opts ...grpc.CallOption) (*Baseline, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Baseline)
	err := c.cc.Invoke(ctx, HistoryService_GetBaseline_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *historyServiceClient) SetBaseline(ctx context.Context, in *SetBaselineRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, HistoryService_SetBaseline_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *historyServiceClient) BeginTransfer(ctx context.Context, in *BeginTransferRequest, opts ...grpc.CallOption) (*TransferStatus, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TransferStatus)
	err := c.cc.Invoke(ctx, HistoryService_BeginTransfer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *historyServiceClient) TransferVersions(ctx context.Context, in *TransferVersionsRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, HistoryService_TransferVersions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *historyServiceClient) CompleteTransfer(ctx context.Context, in *CompleteTransferRequest, opts ...grpc.CallOption) (*TransferStatus, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TransferStatus)
	err := c.cc.Invoke(ctx, HistoryService_CompleteTransfer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HistoryServiceServer is the server API for HistoryService service.
// All implementations must embed UnimplementedHistoryServiceServer
// for forward compatibility.
type HistoryServiceServer interface {
	Head(context.Context, *RegistryRequest) (*Lineage, error)
	GetVersion(context.Context, *VersionRequest) (*Lineage, error)
	GetMaxVersionID(context.Context, *RegistryRequest) (*MaxVersionID, error)
	ListVersions(context.Context, *ListVersionsRequest) (*VersionList, error)
	GetChangeSet(context.Context, *VersionRequest) (*ChangeSet, error)
	ReplayChanges(*VersionRequest, grpc.ServerStreamingServer[ChangeSet]) error
	Save(context.Context, *SaveRequest) (*Empty, error)
	SetHead(context.Context, *SetHeadRequest) (*Empty, error)
	CompareAndSetHead(context.Context, *CompareAndSetHeadRequest) (*Empty, error)
	GetResolution(context.Context, *VersionRequest) (*Resolution, error)
	CheckpointResolution(context.Context, *CheckpointResolutionRequest) (*Empty, error)
	GetBaseline(context.Context, *RegistryRequest) (*Baseline, error)
	SetBaseline(context.Context, *SetBaselineRequest) (*Empty, error)
	BeginTransfer(context.Context, *BeginTransferRequest) (*TransferStatus, error)
	TransferVersions(context.Context, *TransferVersionsRequest) (*Empty, error)
	CompleteTransfer(context.Context, *CompleteTransferRequest) (*TransferStatus, error)
	mustEmbedUnimplementedHistoryServiceServer()
}

// UnimplementedHistoryServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedHistoryServiceServer struct{}

func (UnimplementedHistoryServiceServer) Head(context.Context, *RegistryRequest) (*Lineage, error) {
	return nil, status.Error(codes.Unimplemented, "method Head not implemented")
}
func (UnimplementedHistoryServiceServer) GetVersion(context.Context, *VersionRequest) (*Lineage, error) {
	return nil, status.Error(codes.Unimplemented, "method GetVersion not implemented")
}
func (UnimplementedHistoryServiceServer) GetMaxVersionID(context.Context, *RegistryRequest) (*MaxVersionID, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMaxVersionID not implemented")
}
func (UnimplementedHistoryServiceServer) ListVersions(context.Context, *ListVersionsRequest) (*VersionList, error) {
	return nil, status.Error(codes.Unimplemented, "method ListVersions not implemented")
}
func (UnimplementedHistoryServiceServer) GetChangeSet(context.Context, *VersionRequest) (*ChangeSet, error) {
	return nil, status.Error(codes.Unimplemented, "method GetChangeSet not implemented")
}
func (UnimplementedHistoryServiceServer) ReplayChanges(*VersionRequest, grpc.ServerStreamingServer[ChangeSet]) error {
	return status.Error(codes.Unimplemented, "method ReplayChanges not implemented")
}
func (UnimplementedHistoryServiceServer) Save(context.Context, *SaveRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method Save not implemented")
}
func (UnimplementedHistoryServiceServer) SetHead(context.Context, *SetHeadRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method SetHead not implemented")
}
func (UnimplementedHistoryServiceServer) CompareAndSetHead(context.Context, *CompareAndSetHeadRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method CompareAndSetHead not implemented")
}
func (UnimplementedHistoryServiceServer) GetResolution(context.Context, *VersionRequest) (*Resolution, error) {
	return nil, status.Error(codes.Unimplemented, "method GetResolution not implemented")
}
func (UnimplementedHistoryServiceServer) CheckpointResolution(context.Context, *CheckpointResolutionRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method CheckpointResolution not implemented")
}
func (UnimplementedHistoryServiceServer) GetBaseline(context.Context, *RegistryRequest) (*Baseline, error) {
	return nil, status.Error(codes.Unimplemented, "method GetBaseline not implemented")
}
func (UnimplementedHistoryServiceServer) SetBaseline(context.Context, *SetBaselineRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method SetBaseline not implemented")
}
func (UnimplementedHistoryServiceServer) BeginTransfer(context.Context, *BeginTransferRequest) (*TransferStatus, error) {
	return nil, status.Error(codes.Unimplemented, "method BeginTransfer not implemented")
}
func (UnimplementedHistoryServiceServer) TransferVersions(context.Context, *TransferVersionsRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method TransferVersions not implemented")
}
func (UnimplementedHistoryServiceServer) CompleteTransfer(context.Context, *CompleteTransferRequest) (*TransferStatus, error) {
	return nil, status.Error(codes.Unimplemented, "method CompleteTransfer not implemented")
}
func (UnimplementedHistoryServiceServer) mustEmbedUnimplementedHistoryServiceServer() {}
func (UnimplementedHistoryServiceServer) testEmbeddedByValue()                        {}

// UnsafeHistoryServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HistoryServiceServer will
// result in compilation errors.
type UnsafeHistoryServiceServer interface {
	mustEmbedUnimplementedHistoryServiceServer()
}

func RegisterHistoryServiceServer(s grpc.ServiceRegistrar, srv HistoryServiceServer) {
	// If the following call panics, it indicates UnimplementedHistoryServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&HistoryService_ServiceDesc, srv)
}

func _HistoryService_Head_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegistryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HistoryServiceServer).Head(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HistoryService_Head_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HistoryServiceServer).Head(ctx, req.(*RegistryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HistoryService_GetVersion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VersionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HistoryServiceServer).GetVersion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HistoryService_GetVersion_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HistoryServiceServer).GetVersion(ctx, req.(*VersionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HistoryService_GetMaxVersionID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegistryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HistoryServiceServer).GetMaxVersionID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HistoryService_GetMaxVersionID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HistoryServiceServer).GetMaxVersionID(ctx, req.(*RegistryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HistoryService_ListVersions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListVersionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HistoryServiceServer).ListVersions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HistoryService_ListVersions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HistoryServiceServer).ListVersions(ctx, req.(*ListVersionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HistoryService_GetChangeSet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VersionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HistoryServiceServer).GetChangeSet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HistoryService_GetChangeSet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HistoryServiceServer).GetChangeSet(ctx, req.(*VersionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HistoryService_ReplayChanges_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(VersionRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(HistoryServiceServer).ReplayChanges(m, &grpc.GenericServerStream[VersionRequest, ChangeSet]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type HistoryService_ReplayChangesServer = grpc.ServerStreamingServer[ChangeSet]

func _HistoryService_Save_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HistoryServiceServer).Save(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HistoryService_Save_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HistoryServiceServer).Save(ctx, req.(*SaveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HistoryService_SetHead_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetHeadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HistoryServiceServer).SetHead(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HistoryService_SetHead_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HistoryServiceServer).SetHead(ctx, req.(*SetHeadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HistoryService_CompareAndSetHead_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CompareAndSetHeadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HistoryServiceServer).CompareAndSetHead(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HistoryService_CompareAndSetHead_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HistoryServiceServer).CompareAndSetHead(ctx, req.(*CompareAndSetHeadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HistoryService_GetResolution_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VersionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HistoryServiceServer).GetResolution(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HistoryService_GetResolution_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HistoryServiceServer).GetResolution(ctx, req.(*VersionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HistoryService_CheckpointResolution_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckpointResolutionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HistoryServiceServer).CheckpointResolution(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HistoryService_CheckpointResolution_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HistoryServiceServer).CheckpointResolution(ctx, req.(*CheckpointResolutionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HistoryService_GetBaseline_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegistryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HistoryServiceServer).GetBaseline(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HistoryService_GetBaseline_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HistoryServiceServer).GetBaseline(ctx, req.(*RegistryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HistoryService_SetBaseline_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetBaselineRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HistoryServiceServer).SetBaseline(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HistoryService_SetBaseline_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HistoryServiceServer).SetBaseline(ctx, req.(*SetBaselineRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HistoryService_BeginTransfer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BeginTransferRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HistoryServiceServer).BeginTransfer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HistoryService_BeginTransfer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HistoryServiceServer).BeginTransfer(ctx, req.(*BeginTransferRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HistoryService_TransferVersions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TransferVersionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HistoryServiceServer).TransferVersions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HistoryService_TransferVersions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HistoryServiceServer).TransferVersions(ctx, req.(*TransferVersionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HistoryService_CompleteTransfer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CompleteTransferRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HistoryServiceServer).CompleteTransfer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HistoryService_CompleteTransfer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HistoryServiceServer).CompleteTransfer(ctx, req.(*CompleteTransferRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// HistoryService_ServiceDesc is the grpc.ServiceDesc for HistoryService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var HistoryService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "wippy.registry.history.v1.HistoryService",
	HandlerType: (*HistoryServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Head",
			Handler:    _HistoryService_Head_Handler,
		},
		{
			MethodName: "GetVersion",
			Handler:    _HistoryService_GetVersion_Handler,
		},
		{
			MethodName: "GetMaxVersionID",
			Handler:    _HistoryService_GetMaxVersionID_Handler,
		},
		{
			MethodName: "ListVersions",
			Handler:    _HistoryService_ListVersions_Handler,
		},
		{
			MethodName: "GetChangeSet",
			Handler:    _HistoryService_GetChangeSet_Handler,
		},
		{
			MethodName: "Save",
			Handler:    _HistoryService_Save_Handler,
		},
		{
			MethodName: "SetHead",
			Handler:    _HistoryService_SetHead_Handler,
		},
		{
			MethodName: "CompareAndSetHead",
			Handler:    _HistoryService_CompareAndSetHead_Handler,
		},
		{
			MethodName: "GetResolution",
			Handler:    _HistoryService_GetResolution_Handler,
		},
		{
			MethodName: "CheckpointResolution",
			Handler:    _HistoryService_CheckpointResolution_Handler,
		},
		{
			MethodName: "GetBaseline",
			Handler:    _HistoryService_GetBaseline_Handler,
		},
		{
			MethodName: "SetBaseline",
			Handler:    _HistoryService_SetBaseline_Handler,
		},
		{
			MethodName: "BeginTransfer",
			Handler:    _HistoryService_BeginTransfer_Handler,
		},
		{
			MethodName: "TransferVersions",
			Handler:    _HistoryService_TransferVersions_Handler,
		},
		{
			MethodName: "CompleteTransfer",
			Handler:    _HistoryService_CompleteTransfer_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ReplayChanges",
			Handler:       _HistoryService_ReplayChanges_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "api/registry/history/v1/history.proto",
}
