// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: api/registry/history/v1/history.proto

package historyv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RegistryKey struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	EnvironmentId string                 `protobuf:"bytes,2,opt,name=environment_id,json=environmentId,proto3" json:"environment_id,omitempty"`
	RegistryId    string                 `protobuf:"bytes,3,opt,name=registry_id,json=registryId,proto3" json:"registry_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegistryKey) Reset() {
	*x = RegistryKey{}
	mi := &file_api_registry_history_v1_history_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegistryKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegistryKey) ProtoMessage() {}

func (x *RegistryKey) ProtoReflect() protoreflect.Message {
	mi := &file_api_registry_history_v1_history_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegistryKey.ProtoReflect.Descriptor instead.
func (*RegistryKey) Descriptor() ([]byte, []int) {
	return file_api_registry_history_v1_history_proto_rawDescGZIP(), []int{0}
}

func (x *RegistryKey) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *RegistryKey) GetEnvironmentId() string {
	if x != nil {
		return x.EnvironmentId
	}
	return ""
}

func (x *RegistryKey) GetRegistryId() string {
	if x != nil {
		return x.RegistryId
	}
	return ""
}

type RegistryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           *RegistryKey           `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegistryRequest) Reset() {
	*x = RegistryRequest{}
	mi := &file_api_registry_history_v1_history_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegistryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegistryRequest) ProtoMessage() {}

func (x *RegistryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_registry_history_v1_history_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegistryRequest.ProtoReflect.Descriptor instead.
func (*RegistryRequest) Descriptor() ([]byte, []int) {
	return file_api_registry_history_v1_history_proto_rawDescGZIP(), []int{1}
}

func (x *RegistryRequest) GetKey() *RegistryKey {
	if x != nil {
		return x.Key
	}
	return nil
}

type VersionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           *RegistryKey           `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	VersionId     uint64                 `protobuf:"varint,2,opt,name=version_id,json=versionId,proto3" json:"version_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VersionRequest) Reset() {
	*x = VersionRequest{}
	mi := &file_api_registry_history_v1_history_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VersionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VersionRequest) ProtoMessage() {}

func (x *VersionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_registry_history_v1_history_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VersionRequest.ProtoReflect.Descriptor instead.
func (*VersionRequest) Descriptor() ([]byte, []int) {
	return file_api_registry_history_v1_history_proto_rawDescGZIP(), []int{2}
}

func (x *VersionRequest) GetKey() *RegistryKey {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *VersionRequest) GetVersionId() uint64 {
	if x != nil {
		return x.VersionId
	}
	return 0
}

// Lineage lists version IDs from the first child of the root to the target.
// An empty list is the root version.
type Lineage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ids           []uint64               `protobuf:"varint,1,rep,packed,name=ids,proto3" json:"ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Lineage) Reset() {
	*x = Lineage{}
	mi := &file_api_registry_history_v1_history_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Lineage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Lineage) ProtoMessage() {}

func (x *Lineage) ProtoReflect() protoreflect.Message {
	mi := &file_api_registry_history_v1_history_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Lineage.ProtoReflect.Descriptor instead.
func (*Lineage) Descriptor() ([]byte, []int) {
	return file_api_registry_history_v1_history_proto_rawDescGZIP(), []int{3}
}

func (x *Lineage) GetIds() []uint64 {
	if x != nil {
		return x.Ids
	}
	return nil
}

type MaxVersionID struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VersionId     uint64                 `protobuf:"varint,1,opt,name=version_id,json=versionId,proto3" json:"version_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MaxVersionID) Reset() {
	*x = MaxVersionID{}
	mi := &file_api_registry_history_v1_history_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MaxVersionID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MaxVersionID) ProtoMessage() {}

func (x *MaxVersionID) ProtoReflect() protoreflect.Message {
	mi := &file_api_registry_history_v1_history_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MaxVersionID.ProtoReflect.Descriptor instead.
func (*MaxVersionID) Descriptor() ([]byte, []int) {
	return file_api_registry_history_v1_history_proto_rawDescGZIP(), []int{4}
}

func (x *MaxVersionID) GetVersionId() uint64 {
	if x != nil {
		return x.VersionId
	}
	return 0
}

type ListVersionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           *RegistryKey           `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	AfterId       *uint64                `protobuf:"varint,2,opt,name=after_id,json=afterId,proto3,oneof" json:"after_id,omitempty"`
	Limit         uint32                 `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListVersionsRequest) Reset() {
	*x = ListVersionsRequest{}
	mi := &file_api_registry_history_v1_history_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListVersionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListVersionsRequest) ProtoMessage() {}

func (x *ListVersionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_registry_history_v1_history_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListVersionsRequest.ProtoReflect.Descriptor instead.
func (*ListVersionsRequest) Descriptor() ([]byte, []int) {
	return file_api_registry_history_v1_history_proto_rawDescGZIP(), []int{5}
}

func (x *ListVersionsRequest) GetKey() *RegistryKey {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *ListVersionsRequest) GetAfterId() uint64 {
	if x != nil && x.AfterId != nil {
		return *x.AfterId
	}
	return 0
}

func (x *ListVersionsRequest) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type VersionNode struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ParentId      *uint64                `protobuf:"varint,2,opt,name=parent_id,json=parentId,proto3,oneof" json:"parent_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VersionNode) Reset() {
	*x = VersionNode{}
	mi := &file_api_registry_history_v1_history_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VersionNode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VersionNode) ProtoMessage() {}

func (x *VersionNode) ProtoReflect() protoreflect.Message {
	mi := &file_api_registry_history_v1_history_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VersionNode.ProtoReflect.Descriptor instead.
func (*VersionNode) Descriptor() ([]byte, []int) {
	return file_api_registry_history_v1_history_proto_rawDescGZIP(), []int{6}
}

func (x *VersionNode) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *VersionNode) GetParentId() uint64 {
	if x != nil && x.ParentId != nil {
		return *x.ParentId
	}
	return 0
}

type VersionList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Versions      []*VersionNode         `protobuf:"bytes,1,rep,name=versions,proto3" json:"versions,omitempty"`
	HasMore       bool                   `protobuf:"varint,2,opt,name=has_more,json=hasMore,proto3" json:"has_more,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VersionList) Reset() {
	*x = VersionList{}
	mi := &file_api_registry_history_v1_history_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VersionList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VersionList) ProtoMessage() {}

func (x *VersionList) ProtoReflect() protoreflect.Message {
	mi := &file_api_registry_history_v1_history_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VersionList.ProtoReflect.Descriptor instead.
func (*VersionList) Descriptor() ([]byte, []int) {
	return file_api_registry_history_v1_history_proto_rawDescGZIP(), []int{7}
}

func (x *VersionList) GetVersions() []*VersionNode {
	if x != nil {
		return x.Versions
	}
	return nil
}

func (x *VersionList) GetHasMore() bool {
	if x != nil {
		return x.HasMore
	}
	return false
}

type ChangeSet struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VersionId     uint64                 `protobuf:"varint,1,opt,name=version_id,json=versionId,proto3" json:"version_id,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChangeSet) Reset() {
	*x = ChangeSet{}
	mi := &file_api_registry_history_v1_history_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangeSet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeSet) ProtoMessage() {}

func (x *ChangeSet) ProtoReflect() protoreflect.Message {
	mi := &file_api_registry_history_v1_history_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeSet.ProtoReflect.Descriptor instead.
func (*ChangeSet) Descriptor() ([]byte, []int) {
	return file_api_registry_history_v1_history_proto_rawDescGZIP(), []int{8}
}

func (x *ChangeSet) GetVersionId() uint64 {
	if x != nil {
		return x.VersionId
	}
	return 0
}

func (x *ChangeSet) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// Save and CompareAndSetHead set retry only when they resend a request whose
// result is unknown. The service then accepts a request that is already applied.
type SaveRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           *RegistryKey           `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	VersionId     uint64                 `protobuf:"varint,2,opt,name=version_id,json=versionId,proto3" json:"version_id,omitempty"`
	ParentId      uint64                 `protobuf:"varint,3,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	Changeset     []byte                 `protobuf:"bytes,4,opt,name=changeset,proto3" json:"changeset,omitempty"`
	Resolution    []byte                 `protobuf:"bytes,5,opt,name=resolution,proto3" json:"resolution,omitempty"`
	Head          bool                   `protobuf:"varint,6,opt,name=head,proto3" json:"head,omitempty"`
	Retry         bool                   `protobuf:"varint,7,opt,name=retry,proto3" json:"retry,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveRequest) Reset() {
	*x = SaveRequest{}
	mi := &file_api_registry_history_v1_history_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveRequest) ProtoMessage() {}

func (x *SaveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_registry_history_v1_history_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveRequest.ProtoReflect.Descriptor instead.
func (*SaveRequest) Descriptor() ([]byte, []int) {
	return file_api_registry_history_v1_history_proto_rawDescGZIP(), []int{9}
}

func (x *SaveRequest) GetKey() *RegistryKey {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *SaveRequest) GetVersionId() uint64 {
	if x != nil {
		return x.VersionId
	}
	return 0
}

func (x *SaveRequest) GetParentId() uint64 {
	if x != nil {
		return x.ParentId
	}
	return 0
}

func (x *SaveRequest) GetChangeset() []byte {
	if x != nil {
		return x.Changeset
	}
	return nil
}

func (x *SaveRequest) GetResolution() []byte {
	if x != nil {
		return x.Resolution
	}
	return nil
}

func (x *SaveRequest) GetHead() bool {
	if x != nil {
		return x.Head
	}
	return false
}

func (x *SaveRequest) GetRetry() bool {
	if x != nil {
		return x.Retry
	}
	return false
}

type SetHeadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           *RegistryKey           `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	VersionId     uint64                 `protobuf:"varint,2,opt,name=version_id,json=versionId,proto3" json:"version_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetHeadRequest) Reset() {
	*x = SetHeadRequest{}
	mi := &file_api_registry_history_v1_history_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetHeadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetHeadRequest) ProtoMessage() {}

func (x *SetHeadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_registry_history_v1_history_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetHeadRequest.ProtoReflect.Descriptor instead.
func (*SetHeadRequest) Descriptor() ([]byte, []int) {
	return file_api_registry_history_v1_history_proto_rawDescGZIP(), []int{10}
}

func (x *SetHeadRequest) GetKey() *RegistryKey {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *SetHeadRequest) GetVersionId() uint64 {
	if x != nil {
		return x.VersionId
	}
	return 0
}

type CompareAndSetHeadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           *RegistryKey           `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	ExpectedId    uint64                 `protobuf:"varint,2,opt,name=expected_id,json=expectedId,proto3" json:"expected_id,omitempty"`
	TargetId      uint64                 `protobuf:"varint,3,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`
	Resolution    []byte                 `protobuf:"bytes,4,opt,name=resolution,proto3" json:"resolution,omitempty"`
	Retry         bool                   `protobuf:"varint,5,opt,name=retry,proto3" json:"retry,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompareAndSetHeadRequest) Reset() {
	*x = CompareAndSetHeadRequest{}
	mi := &file_api_registry_history_v1_history_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompareAndSetHeadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompareAndSetHeadRequest) ProtoMessage() {}

func (x *CompareAndSetHeadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_registry_history_v1_history_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompareAndSetHeadRequest.ProtoReflect.Descriptor instead.
func (*CompareAndSetHeadRequest) Descriptor() ([]byte, []int) {
	return file_api_registry_history_v1_history_proto_rawDescGZIP(), []int{11}
}

func (x *CompareAndSetHeadRequest) GetKey() *RegistryKey {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *CompareAndSetHeadRequest) GetExpectedId() uint64 {
	if x != nil {
		return x.ExpectedId
	}
	return 0
}

func (x *CompareAndSetHeadRequest) GetTargetId() uint64 {
	if x != nil {
		return x.TargetId
	}
	return 0
}

func (x *CompareAndSetHeadRequest) GetResolution() []byte {
	if x != nil {
		return x.Resolution
	}
	return nil
}

func (x *CompareAndSetHeadRequest) GetRetry() bool {
	if x != nil {
		return x.Retry
	}
	return false
}

type Resolution struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Resolution) Reset() {
	*x = Resolution{}
	mi := &file_api_registry_history_v1_history_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Resolution) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Resolution) ProtoMessage() {}

func (x *Resolution) ProtoReflect() protoreflect.Message {
	mi := &file_api_registry_history_v1_history_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Resolution.ProtoReflect.Descriptor instead.
func (*Resolution) Descriptor() ([]byte, []int) {
	return file_api_registry_history_v1_history_proto_rawDescGZIP(), []int{12}
}

func (x *Resolution) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type CheckpointResolutionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           *RegistryKey           `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	VersionId     uint64                 `protobuf:"varint,2,opt,name=version_id,json=versionId,proto3" json:"version_id,omitempty"`
	Resolution    []byte                 `protobuf:"bytes,3,opt,name=resolution,proto3" json:"resolution,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckpointResolutionRequest) Reset() {
	*x = CheckpointResolutionRequest{}
	mi := &file_api_registry_history_v1_history_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckpointResolutionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckpointResolutionRequest) ProtoMessage() {}

func (x *CheckpointResolutionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_registry_history_v1_history_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckpointResolutionRequest.ProtoReflect.Descriptor instead.
func (*CheckpointResolutionRequest) Descriptor() ([]byte, []int) {
	return file_api_registry_history_v1_history_proto_rawDescGZIP(), []int{13}
}

func (x *CheckpointResolutionRequest) GetKey() *RegistryKey {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *CheckpointResolutionRequest) GetVersionId() uint64 {
	if x != nil {
		return x.VersionId
	}
	return 0
}

func (x *CheckpointResolutionRequest) GetResolution() []byte {
	if x != nil {
		return x.Resolution
	}
	return nil
}

type Baseline struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	State         []byte                 `protobuf:"bytes,1,opt,name=state,proto3" json:"state,omitempty"`
	Digest        string                 `protobuf:"bytes,2,opt,name=digest,proto3" json:"digest,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Baseline) Reset() {
	*x = Baseline{}
	mi := &file_api_registry_history_v1_history_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Baseline) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Baseline) ProtoMessage() {}

func (x *Baseline) ProtoReflect() protoreflect.Message {
	mi := &file_api_registry_history_v1_history_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Baseline.ProtoReflect.Descriptor instead.
func (*Baseline) Descriptor() ([]byte, []int) {
	return file_api_registry_history_v1_history_proto_rawDescGZIP(), []int{14}
}

func (x *Baseline) GetState() []byte {
	if x != nil {
		return x.State
	}
	return nil
}

func (x *Baseline) GetDigest() string {
	if x != nil {
		return x.Digest
	}
	return ""
}

type SetBaselineRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Key            *RegistryKey           `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	ExpectedDigest string                 `protobuf:"bytes,2,opt,name=expected_digest,json=expectedDigest,proto3" json:"expected_digest,omitempty"`
	Baseline       *Baseline              `protobuf:"bytes,3,opt,name=baseline,proto3" json:"baseline,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SetBaselineRequest) Reset() {
	*x = SetBaselineRequest{}
	mi := &file_api_registry_history_v1_history_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetBaselineRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetBaselineRequest) ProtoMessage() {}

func (x *SetBaselineRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_registry_history_v1_history_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetBaselineRequest.ProtoReflect.Descriptor instead.
func (*SetBaselineRequest) Descriptor() ([]byte, []int) {
	return file_api_registry_history_v1_history_proto_rawDescGZIP(), []int{15}
}

func (x *SetBaselineRequest) GetKey() *RegistryKey {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *SetBaselineRequest) GetExpectedDigest() string {
	if x != nil {
		return x.ExpectedDigest
	}
	return ""
}

func (x *SetBaselineRequest) GetBaseline() *Baseline {
	if x != nil {
		return x.Baseline
	}
	return nil
}

type TransferVersion struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ParentId      uint64                 `protobuf:"varint,2,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	Changeset     []byte                 `protobuf:"bytes,3,opt,name=changeset,proto3" json:"changeset,omitempty"`
	Resolution    []byte                 `protobuf:"bytes,4,opt,name=resolution,proto3" json:"resolution,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransferVersion) Reset() {
	*x = TransferVersion{}
	mi := &file_api_registry_history_v1_history_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransferVersion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferVersion) ProtoMessage() {}

func (x *TransferVersion) ProtoReflect() protoreflect.Message {
	mi := &file_api_registry_history_v1_history_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferVersion.ProtoReflect.Descriptor instead.
func (*TransferVersion) Descriptor() ([]byte, []int) {
	return file_api_registry_history_v1_history_proto_rawDescGZIP(), []int{16}
}

func (x *TransferVersion) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *TransferVersion) GetParentId() uint64 {
	if x != nil {
		return x.ParentId
	}
	return 0
}

func (x *TransferVersion) GetChangeset() []byte {
	if x != nil {
		return x.Changeset
	}
	return nil
}

func (x *TransferVersion) GetResolution() []byte {
	if x != nil {
		return x.Resolution
	}
	return nil
}

type BeginTransferRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           *RegistryKey           `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	TransferId    string                 `protobuf:"bytes,2,opt,name=transfer_id,json=transferId,proto3" json:"transfer_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BeginTransferRequest) Reset() {
	*x = BeginTransferRequest{}
	mi := &file_api_registry_history_v1_history_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BeginTransferRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BeginTransferRequest) ProtoMessage() {}

func (x *BeginTransferRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_registry_history_v1_history_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BeginTransferRequest.ProtoReflect.Descriptor instead.
func (*BeginTransferRequest) Descriptor() ([]byte, []int) {
	return file_api_registry_history_v1_history_proto_rawDescGZIP(), []int{17}
}

func (x *BeginTransferRequest) GetKey() *RegistryKey {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *BeginTransferRequest) GetTransferId() string {
	if x != nil {
		return x.TransferId
	}
	return ""
}

type TransferVersionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           *RegistryKey           `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	TransferId    string                 `protobuf:"bytes,2,opt,name=transfer_id,json=transferId,proto3" json:"transfer_id,omitempty"`
	Versions      []*TransferVersion     `protobuf:"bytes,3,rep,name=versions,proto3" json:"versions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransferVersionsRequest) Reset() {
	*x = TransferVersionsRequest{}
	mi := &file_api_registry_history_v1_history_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransferVersionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferVersionsRequest) ProtoMessage() {}

func (x *TransferVersionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_registry_history_v1_history_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferVersionsRequest.ProtoReflect.Descriptor instead.
func (*TransferVersionsRequest) Descriptor() ([]byte, []int) {
	return file_api_registry_history_v1_history_proto_rawDescGZIP(), []int{18}
}

func (x *TransferVersionsRequest) GetKey() *RegistryKey {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *TransferVersionsRequest) GetTransferId() string {
	if x != nil {
		return x.TransferId
	}
	return ""
}

func (x *TransferVersionsRequest) GetVersions() []*TransferVersion {
	if x != nil {
		return x.Versions
	}
	return nil
}

type CompleteTransferRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           *RegistryKey           `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	TransferId    string                 `protobuf:"bytes,2,opt,name=transfer_id,json=transferId,proto3" json:"transfer_id,omitempty"`
	HeadId        uint64                 `protobuf:"varint,3,opt,name=head_id,json=headId,proto3" json:"head_id,omitempty"`
	Baseline      *Baseline              `protobuf:"bytes,4,opt,name=baseline,proto3" json:"baseline,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompleteTransferRequest) Reset() {
	*x = CompleteTransferRequest{}
	mi := &file_api_registry_history_v1_history_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteTransferRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteTransferRequest) ProtoMessage() {}

func (x *CompleteTransferRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_registry_history_v1_history_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteTransferRequest.ProtoReflect.Descriptor instead.
func (*CompleteTransferRequest) Descriptor() ([]byte, []int) {
	return file_api_registry_history_v1_history_proto_rawDescGZIP(), []int{19}
}

func (x *CompleteTransferRequest) GetKey() *RegistryKey {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *CompleteTransferRequest) GetTransferId() string {
	if x != nil {
		return x.TransferId
	}
	return ""
}

func (x *CompleteTransferRequest) GetHeadId() uint64 {
	if x != nil {
		return x.HeadId
	}
	return 0
}

func (x *CompleteTransferRequest) GetBaseline() *Baseline {
	if x != nil {
		return x.Baseline
	}
	return nil
}

// TransferStatus reports a completed transfer and the digest of the content
// that the transfer stored. Later writes do not change this digest.
type TransferStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Completed     bool                   `protobuf:"varint,1,opt,name=completed,proto3" json:"completed,omitempty"`
	Digest        string                 `protobuf:"bytes,2,opt,name=digest,proto3" json:"digest,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransferStatus) Reset() {
	*x = TransferStatus{}
	mi := &file_api_registry_history_v1_history_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransferStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferStatus) ProtoMessage() {}

func (x *TransferStatus) ProtoReflect() protoreflect.Message {
	mi := &file_api_registry_history_v1_history_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferStatus.ProtoReflect.Descriptor instead.
func (*TransferStatus) Descriptor() ([]byte, []int) {
	return file_api_registry_history_v1_history_proto_rawDescGZIP(), []int{20}
}

func (x *TransferStatus) GetCompleted() bool {
	if x != nil {
		return x.Completed
	}
	return false
}

func (x *TransferStatus) GetDigest() string {
	if x != nil {
		return x.Digest
	}
	return ""
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_api_registry_history_v1_history_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_api_registry_history_v1_history_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_api_registry_history_v1_history_proto_rawDescGZIP(), []int{21}
}

var File_api_registry_history_v1_history_proto protoreflect.FileDescriptor

const file_api_registry_history_v1_history_proto_rawDesc = "" +
	"\n" +
	"%api/registry/history/v1/history.proto\x12\x19wippy.registry.history.v1\"r\n" +
	"\vRegistryKey\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12%\n" +
	"\x0eenvironment_id\x18\x02 \x01(\tR\renvironmentId\x12\x1f\n" +
	"\vregistry_id\x18\x03 \x01(\tR\n" +
	"registryId\"K\n" +
	"\x0fRegistryRequest\x128\n" +
	"\x03key\x18\x01 \x01(\v2&.wippy.registry.history.v1.RegistryKeyR\x03key\"i\n" +
	"\x0eVersionRequest\x128\n" +
	"\x03key\x18\x01 \x01(\v2&.wippy.registry.history.v1.RegistryKeyR\x03key\x12\x1d\n" +
	"\n" +
	"version_id\x18\x02 \x01(\x04R\tversionId\"\x1b\n" +
	"\aLineage\x12\x10\n" +
	"\x03ids\x18\x01 \x03(\x04R\x03ids\"-\n" +
	"\fMaxVersionID\x12\x1d\n" +
	"\n" +
	"version_id\x18\x01 \x01(\x04R\tversionId\"\x92\x01\n" +
	"\x13ListVersionsRequest\x128\n" +
	"\x03key\x18\x01 \x01(\v2&.wippy.registry.history.v1.RegistryKeyR\x03key\x12\x1e\n" +
	"\bafter_id\x18\x02 \x01(\x04H\x00R\aafterId\x88\x01\x01\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\rR\x05limitB\v\n" +
	"\t_after_id\"M\n" +
	"\vVersionNode\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12 \n" +
	"\tparent_id\x18\x02 \x01(\x04H\x00R\bparentId\x88\x01\x01B\f\n" +
	"\n" +
	"_parent_id\"l\n" +
	"\vVersionList\x12B\n" +
	"\bversions\x18\x01 \x03(\v2&.wippy.registry.history.v1.VersionNodeR\bversions\x12\x19\n" +
	"\bhas_more\x18\x02 \x01(\bR\ahasMore\">\n" +
	"\tChangeSet\x12\x1d\n" +
	"\n" +
	"version_id\x18\x01 \x01(\x04R\tversionId\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\"\xeb\x01\n" +
	"\vSaveRequest\x128\n" +
	"\x03key\x18\x01 \x01(\v2&.wippy.registry.history.v1.RegistryKeyR\x03key\x12\x1d\n" +
	"\n" +
	"version_id\x18\x02 \x01(\x04R\tversionId\x12\x1b\n" +
	"\tparent_id\x18\x03 \x01(\x04R\bparentId\x12\x1c\n" +
	"\tchangeset\x18\x04 \x01(\fR\tchangeset\x12\x1e\n" +
	"\n" +
	"resolution\x18\x05 \x01(\fR\n" +
	"resolution\x12\x12\n" +
	"\x04head\x18\x06 \x01(\bR\x04head\x12\x14\n" +
	"\x05retry\x18\a \x01(\bR\x05retry\"i\n" +
	"\x0eSetHeadRequest\x128\n" +
	"\x03key\x18\x01 \x01(\v2&.wippy.registry.history.v1.RegistryKeyR\x03key\x12\x1d\n" +
	"\n" +
	"version_id\x18\x02 \x01(\x04R\tversionId\"\xc8\x01\n" +
	"\x18CompareAndSetHeadRequest\x128\n" +
	"\x03key\x18\x01 \x01(\v2&.wippy.registry.history.v1.RegistryKeyR\x03key\x12\x1f\n" +
	"\vexpected_id\x18\x02 \x01(\x04R\n" +
	"expectedId\x12\x1b\n" +
	"\ttarget_id\x18\x03 \x01(\x04R\btargetId\x12\x1e\n" +
	"\n" +
	"resolution\x18\x04 \x01(\fR\n" +
	"resolution\x12\x14\n" +
	"\x05retry\x18\x05 \x01(\bR\x05retry\" \n" +
	"\n" +
	"Resolution\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\"\x96\x01\n" +
	"\x1bCheckpointResolutionRequest\x128\n" +
	"\x03key\x18\x01 \x01(\v2&.wippy.registry.history.v1.RegistryKeyR\x03key\x12\x1d\n" +
	"\n" +
	"version_id\x18\x02 \x01(\x04R\tversionId\x12\x1e\n" +
	"\n" +
	"resolution\x18\x03 \x01(\fR\n" +
	"resolution\"8\n" +
	"\bBaseline\x12\x14\n" +
	"\x05state\x18\x01 \x01(\fR\x05state\x12\x16\n" +
	"\x06digest\x18\x02 \x01(\tR\x06digest\"\xb8\x01\n" +
	"\x12SetBaselineRequest\x128\n" +
	"\x03key\x18\x01 \x01(\v2&.wippy.registry.history.v1.RegistryKeyR\x03key\x12'\n" +
	"\x0fexpected_digest\x18\x02 \x01(\tR\x0eexpectedDigest\x12?\n" +
	"\bbaseline\x18\x03 \x01(\v2#.wippy.registry.history.v1.BaselineR\bbaseline\"|\n" +
	"\x0fTransferVersion\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x1b\n" +
	"\tparent_id\x18\x02 \x01(\x04R\bparentId\x12\x1c\n" +
	"\tchangeset\x18\x03 \x01(\fR\tchangeset\x12\x1e\n" +
	"\n" +
	"resolution\x18\x04 \x01(\fR\n" +
	"resolution\"q\n" +
	"\x14BeginTransferRequest\x128\n" +
	"\x03key\x18\x01 \x01(\v2&.wippy.registry.history.v1.RegistryKeyR\x03key\x12\x1f\n" +
	"\vtransfer_id\x18\x02 \x01(\tR\n" +
	"transferId\"\xbc\x01\n" +
	"\x17TransferVersionsRequest\x128\n" +
	"\x03key\x18\x01 \x01(\v2&.wippy.registry.history.v1.RegistryKeyR\x03key\x12\x1f\n" +
	"\vtransfer_id\x18\x02 \x01(\tR\n" +
	"transferId\x12F\n" +
	"\bversions\x18\x03 \x03(\v2*.wippy.registry.history.v1.TransferVersionR\bversions\"\xce\x01\n" +
	"\x17CompleteTransferRequest\x128\n" +
	"\x03key\x18\x01 \x01(\v2&.wippy.registry.history.v1.RegistryKeyR\x03key\x12\x1f\n" +
	"\vtransfer_id\x18\x02 \x01(\tR\n" +
	"transferId\x12\x17\n" +
	"\ahead_id\x18\x03 \x01(\x04R\x06headId\x12?\n" +
	"\bbaseline\x18\x04 \x01(\v2#.wippy.registry.history.v1.BaselineR\bbaseline\"F\n" +
	"\x0eTransferStatus\x12\x1c\n" +
	"\tcompleted\x18\x01 \x01(\bR\tcompleted\x12\x16\n" +
	"\x06digest\x18\x02 \x01(\tR\x06digest\"\a\n" +
	"\x05Empty2\xcf\f\n" +
	"\x0eHistoryService\x12V\n" +
	"\x04Head\x12*.wippy.registry.history.v1.RegistryRequest\x1a\".wippy.registry.history.v1.Lineage\x12[\n" +
	"\n" +
	"GetVersion\x12).wippy.registry.history.v1.VersionRequest\x1a\".wippy.registry.history.v1.Lineage\x12f\n" +
	"\x0fGetMaxVersionID\x12*.wippy.registry.history.v1.RegistryRequest\x1a'.wippy.registry.history.v1.MaxVersionID\x12f\n" +
	"\fListVersions\x12..wippy.registry.history.v1.ListVersionsRequest\x1a&.wippy.registry.history.v1.VersionList\x12_\n" +
	"\fGetChangeSet\x12).wippy.registry.history.v1.VersionRequest\x1a$.wippy.registry.history.v1.ChangeSet\x12b\n" +
	"\rReplayChanges\x12).wippy.registry.history.v1.VersionRequest\x1a$.wippy.registry.history.v1.ChangeSet0\x01\x12P\n" +
	"\x04Save\x12&.wippy.registry.history.v1.SaveRequest\x1a .wippy.registry.history.v1.Empty\x12V\n" +
	"\aSetHead\x12).wippy.registry.history.v1.SetHeadRequest\x1a .wippy.registry.history.v1.Empty\x12j\n" +
	"\x11CompareAndSetHead\x123.wippy.registry.history.v1.CompareAndSetHeadRequest\x1a .wippy.registry.history.v1.Empty\x12a\n" +
	"\rGetResolution\x12).wippy.registry.history.v1.VersionRequest\x1a%.wippy.registry.history.v1.Resolution\x12p\n" +
	"\x14CheckpointResolution\x126.wippy.registry.history.v1.CheckpointResolutionRequest\x1a .wippy.registry.history.v1.Empty\x12^\n" +
	"\vGetBaseline\x12*.wippy.registry.history.v1.RegistryRequest\x1a#.wippy.registry.history.v1.Baseline\x12^\n" +
	"\vSetBaseline\x12-.wippy.registry.history.v1.SetBaselineRequest\x1a .wippy.registry.history.v1.Empty\x12k\n" +
	"\rBeginTransfer\x12/.wippy.registry.history.v1.BeginTransferRequest\x1a).wippy.registry.history.v1.TransferStatus\x12h\n" +
	"\x10TransferVersions\x122.wippy.registry.history.v1.TransferVersionsRequest\x1a .wippy.registry.history.v1.Empty\x12q\n" +
	"\x10CompleteTransfer\x122.wippy.registry.history.v1.CompleteTransferRequest\x1a).wippy.registry.history.v1.TransferStatusB>Z<github.com/wippyai/runtime/api/registry/history/v1;historyv1b\x06proto3"

var (
	file_api_registry_history_v1_history_proto_rawDescOnce sync.Once
	file_api_registry_history_v1_history_proto_rawDescData []byte
)

func file_api_registry_history_v1_history_proto_rawDescGZIP() []byte {
	file_api_registry_history_v1_history_proto_rawDescOnce.Do(func() {
		file_api_registry_history_v1_history_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_registry_history_v1_history_proto_rawDesc), len(file_api_registry_history_v1_history_proto_rawDesc)))
	})
	return file_api_registry_history_v1_history_proto_rawDescData
}

var file_api_registry_history_v1_history_proto_msgTypes = make([]protoimpl.MessageInfo, 22)
var file_api_registry_history_v1_history_proto_goTypes = []any{
	(*RegistryKey)(nil),                 // 0: wippy.registry.history.v1.RegistryKey
	(*RegistryRequest)(nil),             // 1: wippy.registry.history.v1.RegistryRequest
	(*VersionRequest)(nil),              // 2: wippy.registry.history.v1.VersionRequest
	(*Lineage)(nil),                     // 3: wippy.registry.history.v1.Lineage
	(*MaxVersionID)(nil),                // 4: wippy.registry.history.v1.MaxVersionID
	(*ListVersionsRequest)(nil),         // 5: wippy.registry.history.v1.ListVersionsRequest
	(*VersionNode)(nil),                 // 6: wippy.registry.history.v1.VersionNode
	(*VersionList)(nil),                 // 7: wippy.registry.history.v1.VersionList
	(*ChangeSet)(nil),                   // 8: wippy.registry.history.v1.ChangeSet
	(*SaveRequest)(nil),                 // 9: wippy.registry.history.v1.SaveRequest
	(*SetHeadRequest)(nil),              // 10: wippy.registry.history.v1.SetHeadRequest
	(*CompareAndSetHeadRequest)(nil),    // 11: wippy.registry.history.v1.CompareAndSetHeadRequest
	(*Resolution)(nil),                  // 12: wippy.registry.history.v1.Resolution
	(*CheckpointResolutionRequest)(nil), // 13: wippy.registry.history.v1.CheckpointResolutionRequest
	(*Baseline)(nil),                    // 14: wippy.registry.history.v1.Baseline
	(*SetBaselineRequest)(nil),          // 15: wippy.registry.history.v1.SetBaselineRequest
	(*TransferVersion)(nil),             // 16: wippy.registry.history.v1.TransferVersion
	(*BeginTransferRequest)(nil),        // 17: wippy.registry.history.v1.BeginTransferRequest
	(*TransferVersionsRequest)(nil),     // 18: wippy.registry.history.v1.TransferVersionsRequest
	(*CompleteTransferRequest)(nil),     // 19: wippy.registry.history.v1.CompleteTransferRequest
	(*TransferStatus)(nil),              // 20: wippy.registry.history.v1.TransferStatus
	(*Empty)(nil),                       // 21: wippy.registry.history.v1.Empty
}
var file_api_registry_history_v1_history_proto_depIdxs = []int32{
	0,  // 0: wippy.registry.history.v1.RegistryRequest.key:type_name -> wippy.registry.history.v1.RegistryKey
	0,  // 1: wippy.registry.history.v1.VersionRequest.key:type_name -> wippy.registry.history.v1.RegistryKey
	0,  // 2: wippy.registry.history.v1.ListVersionsRequest.key:type_name -> wippy.registry.history.v1.RegistryKey
	6,  // 3: wippy.registry.history.v1.VersionList.versions:type_name -> wippy.registry.history.v1.VersionNode
	0,  // 4: wippy.registry.history.v1.SaveRequest.key:type_name -> wippy.registry.history.v1.RegistryKey
	0,  // 5: wippy.registry.history.v1.SetHeadRequest.key:type_name -> wippy.registry.history.v1.RegistryKey
	0,  // 6: wippy.registry.history.v1.CompareAndSetHeadRequest.key:type_name -> wippy.registry.history.v1.RegistryKey
	0,  // 7: wippy.registry.history.v1.CheckpointResolutionRequest.key:type_name -> wippy.registry.history.v1.RegistryKey
	0,  // 8: wippy.registry.history.v1.SetBaselineRequest.key:type_name -> wippy.registry.history.v1.RegistryKey
	14, // 9: wippy.registry.history.v1.SetBaselineRequest.baseline:type_name -> wippy.registry.history.v1.Baseline
	0,  // 10: wippy.registry.history.v1.BeginTransferRequest.key:type_name -> wippy.registry.history.v1.RegistryKey
	0,  // 11: wippy.registry.history.v1.TransferVersionsRequest.key:type_name -> wippy.registry.history.v1.RegistryKey
	16, // 12: wippy.registry.history.v1.TransferVersionsRequest.versions:type_name -> wippy.registry.history.v1.TransferVersion
	0,  // 13: wippy.registry.history.v1.CompleteTransferRequest.key:type_name -> wippy.registry.history.v1.RegistryKey
	14, // 14: wippy.registry.history.v1.CompleteTransferRequest.baseline:type_name -> wippy.registry.history.v1.Baseline
	1,  // 15: wippy.registry.history.v1.HistoryService.Head:input_type -> wippy.registry.history.v1.RegistryRequest
	2,  // 16: wippy.registry.history.v1.HistoryService.GetVersion:input_type -> wippy.registry.history.v1.VersionRequest
	1,  // 17: wippy.registry.history.v1.HistoryService.GetMaxVersionID:input_type -> wippy.registry.history.v1.RegistryRequest
	5,  // 18: wippy.registry.history.v1.HistoryService.ListVersions:input_type -> wippy.registry.history.v1.ListVersionsRequest
	2,  // 19: wippy.registry.history.v1.HistoryService.GetChangeSet:input_type -> wippy.registry.history.v1.VersionRequest
	2,  // 20: wippy.registry.history.v1.HistoryService.ReplayChanges:input_type -> wippy.registry.history.v1.VersionRequest
	9,  // 21: wippy.registry.history.v1.HistoryService.Save:input_type -> wippy.registry.history.v1.SaveRequest
	10, // 22: wippy.registry.history.v1.HistoryService.SetHead:input_type -> wippy.registry.history.v1.SetHeadRequest
	11, // 23: wippy.registry.history.v1.HistoryService.CompareAndSetHead:input_type -> wippy.registry.history.v1.CompareAndSetHeadRequest
	2,  // 24: wippy.registry.history.v1.HistoryService.GetResolution:input_type -> wippy.registry.history.v1.VersionRequest
	13, // 25: wippy.registry.history.v1.HistoryService.CheckpointResolution:input_type -> wippy.registry.history.v1.CheckpointResolutionRequest
	1,  // 26: wippy.registry.history.v1.HistoryService.GetBaseline:input_type -> wippy.registry.history.v1.RegistryRequest
	15, // 27: wippy.registry.history.v1.HistoryService.SetBaseline:input_type -> wippy.registry.history.v1.SetBaselineRequest
	17, // 28: wippy.registry.history.v1.HistoryService.BeginTransfer:input_type -> wippy.registry.history.v1.BeginTransferRequest
	18, // 29: wippy.registry.history.v1.HistoryService.TransferVersions:input_type -> wippy.registry.history.v1.TransferVersionsRequest
	19, // 30: wippy.registry.history.v1.HistoryService.CompleteTransfer:input_type -> wippy.registry.history.v1.CompleteTransferRequest
	3,  // 31: wippy.registry.history.v1.HistoryService.Head:output_type -> wippy.registry.history.v1.Lineage
	3,  // 32: wippy.registry.history.v1.HistoryService.GetVersion:output_type -> wippy.registry.history.v1.Lineage
	4,  // 33: wippy.registry.history.v1.HistoryService.GetMaxVersionID:output_type -> wippy.registry.history.v1.MaxVersionID
	7,  // 34: wippy.registry.history.v1.HistoryService.ListVersions:output_type -> wippy.registry.history.v1.VersionList
	8,  // 35: wippy.registry.history.v1.HistoryService.GetChangeSet:output_type -> wippy.registry.history.v1.ChangeSet
	8,  // 36: wippy.registry.history.v1.HistoryService.ReplayChanges:output_type -> wippy.registry.history.v1.ChangeSet
	21, // 37: wippy.registry.history.v1.HistoryService.Save:output_type -> wippy.registry.history.v1.Empty
	21, // 38: wippy.registry.history.v1.HistoryService.SetHead:output_type -> wippy.registry.history.v1.Empty
	21, // 39: wippy.registry.history.v1.HistoryService.CompareAndSetHead:output_type -> wippy.registry.history.v1.Empty
	12, // 40: wippy.registry.history.v1.HistoryService.GetResolution:output_type -> wippy.registry.history.v1.Resolution
	21, // 41: wippy.registry.history.v1.HistoryService.CheckpointResolution:output_type -> wippy.registry.history.v1.Empty
	14, // 42: wippy.registry.history.v1.HistoryService.GetBaseline:output_type -> wippy.registry.history.v1.Baseline
	21, // 43: wippy.registry.history.v1.HistoryService.SetBaseline:output_type -> wippy.registry.history.v1.Empty
	20, // 44: wippy.registry.history.v1.HistoryService.BeginTransfer:output_type -> wippy.registry.history.v1.TransferStatus
	21, // 45: wippy.registry.history.v1.HistoryService.TransferVersions:output_type -> wippy.registry.history.v1.Empty
	20, // 46: wippy.registry.history.v1.HistoryService.CompleteTransfer:output_type -> wippy.registry.history.v1.TransferStatus
	31, // [31:47] is the sub-list for method output_type
	15, // [15:31] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_api_registry_history_v1_history_proto_init() }
func file_api_registry_history_v1_history_proto_init() {
	if File_api_registry_history_v1_history_proto != nil {
		return
	}
	file_api_registry_history_v1_history_proto_msgTypes[5].OneofWrappers = []any{}
	file_api_registry_history_v1_history_proto_msgTypes[6].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_registry_history_v1_history_proto_rawDesc), len(file_api_registry_history_v1_history_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   22,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_registry_history_v1_history_proto_goTypes,
		DependencyIndexes: file_api_registry_history_v1_history_proto_depIdxs,
		MessageInfos:      file_api_registry_history_v1_history_proto_msgTypes,
	}.Build()
	File_api_registry_history_v1_history_proto = out.File
	file_api_registry_history_v1_history_proto_goTypes = nil
	file_api_registry_history_v1_history_proto_depIdxs = nil
}
