// SPDX-License-Identifier: MPL-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: wippy/api/hub/manifest/v1/message.proto

package manifestv1

import (
	v11 "github.com/wippyai/runtime/api/hub/wippy/api/hub/common/v1"
	v1 "github.com/wippyai/runtime/api/hub/wippy/api/hub/version/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Resolution strategy.
type ResolutionStrategy int32

const (
	ResolutionStrategy_RESOLUTION_STRATEGY_UNSPECIFIED ResolutionStrategy = 0
	ResolutionStrategy_RESOLUTION_STRATEGY_NEWEST      ResolutionStrategy = 1
	ResolutionStrategy_RESOLUTION_STRATEGY_MINIMAL     ResolutionStrategy = 2
)

// Enum value maps for ResolutionStrategy.
var (
	ResolutionStrategy_name = map[int32]string{
		0: "RESOLUTION_STRATEGY_UNSPECIFIED",
		1: "RESOLUTION_STRATEGY_NEWEST",
		2: "RESOLUTION_STRATEGY_MINIMAL",
	}
	ResolutionStrategy_value = map[string]int32{
		"RESOLUTION_STRATEGY_UNSPECIFIED": 0,
		"RESOLUTION_STRATEGY_NEWEST":      1,
		"RESOLUTION_STRATEGY_MINIMAL":     2,
	}
)

func (x ResolutionStrategy) Enum() *ResolutionStrategy {
	p := new(ResolutionStrategy)
	*p = x
	return p
}

func (x ResolutionStrategy) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ResolutionStrategy) Descriptor() protoreflect.EnumDescriptor {
	return file_wippy_api_hub_manifest_v1_message_proto_enumTypes[0].Descriptor()
}

func (ResolutionStrategy) Type() protoreflect.EnumType {
	return &file_wippy_api_hub_manifest_v1_message_proto_enumTypes[0]
}

func (x ResolutionStrategy) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ResolutionStrategy.Descriptor instead.
func (ResolutionStrategy) EnumDescriptor() ([]byte, []int) {
	return file_wippy_api_hub_manifest_v1_message_proto_rawDescGZIP(), []int{0}
}

// Complete manifest for a module version.
type ModuleManifest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ModuleId      string                 `protobuf:"bytes,1,opt,name=module_id,json=moduleId,proto3" json:"module_id,omitempty"`
	Org           string                 `protobuf:"bytes,2,opt,name=org,proto3" json:"org,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	VersionId     string                 `protobuf:"bytes,4,opt,name=version_id,json=versionId,proto3" json:"version_id,omitempty"`
	Version       string                 `protobuf:"bytes,5,opt,name=version,proto3" json:"version,omitempty"`
	Digest        string                 `protobuf:"bytes,6,opt,name=digest,proto3" json:"digest,omitempty"`
	SizeBytes     uint64                 `protobuf:"varint,7,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	Metadata      *v1.VersionMetadata    `protobuf:"bytes,8,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Dependencies  []*ResolvedDependency  `protobuf:"bytes,9,rep,name=dependencies,proto3" json:"dependencies,omitempty"`
	Download      *v11.DownloadInfo      `protobuf:"bytes,10,opt,name=download,proto3" json:"download,omitempty"`
	Protected     bool                   `protobuf:"varint,11,opt,name=protected,proto3" json:"protected,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ModuleManifest) Reset() {
	*x = ModuleManifest{}
	mi := &file_wippy_api_hub_manifest_v1_message_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModuleManifest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModuleManifest) ProtoMessage() {}

func (x *ModuleManifest) ProtoReflect() protoreflect.Message {
	mi := &file_wippy_api_hub_manifest_v1_message_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModuleManifest.ProtoReflect.Descriptor instead.
func (*ModuleManifest) Descriptor() ([]byte, []int) {
	return file_wippy_api_hub_manifest_v1_message_proto_rawDescGZIP(), []int{0}
}

func (x *ModuleManifest) GetModuleId() string {
	if x != nil {
		return x.ModuleId
	}
	return ""
}

func (x *ModuleManifest) GetOrg() string {
	if x != nil {
		return x.Org
	}
	return ""
}

func (x *ModuleManifest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ModuleManifest) GetVersionId() string {
	if x != nil {
		return x.VersionId
	}
	return ""
}

func (x *ModuleManifest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *ModuleManifest) GetDigest() string {
	if x != nil {
		return x.Digest
	}
	return ""
}

func (x *ModuleManifest) GetSizeBytes() uint64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

func (x *ModuleManifest) GetMetadata() *v1.VersionMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *ModuleManifest) GetDependencies() []*ResolvedDependency {
	if x != nil {
		return x.Dependencies
	}
	return nil
}

func (x *ModuleManifest) GetDownload() *v11.DownloadInfo {
	if x != nil {
		return x.Download
	}
	return nil
}

func (x *ModuleManifest) GetProtected() bool {
	if x != nil {
		return x.Protected
	}
	return false
}

// Resolved dependency with download info.
type ResolvedDependency struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Org           string                 `protobuf:"bytes,1,opt,name=org,proto3" json:"org,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Version       string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	VersionId     string                 `protobuf:"bytes,4,opt,name=version_id,json=versionId,proto3" json:"version_id,omitempty"`
	Digest        string                 `protobuf:"bytes,5,opt,name=digest,proto3" json:"digest,omitempty"`
	SizeBytes     uint64                 `protobuf:"varint,6,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	Download      *v11.DownloadInfo      `protobuf:"bytes,7,opt,name=download,proto3" json:"download,omitempty"`
	Protected     bool                   `protobuf:"varint,8,opt,name=protected,proto3" json:"protected,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolvedDependency) Reset() {
	*x = ResolvedDependency{}
	mi := &file_wippy_api_hub_manifest_v1_message_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolvedDependency) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolvedDependency) ProtoMessage() {}

func (x *ResolvedDependency) ProtoReflect() protoreflect.Message {
	mi := &file_wippy_api_hub_manifest_v1_message_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolvedDependency.ProtoReflect.Descriptor instead.
func (*ResolvedDependency) Descriptor() ([]byte, []int) {
	return file_wippy_api_hub_manifest_v1_message_proto_rawDescGZIP(), []int{1}
}

func (x *ResolvedDependency) GetOrg() string {
	if x != nil {
		return x.Org
	}
	return ""
}

func (x *ResolvedDependency) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ResolvedDependency) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *ResolvedDependency) GetVersionId() string {
	if x != nil {
		return x.VersionId
	}
	return ""
}

func (x *ResolvedDependency) GetDigest() string {
	if x != nil {
		return x.Digest
	}
	return ""
}

func (x *ResolvedDependency) GetSizeBytes() uint64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

func (x *ResolvedDependency) GetDownload() *v11.DownloadInfo {
	if x != nil {
		return x.Download
	}
	return nil
}

func (x *ResolvedDependency) GetProtected() bool {
	if x != nil {
		return x.Protected
	}
	return false
}

// Dependency specification for resolution.
type DependencySpec struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Org           string                 `protobuf:"bytes,1,opt,name=org,proto3" json:"org,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Constraint    string                 `protobuf:"bytes,3,opt,name=constraint,proto3" json:"constraint,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DependencySpec) Reset() {
	*x = DependencySpec{}
	mi := &file_wippy_api_hub_manifest_v1_message_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DependencySpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DependencySpec) ProtoMessage() {}

func (x *DependencySpec) ProtoReflect() protoreflect.Message {
	mi := &file_wippy_api_hub_manifest_v1_message_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DependencySpec.ProtoReflect.Descriptor instead.
func (*DependencySpec) Descriptor() ([]byte, []int) {
	return file_wippy_api_hub_manifest_v1_message_proto_rawDescGZIP(), []int{2}
}

func (x *DependencySpec) GetOrg() string {
	if x != nil {
		return x.Org
	}
	return ""
}

func (x *DependencySpec) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DependencySpec) GetConstraint() string {
	if x != nil {
		return x.Constraint
	}
	return ""
}

// Already installed module.
type InstalledModule struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Org           string                 `protobuf:"bytes,1,opt,name=org,proto3" json:"org,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Version       string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	Digest        string                 `protobuf:"bytes,4,opt,name=digest,proto3" json:"digest,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InstalledModule) Reset() {
	*x = InstalledModule{}
	mi := &file_wippy_api_hub_manifest_v1_message_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InstalledModule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstalledModule) ProtoMessage() {}

func (x *InstalledModule) ProtoReflect() protoreflect.Message {
	mi := &file_wippy_api_hub_manifest_v1_message_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstalledModule.ProtoReflect.Descriptor instead.
func (*InstalledModule) Descriptor() ([]byte, []int) {
	return file_wippy_api_hub_manifest_v1_message_proto_rawDescGZIP(), []int{3}
}

func (x *InstalledModule) GetOrg() string {
	if x != nil {
		return x.Org
	}
	return ""
}

func (x *InstalledModule) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *InstalledModule) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *InstalledModule) GetDigest() string {
	if x != nil {
		return x.Digest
	}
	return ""
}

// Resolved module with full download info.
type ResolvedModule struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Org           string                 `protobuf:"bytes,1,opt,name=org,proto3" json:"org,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Version       string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	VersionId     string                 `protobuf:"bytes,4,opt,name=version_id,json=versionId,proto3" json:"version_id,omitempty"`
	Digest        string                 `protobuf:"bytes,5,opt,name=digest,proto3" json:"digest,omitempty"`
	SizeBytes     uint64                 `protobuf:"varint,6,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	Download      *v11.DownloadInfo      `protobuf:"bytes,7,opt,name=download,proto3" json:"download,omitempty"`
	Dependencies  []*DependencySpec      `protobuf:"bytes,8,rep,name=dependencies,proto3" json:"dependencies,omitempty"`
	Protected     bool                   `protobuf:"varint,9,opt,name=protected,proto3" json:"protected,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolvedModule) Reset() {
	*x = ResolvedModule{}
	mi := &file_wippy_api_hub_manifest_v1_message_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolvedModule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolvedModule) ProtoMessage() {}

func (x *ResolvedModule) ProtoReflect() protoreflect.Message {
	mi := &file_wippy_api_hub_manifest_v1_message_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolvedModule.ProtoReflect.Descriptor instead.
func (*ResolvedModule) Descriptor() ([]byte, []int) {
	return file_wippy_api_hub_manifest_v1_message_proto_rawDescGZIP(), []int{4}
}

func (x *ResolvedModule) GetOrg() string {
	if x != nil {
		return x.Org
	}
	return ""
}

func (x *ResolvedModule) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ResolvedModule) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *ResolvedModule) GetVersionId() string {
	if x != nil {
		return x.VersionId
	}
	return ""
}

func (x *ResolvedModule) GetDigest() string {
	if x != nil {
		return x.Digest
	}
	return ""
}

func (x *ResolvedModule) GetSizeBytes() uint64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

func (x *ResolvedModule) GetDownload() *v11.DownloadInfo {
	if x != nil {
		return x.Download
	}
	return nil
}

func (x *ResolvedModule) GetDependencies() []*DependencySpec {
	if x != nil {
		return x.Dependencies
	}
	return nil
}

func (x *ResolvedModule) GetProtected() bool {
	if x != nil {
		return x.Protected
	}
	return false
}

// Resolution error.
type ResolutionError struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Org           string                 `protobuf:"bytes,1,opt,name=org,proto3" json:"org,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Constraint    string                 `protobuf:"bytes,3,opt,name=constraint,proto3" json:"constraint,omitempty"`
	Error         *v11.OperationError    `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolutionError) Reset() {
	*x = ResolutionError{}
	mi := &file_wippy_api_hub_manifest_v1_message_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolutionError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolutionError) ProtoMessage() {}

func (x *ResolutionError) ProtoReflect() protoreflect.Message {
	mi := &file_wippy_api_hub_manifest_v1_message_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolutionError.ProtoReflect.Descriptor instead.
func (*ResolutionError) Descriptor() ([]byte, []int) {
	return file_wippy_api_hub_manifest_v1_message_proto_rawDescGZIP(), []int{5}
}

func (x *ResolutionError) GetOrg() string {
	if x != nil {
		return x.Org
	}
	return ""
}

func (x *ResolutionError) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ResolutionError) GetConstraint() string {
	if x != nil {
		return x.Constraint
	}
	return ""
}

func (x *ResolutionError) GetError() *v11.OperationError {
	if x != nil {
		return x.Error
	}
	return nil
}

// Available module update.
type ModuleUpdate struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Org            string                 `protobuf:"bytes,1,opt,name=org,proto3" json:"org,omitempty"`
	Name           string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	CurrentVersion string                 `protobuf:"bytes,3,opt,name=current_version,json=currentVersion,proto3" json:"current_version,omitempty"`
	LatestVersion  string                 `protobuf:"bytes,4,opt,name=latest_version,json=latestVersion,proto3" json:"latest_version,omitempty"`
	Breaking       bool                   `protobuf:"varint,5,opt,name=breaking,proto3" json:"breaking,omitempty"`
	Summary        string                 `protobuf:"bytes,6,opt,name=summary,proto3" json:"summary,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ModuleUpdate) Reset() {
	*x = ModuleUpdate{}
	mi := &file_wippy_api_hub_manifest_v1_message_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModuleUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModuleUpdate) ProtoMessage() {}

func (x *ModuleUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_wippy_api_hub_manifest_v1_message_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModuleUpdate.ProtoReflect.Descriptor instead.
func (*ModuleUpdate) Descriptor() ([]byte, []int) {
	return file_wippy_api_hub_manifest_v1_message_proto_rawDescGZIP(), []int{6}
}

func (x *ModuleUpdate) GetOrg() string {
	if x != nil {
		return x.Org
	}
	return ""
}

func (x *ModuleUpdate) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ModuleUpdate) GetCurrentVersion() string {
	if x != nil {
		return x.CurrentVersion
	}
	return ""
}

func (x *ModuleUpdate) GetLatestVersion() string {
	if x != nil {
		return x.LatestVersion
	}
	return ""
}

func (x *ModuleUpdate) GetBreaking() bool {
	if x != nil {
		return x.Breaking
	}
	return false
}

func (x *ModuleUpdate) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

var File_wippy_api_hub_manifest_v1_message_proto protoreflect.FileDescriptor

const file_wippy_api_hub_manifest_v1_message_proto_rawDesc = "" +
	"\n" +
	"'wippy/api/hub/manifest/v1/message.proto\x12\x19wippy.api.hub.manifest.v1\x1a%wippy/api/hub/common/v1/message.proto\x1a&wippy/api/hub/version/v1/message.proto\"\xbe\x03\n" +
	"\x0eModuleManifest\x12\x1b\n" +
	"\tmodule_id\x18\x01 \x01(\tR\bmoduleId\x12\x10\n" +
	"\x03org\x18\x02 \x01(\tR\x03org\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"version_id\x18\x04 \x01(\tR\tversionId\x12\x18\n" +
	"\aversion\x18\x05 \x01(\tR\aversion\x12\x16\n" +
	"\x06digest\x18\x06 \x01(\tR\x06digest\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\a \x01(\x04R\tsizeBytes\x12E\n" +
	"\bmetadata\x18\b \x01(\v2).wippy.api.hub.version.v1.VersionMetadataR\bmetadata\x12Q\n" +
	"\fdependencies\x18\t \x03(\v2-.wippy.api.hub.manifest.v1.ResolvedDependencyR\fdependencies\x12A\n" +
	"\bdownload\x18\n" +
	" \x01(\v2%.wippy.api.hub.common.v1.DownloadInfoR\bdownload\x12\x1c\n" +
	"\tprotected\x18\v \x01(\bR\tprotected\"\x8b\x02\n" +
	"\x12ResolvedDependency\x12\x10\n" +
	"\x03org\x18\x01 \x01(\tR\x03org\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\x12\x1d\n" +
	"\n" +
	"version_id\x18\x04 \x01(\tR\tversionId\x12\x16\n" +
	"\x06digest\x18\x05 \x01(\tR\x06digest\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\x06 \x01(\x04R\tsizeBytes\x12A\n" +
	"\bdownload\x18\a \x01(\v2%.wippy.api.hub.common.v1.DownloadInfoR\bdownload\x12\x1c\n" +
	"\tprotected\x18\b \x01(\bR\tprotected\"V\n" +
	"\x0eDependencySpec\x12\x10\n" +
	"\x03org\x18\x01 \x01(\tR\x03org\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1e\n" +
	"\n" +
	"constraint\x18\x03 \x01(\tR\n" +
	"constraint\"i\n" +
	"\x0fInstalledModule\x12\x10\n" +
	"\x03org\x18\x01 \x01(\tR\x03org\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\x12\x16\n" +
	"\x06digest\x18\x04 \x01(\tR\x06digest\"\xd6\x02\n" +
	"\x0eResolvedModule\x12\x10\n" +
	"\x03org\x18\x01 \x01(\tR\x03org\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\x12\x1d\n" +
	"\n" +
	"version_id\x18\x04 \x01(\tR\tversionId\x12\x16\n" +
	"\x06digest\x18\x05 \x01(\tR\x06digest\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\x06 \x01(\x04R\tsizeBytes\x12A\n" +
	"\bdownload\x18\a \x01(\v2%.wippy.api.hub.common.v1.DownloadInfoR\bdownload\x12M\n" +
	"\fdependencies\x18\b \x03(\v2).wippy.api.hub.manifest.v1.DependencySpecR\fdependencies\x12\x1c\n" +
	"\tprotected\x18\t \x01(\bR\tprotected\"\x96\x01\n" +
	"\x0fResolutionError\x12\x10\n" +
	"\x03org\x18\x01 \x01(\tR\x03org\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1e\n" +
	"\n" +
	"constraint\x18\x03 \x01(\tR\n" +
	"constraint\x12=\n" +
	"\x05error\x18\x04 \x01(\v2'.wippy.api.hub.common.v1.OperationErrorR\x05error\"\xba\x01\n" +
	"\fModuleUpdate\x12\x10\n" +
	"\x03org\x18\x01 \x01(\tR\x03org\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12'\n" +
	"\x0fcurrent_version\x18\x03 \x01(\tR\x0ecurrentVersion\x12%\n" +
	"\x0elatest_version\x18\x04 \x01(\tR\rlatestVersion\x12\x1a\n" +
	"\bbreaking\x18\x05 \x01(\bR\bbreaking\x12\x18\n" +
	"\asummary\x18\x06 \x01(\tR\asummary*z\n" +
	"\x12ResolutionStrategy\x12#\n" +
	"\x1fRESOLUTION_STRATEGY_UNSPECIFIED\x10\x00\x12\x1e\n" +
	"\x1aRESOLUTION_STRATEGY_NEWEST\x10\x01\x12\x1f\n" +
	"\x1bRESOLUTION_STRATEGY_MINIMAL\x10\x02B\xff\x01\n" +
	"\x1dcom.wippy.api.hub.manifest.v1B\fMessageProtoP\x01ZGgithub.com/wippyai/runtime/api/hub/wippy/api/hub/manifest/v1;manifestv1\xa2\x02\x04WAHM\xaa\x02\x19Wippy.Api.Hub.Manifest.V1\xca\x02\x19Wippy\\Api\\Hub\\Manifest\\V1\xe2\x02%Wippy\\Api\\Hub\\Manifest\\V1\\GPBMetadata\xea\x02\x1dWippy::Api::Hub::Manifest::V1b\x06proto3"

var (
	file_wippy_api_hub_manifest_v1_message_proto_rawDescOnce sync.Once
	file_wippy_api_hub_manifest_v1_message_proto_rawDescData []byte
)

func file_wippy_api_hub_manifest_v1_message_proto_rawDescGZIP() []byte {
	file_wippy_api_hub_manifest_v1_message_proto_rawDescOnce.Do(func() {
		file_wippy_api_hub_manifest_v1_message_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_wippy_api_hub_manifest_v1_message_proto_rawDesc), len(file_wippy_api_hub_manifest_v1_message_proto_rawDesc)))
	})
	return file_wippy_api_hub_manifest_v1_message_proto_rawDescData
}

var file_wippy_api_hub_manifest_v1_message_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_wippy_api_hub_manifest_v1_message_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_wippy_api_hub_manifest_v1_message_proto_goTypes = []any{
	(ResolutionStrategy)(0),    // 0: wippy.api.hub.manifest.v1.ResolutionStrategy
	(*ModuleManifest)(nil),     // 1: wippy.api.hub.manifest.v1.ModuleManifest
	(*ResolvedDependency)(nil), // 2: wippy.api.hub.manifest.v1.ResolvedDependency
	(*DependencySpec)(nil),     // 3: wippy.api.hub.manifest.v1.DependencySpec
	(*InstalledModule)(nil),    // 4: wippy.api.hub.manifest.v1.InstalledModule
	(*ResolvedModule)(nil),     // 5: wippy.api.hub.manifest.v1.ResolvedModule
	(*ResolutionError)(nil),    // 6: wippy.api.hub.manifest.v1.ResolutionError
	(*ModuleUpdate)(nil),       // 7: wippy.api.hub.manifest.v1.ModuleUpdate
	(*v1.VersionMetadata)(nil), // 8: wippy.api.hub.version.v1.VersionMetadata
	(*v11.DownloadInfo)(nil),   // 9: wippy.api.hub.common.v1.DownloadInfo
	(*v11.OperationError)(nil), // 10: wippy.api.hub.common.v1.OperationError
}
var file_wippy_api_hub_manifest_v1_message_proto_depIdxs = []int32{
	8,  // 0: wippy.api.hub.manifest.v1.ModuleManifest.metadata:type_name -> wippy.api.hub.version.v1.VersionMetadata
	2,  // 1: wippy.api.hub.manifest.v1.ModuleManifest.dependencies:type_name -> wippy.api.hub.manifest.v1.ResolvedDependency
	9,  // 2: wippy.api.hub.manifest.v1.ModuleManifest.download:type_name -> wippy.api.hub.common.v1.DownloadInfo
	9,  // 3: wippy.api.hub.manifest.v1.ResolvedDependency.download:type_name -> wippy.api.hub.common.v1.DownloadInfo
	9,  // 4: wippy.api.hub.manifest.v1.ResolvedModule.download:type_name -> wippy.api.hub.common.v1.DownloadInfo
	3,  // 5: wippy.api.hub.manifest.v1.ResolvedModule.dependencies:type_name -> wippy.api.hub.manifest.v1.DependencySpec
	10, // 6: wippy.api.hub.manifest.v1.ResolutionError.error:type_name -> wippy.api.hub.common.v1.OperationError
	7,  // [7:7] is the sub-list for method output_type
	7,  // [7:7] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_wippy_api_hub_manifest_v1_message_proto_init() }
func file_wippy_api_hub_manifest_v1_message_proto_init() {
	if File_wippy_api_hub_manifest_v1_message_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_wippy_api_hub_manifest_v1_message_proto_rawDesc), len(file_wippy_api_hub_manifest_v1_message_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_wippy_api_hub_manifest_v1_message_proto_goTypes,
		DependencyIndexes: file_wippy_api_hub_manifest_v1_message_proto_depIdxs,
		EnumInfos:         file_wippy_api_hub_manifest_v1_message_proto_enumTypes,
		MessageInfos:      file_wippy_api_hub_manifest_v1_message_proto_msgTypes,
	}.Build()
	File_wippy_api_hub_manifest_v1_message_proto = out.File
	file_wippy_api_hub_manifest_v1_message_proto_goTypes = nil
	file_wippy_api_hub_manifest_v1_message_proto_depIdxs = nil
}
