// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: wippy/api/hub/manifest/v1/service.proto

package manifestv1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	v1 "github.com/wippyai/runtime/api/hub/wippy/api/hub/module/v1"
	v11 "github.com/wippyai/runtime/api/hub/wippy/api/hub/version/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetManifestRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Module        *v1.ModuleRef          `protobuf:"bytes,1,opt,name=module,proto3" json:"module,omitempty"`
	Version       *v11.VersionRef        `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetManifestRequest) Reset() {
	*x = GetManifestRequest{}
	mi := &file_wippy_api_hub_manifest_v1_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetManifestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetManifestRequest) ProtoMessage() {}

func (x *GetManifestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wippy_api_hub_manifest_v1_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetManifestRequest.ProtoReflect.Descriptor instead.
func (*GetManifestRequest) Descriptor() ([]byte, []int) {
	return file_wippy_api_hub_manifest_v1_service_proto_rawDescGZIP(), []int{0}
}

func (x *GetManifestRequest) GetModule() *v1.ModuleRef {
	if x != nil {
		return x.Module
	}
	return nil
}

func (x *GetManifestRequest) GetVersion() *v11.VersionRef {
	if x != nil {
		return x.Version
	}
	return nil
}

type GetManifestResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Manifest      *ModuleManifest        `protobuf:"bytes,1,opt,name=manifest,proto3" json:"manifest,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetManifestResponse) Reset() {
	*x = GetManifestResponse{}
	mi := &file_wippy_api_hub_manifest_v1_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetManifestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetManifestResponse) ProtoMessage() {}

func (x *GetManifestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_wippy_api_hub_manifest_v1_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetManifestResponse.ProtoReflect.Descriptor instead.
func (*GetManifestResponse) Descriptor() ([]byte, []int) {
	return file_wippy_api_hub_manifest_v1_service_proto_rawDescGZIP(), []int{1}
}

func (x *GetManifestResponse) GetManifest() *ModuleManifest {
	if x != nil {
		return x.Manifest
	}
	return nil
}

type ResolveDependenciesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Roots         []*DependencySpec      `protobuf:"bytes,1,rep,name=roots,proto3" json:"roots,omitempty"`
	Installed     []*InstalledModule     `protobuf:"bytes,2,rep,name=installed,proto3" json:"installed,omitempty"`
	Strategy      ResolutionStrategy     `protobuf:"varint,3,opt,name=strategy,proto3,enum=wippy.api.hub.manifest.v1.ResolutionStrategy" json:"strategy,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveDependenciesRequest) Reset() {
	*x = ResolveDependenciesRequest{}
	mi := &file_wippy_api_hub_manifest_v1_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveDependenciesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveDependenciesRequest) ProtoMessage() {}

func (x *ResolveDependenciesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wippy_api_hub_manifest_v1_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveDependenciesRequest.ProtoReflect.Descriptor instead.
func (*ResolveDependenciesRequest) Descriptor() ([]byte, []int) {
	return file_wippy_api_hub_manifest_v1_service_proto_rawDescGZIP(), []int{2}
}

func (x *ResolveDependenciesRequest) GetRoots() []*DependencySpec {
	if x != nil {
		return x.Roots
	}
	return nil
}

func (x *ResolveDependenciesRequest) GetInstalled() []*InstalledModule {
	if x != nil {
		return x.Installed
	}
	return nil
}

func (x *ResolveDependenciesRequest) GetStrategy() ResolutionStrategy {
	if x != nil {
		return x.Strategy
	}
	return ResolutionStrategy_RESOLUTION_STRATEGY_UNSPECIFIED
}

type ResolveDependenciesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Modules       []*ResolvedModule      `protobuf:"bytes,1,rep,name=modules,proto3" json:"modules,omitempty"`
	Errors        []*ResolutionError     `protobuf:"bytes,2,rep,name=errors,proto3" json:"errors,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveDependenciesResponse) Reset() {
	*x = ResolveDependenciesResponse{}
	mi := &file_wippy_api_hub_manifest_v1_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveDependenciesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveDependenciesResponse) ProtoMessage() {}

func (x *ResolveDependenciesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_wippy_api_hub_manifest_v1_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveDependenciesResponse.ProtoReflect.Descriptor instead.
func (*ResolveDependenciesResponse) Descriptor() ([]byte, []int) {
	return file_wippy_api_hub_manifest_v1_service_proto_rawDescGZIP(), []int{3}
}

func (x *ResolveDependenciesResponse) GetModules() []*ResolvedModule {
	if x != nil {
		return x.Modules
	}
	return nil
}

func (x *ResolveDependenciesResponse) GetErrors() []*ResolutionError {
	if x != nil {
		return x.Errors
	}
	return nil
}

type CheckUpdatesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Installed     []*InstalledModule     `protobuf:"bytes,1,rep,name=installed,proto3" json:"installed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckUpdatesRequest) Reset() {
	*x = CheckUpdatesRequest{}
	mi := &file_wippy_api_hub_manifest_v1_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckUpdatesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckUpdatesRequest) ProtoMessage() {}

func (x *CheckUpdatesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wippy_api_hub_manifest_v1_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckUpdatesRequest.ProtoReflect.Descriptor instead.
func (*CheckUpdatesRequest) Descriptor() ([]byte, []int) {
	return file_wippy_api_hub_manifest_v1_service_proto_rawDescGZIP(), []int{4}
}

func (x *CheckUpdatesRequest) GetInstalled() []*InstalledModule {
	if x != nil {
		return x.Installed
	}
	return nil
}

type CheckUpdatesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Updates       []*ModuleUpdate        `protobuf:"bytes,1,rep,name=updates,proto3" json:"updates,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckUpdatesResponse) Reset() {
	*x = CheckUpdatesResponse{}
	mi := &file_wippy_api_hub_manifest_v1_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckUpdatesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckUpdatesResponse) ProtoMessage() {}

func (x *CheckUpdatesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_wippy_api_hub_manifest_v1_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckUpdatesResponse.ProtoReflect.Descriptor instead.
func (*CheckUpdatesResponse) Descriptor() ([]byte, []int) {
	return file_wippy_api_hub_manifest_v1_service_proto_rawDescGZIP(), []int{5}
}

func (x *CheckUpdatesResponse) GetUpdates() []*ModuleUpdate {
	if x != nil {
		return x.Updates
	}
	return nil
}

var File_wippy_api_hub_manifest_v1_service_proto protoreflect.FileDescriptor

const file_wippy_api_hub_manifest_v1_service_proto_rawDesc = "" +
	"\n" +
	"'wippy/api/hub/manifest/v1/service.proto\x12\x19wippy.api.hub.manifest.v1\x1a\x1bbuf/validate/validate.proto\x1a'wippy/api/hub/manifest/v1/message.proto\x1a%wippy/api/hub/module/v1/message.proto\x1a&wippy/api/hub/version/v1/message.proto\"\x98\x01\n" +
	"\x12GetManifestRequest\x12B\n" +
	"\x06module\x18\x01 \x01(\v2\".wippy.api.hub.module.v1.ModuleRefB\x06\xbaH\x03\xc8\x01\x01R\x06module\x12>\n" +
	"\aversion\x18\x02 \x01(\v2$.wippy.api.hub.version.v1.VersionRefR\aversion\"\\\n" +
	"\x13GetManifestResponse\x12E\n" +
	"\bmanifest\x18\x01 \x01(\v2).wippy.api.hub.manifest.v1.ModuleManifestR\bmanifest\"\xfc\x01\n" +
	"\x1aResolveDependenciesRequest\x12I\n" +
	"\x05roots\x18\x01 \x03(\v2).wippy.api.hub.manifest.v1.DependencySpecB\b\xbaH\x05\x92\x01\x02\b\x01R\x05roots\x12H\n" +
	"\tinstalled\x18\x02 \x03(\v2*.wippy.api.hub.manifest.v1.InstalledModuleR\tinstalled\x12I\n" +
	"\bstrategy\x18\x03 \x01(\x0e2-.wippy.api.hub.manifest.v1.ResolutionStrategyR\bstrategy\"\xa6\x01\n" +
	"\x1bResolveDependenciesResponse\x12C\n" +
	"\amodules\x18\x01 \x03(\v2).wippy.api.hub.manifest.v1.ResolvedModuleR\amodules\x12B\n" +
	"\x06errors\x18\x02 \x03(\v2*.wippy.api.hub.manifest.v1.ResolutionErrorR\x06errors\"i\n" +
	"\x13CheckUpdatesRequest\x12R\n" +
	"\tinstalled\x18\x01 \x03(\v2*.wippy.api.hub.manifest.v1.InstalledModuleB\b\xbaH\x05\x92\x01\x02\b\x01R\tinstalled\"Y\n" +
	"\x14CheckUpdatesResponse\x12A\n" +
	"\aupdates\x18\x01 \x03(\v2'.wippy.api.hub.manifest.v1.ModuleUpdateR\aupdates2\x86\x03\n" +
	"\x0fManifestService\x12q\n" +
	"\vGetManifest\x12-.wippy.api.hub.manifest.v1.GetManifestRequest\x1a..wippy.api.hub.manifest.v1.GetManifestResponse\"\x03\x90\x02\x01\x12\x89\x01\n" +
	"\x13ResolveDependencies\x125.wippy.api.hub.manifest.v1.ResolveDependenciesRequest\x1a6.wippy.api.hub.manifest.v1.ResolveDependenciesResponse\"\x03\x90\x02\x01\x12t\n" +
	"\fCheckUpdates\x12..wippy.api.hub.manifest.v1.CheckUpdatesRequest\x1a/.wippy.api.hub.manifest.v1.CheckUpdatesResponse\"\x03\x90\x02\x01B\xff\x01\n" +
	"\x1dcom.wippy.api.hub.manifest.v1B\fServiceProtoP\x01ZGgithub.com/wippyai/runtime/api/hub/wippy/api/hub/manifest/v1;manifestv1\xa2\x02\x04WAHM\xaa\x02\x19Wippy.Api.Hub.Manifest.V1\xca\x02\x19Wippy\\Api\\Hub\\Manifest\\V1\xe2\x02%Wippy\\Api\\Hub\\Manifest\\V1\\GPBMetadata\xea\x02\x1dWippy::Api::Hub::Manifest::V1b\x06proto3"

var (
	file_wippy_api_hub_manifest_v1_service_proto_rawDescOnce sync.Once
	file_wippy_api_hub_manifest_v1_service_proto_rawDescData []byte
)

func file_wippy_api_hub_manifest_v1_service_proto_rawDescGZIP() []byte {
	file_wippy_api_hub_manifest_v1_service_proto_rawDescOnce.Do(func() {
		file_wippy_api_hub_manifest_v1_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_wippy_api_hub_manifest_v1_service_proto_rawDesc), len(file_wippy_api_hub_manifest_v1_service_proto_rawDesc)))
	})
	return file_wippy_api_hub_manifest_v1_service_proto_rawDescData
}

var file_wippy_api_hub_manifest_v1_service_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_wippy_api_hub_manifest_v1_service_proto_goTypes = []any{
	(*GetManifestRequest)(nil),          // 0: wippy.api.hub.manifest.v1.GetManifestRequest
	(*GetManifestResponse)(nil),         // 1: wippy.api.hub.manifest.v1.GetManifestResponse
	(*ResolveDependenciesRequest)(nil),  // 2: wippy.api.hub.manifest.v1.ResolveDependenciesRequest
	(*ResolveDependenciesResponse)(nil), // 3: wippy.api.hub.manifest.v1.ResolveDependenciesResponse
	(*CheckUpdatesRequest)(nil),         // 4: wippy.api.hub.manifest.v1.CheckUpdatesRequest
	(*CheckUpdatesResponse)(nil),        // 5: wippy.api.hub.manifest.v1.CheckUpdatesResponse
	(*v1.ModuleRef)(nil),                // 6: wippy.api.hub.module.v1.ModuleRef
	(*v11.VersionRef)(nil),              // 7: wippy.api.hub.version.v1.VersionRef
	(*ModuleManifest)(nil),              // 8: wippy.api.hub.manifest.v1.ModuleManifest
	(*DependencySpec)(nil),              // 9: wippy.api.hub.manifest.v1.DependencySpec
	(*InstalledModule)(nil),             // 10: wippy.api.hub.manifest.v1.InstalledModule
	(ResolutionStrategy)(0),             // 11: wippy.api.hub.manifest.v1.ResolutionStrategy
	(*ResolvedModule)(nil),              // 12: wippy.api.hub.manifest.v1.ResolvedModule
	(*ResolutionError)(nil),             // 13: wippy.api.hub.manifest.v1.ResolutionError
	(*ModuleUpdate)(nil),                // 14: wippy.api.hub.manifest.v1.ModuleUpdate
}
var file_wippy_api_hub_manifest_v1_service_proto_depIdxs = []int32{
	6,  // 0: wippy.api.hub.manifest.v1.GetManifestRequest.module:type_name -> wippy.api.hub.module.v1.ModuleRef
	7,  // 1: wippy.api.hub.manifest.v1.GetManifestRequest.version:type_name -> wippy.api.hub.version.v1.VersionRef
	8,  // 2: wippy.api.hub.manifest.v1.GetManifestResponse.manifest:type_name -> wippy.api.hub.manifest.v1.ModuleManifest
	9,  // 3: wippy.api.hub.manifest.v1.ResolveDependenciesRequest.roots:type_name -> wippy.api.hub.manifest.v1.DependencySpec
	10, // 4: wippy.api.hub.manifest.v1.ResolveDependenciesRequest.installed:type_name -> wippy.api.hub.manifest.v1.InstalledModule
	11, // 5: wippy.api.hub.manifest.v1.ResolveDependenciesRequest.strategy:type_name -> wippy.api.hub.manifest.v1.ResolutionStrategy
	12, // 6: wippy.api.hub.manifest.v1.ResolveDependenciesResponse.modules:type_name -> wippy.api.hub.manifest.v1.ResolvedModule
	13, // 7: wippy.api.hub.manifest.v1.ResolveDependenciesResponse.errors:type_name -> wippy.api.hub.manifest.v1.ResolutionError
	10, // 8: wippy.api.hub.manifest.v1.CheckUpdatesRequest.installed:type_name -> wippy.api.hub.manifest.v1.InstalledModule
	14, // 9: wippy.api.hub.manifest.v1.CheckUpdatesResponse.updates:type_name -> wippy.api.hub.manifest.v1.ModuleUpdate
	0,  // 10: wippy.api.hub.manifest.v1.ManifestService.GetManifest:input_type -> wippy.api.hub.manifest.v1.GetManifestRequest
	2,  // 11: wippy.api.hub.manifest.v1.ManifestService.ResolveDependencies:input_type -> wippy.api.hub.manifest.v1.ResolveDependenciesRequest
	4,  // 12: wippy.api.hub.manifest.v1.ManifestService.CheckUpdates:input_type -> wippy.api.hub.manifest.v1.CheckUpdatesRequest
	1,  // 13: wippy.api.hub.manifest.v1.ManifestService.GetManifest:output_type -> wippy.api.hub.manifest.v1.GetManifestResponse
	3,  // 14: wippy.api.hub.manifest.v1.ManifestService.ResolveDependencies:output_type -> wippy.api.hub.manifest.v1.ResolveDependenciesResponse
	5,  // 15: wippy.api.hub.manifest.v1.ManifestService.CheckUpdates:output_type -> wippy.api.hub.manifest.v1.CheckUpdatesResponse
	13, // [13:16] is the sub-list for method output_type
	10, // [10:13] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_wippy_api_hub_manifest_v1_service_proto_init() }
func file_wippy_api_hub_manifest_v1_service_proto_init() {
	if File_wippy_api_hub_manifest_v1_service_proto != nil {
		return
	}
	file_wippy_api_hub_manifest_v1_message_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_wippy_api_hub_manifest_v1_service_proto_rawDesc), len(file_wippy_api_hub_manifest_v1_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_wippy_api_hub_manifest_v1_service_proto_goTypes,
		DependencyIndexes: file_wippy_api_hub_manifest_v1_service_proto_depIdxs,
		MessageInfos:      file_wippy_api_hub_manifest_v1_service_proto_msgTypes,
	}.Build()
	File_wippy_api_hub_manifest_v1_service_proto = out.File
	file_wippy_api_hub_manifest_v1_service_proto_goTypes = nil
	file_wippy_api_hub_manifest_v1_service_proto_depIdxs = nil
}
