name: Linters

on: [push, pull_request]

jobs:
  linters:
    name: Golang-CI (lint)
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v5
        with:
          token: ${{ secrets.PAT_TOKEN }}  # Required for private modules

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: stable

      - name: Install C dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential

      - name: Configure Go environment
        run: |
          git config --global url."https://${{ secrets.PAT_TOKEN }}@github.com/".insteadOf "https://github.com/"
          go env -w GOPRIVATE=github.com/ponyruntime/*
          go env -w GONOSUMDB=github.com/ponyruntime/*
          go env -w CGO_ENABLED=1

      - name: Run linter
        uses: golangci/golangci-lint-action@v7.0.0
        env:
          CGO_ENABLED: 1
        with:
          version: v2.1.5
          only-new-issues: false
          args: --timeout=10m --build-tags=race ./...