name: Native Exec Cross Platform Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:  # Allow manual triggering

jobs:
  build-and-run:
    name: Build and Run on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Go
        uses: actions/setup-go@v5
      
      - name: Build Go program
        if: matrix.os == 'ubuntu-latest'
        run: go build -o test-app ./service/exec/native/testdata

      - name: Run executable (Ubuntu)
        if: matrix.os == 'ubuntu-latest'
        run: ./test-app

      - name: Build Go program
        if: matrix.os == 'windows-latest'
        run: go build -o test-app.exe ./service/exec/native/testdata

      - name: Run executable (Windows)
        if: matrix.os == 'windows-latest'
        run: .\test-app.exe
