name: pony_tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  tests:
    name: Pony Tests (Go ${{ matrix.go }}, OS ${{matrix.os}})
    runs-on: ${{ matrix.os }}
    timeout-minutes: 60
    strategy:
      matrix:
        go: [stable]
        os: ["ubuntu-latest"]
    steps:
      - name: Set up Go ${{ matrix.go }}
        uses: actions/setup-go@v5 # action page: <https://github.com/actions/setup-go>
        with:
          go-version: ${{ matrix.go }}

      - name: Configure Git for private modules
        run: |
          git config --global url."https://${{ secrets.GH_TOKEN }}@github.com".insteadOf "https://github.com"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure Go private modules
        run: |
          go env -w GOPRIVATE=github.com/ponyruntime/*
          go env -w GONOSUMDB=github.com/ponyruntime/*
          go env -w GONOPROXY=github.com/ponyruntime/*

      - name: Check out code
        uses: actions/checkout@v4

      - name: Install Go dependencies
        run: go mod download

      - name: Run golang tests
        run: |
          go test -v -race ./...
