name: pony_tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  tests:
    name: Wippy Tests (Go ${{ matrix.go }}, OS ${{matrix.os}})
    runs-on: ${{ matrix.os }}
    timeout-minutes: 60
    strategy:
      matrix:
        go: [stable]
        os: ["ubuntu-latest", "windows-latest"]
    steps:
      - name: Check out code
        uses: actions/checkout@v5
        with:
          token: ${{ secrets.PAT_TOKEN }}  # Use Personal Access Token

      - name: Setup msys
        if: matrix.os == 'windows-latest'
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          install: mingw-w64-x86_64-toolchain mingw-w64-x86_64-sqlite3
          path-type: inherit

      - name: Set up Go ${{ matrix.go }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}

      - name: Configure Git and Go for private modules
        run: |
          # Configure Git to use PAT for authentication
          git config --global url."https://${{ secrets.PAT_TOKEN }}@github.com/".insteadOf "https://github.com/"
          
          # Configure Go to skip verification for private modules
          go env -w GOPRIVATE=github.com/ponyruntime/*
          go env -w GONOSUMDB=github.com/ponyruntime/*
          go env -w GONOPROXY=github.com/ponyruntime/*

      - name: Install Go dependencies
        run: |
          go mod download

      - name: Run golang tests
        if: matrix.os != 'windows-latest'
        env:
          CGO_ENABLED: 1
        run: |
          go test --tags "fts5 sqlite_vec" -race ./...

      - name: Run golang tests
        if: matrix.os == 'windows-latest'
        env:
          CGO_ENABLED: 1
        run: |
          go test --tags "fts5 sqlite_vec" -race ./...
        shell: msys2 {0}
